import type { Question } from "@/lib/data/questions/types";
import { buildRobloxCodeConceptQuestions, type RobloxCodeConceptSpec } from "@/lib/robloxCourse/builders";

const clickDetectorSpec: RobloxCodeConceptSpec = {
  concept: "click-detector",
  title: "ClickDetector",
  nodeType: "teaching",
  definitions: [
    {
      prompt: "What is a `ClickDetector` used for in Roblox?",
      options: [
        "Letting players click a world object and trigger code",
        "Saving persistent player data",
        "Animating properties over time",
        "Opening the Properties panel in Studio",
      ],
      correctIndex: 0,
      explanation: "`ClickDetector` is placed on a world object so player clicks can trigger gameplay behavior.",
    },
    {
      prompt: "Where is a `ClickDetector` commonly parented?",
      options: [
        "Inside a Part or other world object that should be clickable",
        "Only inside StarterGui",
        "Inside the Terrain Editor panel",
        "Inside DataStoreService",
      ],
      correctIndex: 0,
      explanation: "A `ClickDetector` is usually parented to a clickable world object like a Part.",
    },
    {
      prompt: "Which event on a `ClickDetector` is commonly used when a player clicks it?",
      options: [
        "MouseClick",
        "Touched",
        "PlayerAdded",
        "OnServerEvent",
      ],
      correctIndex: 0,
      explanation: "`MouseClick` is the event that fires when a player clicks the detector in the world.",
    },
    {
      prompt: "Why would a developer use a `ClickDetector`?",
      options: [
        "To make buttons, doors, or world props react to player clicks",
        "To fetch Roblox services from `game`",
        "To save data to a datastore",
        "To paint terrain materials",
      ],
      correctIndex: 0,
      explanation: "`ClickDetector` is a simple way to make world objects interactive through clicks.",
    },
  ],
  truths: [
    {
      prompt: "A `ClickDetector` can be created with `Instance.new(\"ClickDetector\")`.",
      correct: true,
      explanation: "ClickDetector is a normal Roblox Instance class created through `Instance.new()`.",
      code: "local clickDetector = Instance.new(\"ClickDetector\")\nprint(clickDetector.ClassName)",
    },
    {
      prompt: "The `MouseClick` member on a ClickDetector is an event signal.",
      correct: true,
      explanation: "`MouseClick` is an `RBXScriptSignal`, so scripts connect a callback with `:Connect()`.",
      code: "local clickDetector = Instance.new(\"ClickDetector\")\nprint(typeof(clickDetector.MouseClick))",
    },
    {
      prompt: "A `ClickDetector` is normally parented to a clickable world object such as a Part.",
      correct: true,
      explanation: "The detector is attached to the object the player will click in the world.",
    },
    {
      prompt: "A `ClickDetector` is only for GUI buttons and cannot be used on world objects.",
      correct: false,
      explanation: "ClickDetectors are specifically for world-space click interaction on objects like parts and models.",
    },
  ],
  examples: [
    {
      mcOutputPrompt: "What does this print?",
      mcOutputCode: "local clickDetector = Instance.new(\"ClickDetector\")\nprint(clickDetector.ClassName)",
      mcOutputOptions: ["ClickDetector", "MouseClick", "Part", "Detector"],
      mcOutputCorrectIndex: 0,
      mcOutputExplanation: "The object's class name is `ClickDetector`.",
      fillTypePrompt: "Type the class name so the code creates a world click detector.",
      fillTypeCode: "local clickDetector = Instance.new(\"___\")",
      fillTypeAnswer: "ClickDetector",
      fillTypeExplanation: "`ClickDetector` is the Roblox class for world click detection.",
      fillTypeHint: "Use the object class that lets players click a world part.",
      fillSelectPrompt: "Fill the blanks so the script creates a ClickDetector and prints its class.",
      fillSelectCode: "local clickDetector = Instance.new(\"___\")\nprint(clickDetector.___)",
      fillSelectTokens: ["ClickDetector", "ClassName", "Name", "Players"],
      fillSelectAnswer: ["ClickDetector", "ClassName"],
      fillSelectExplanation: "The object is a `ClickDetector`, and `ClassName` prints that type.",
      wordBankPrompt: "Build the line that stores a new ClickDetector in a variable.",
      wordBankTokens: ["local", "clickDetector", "=", "Instance.new(\"ClickDetector\")", "workspace", "clickDetector.Name"],
      wordBankAnswer: ["local", "clickDetector", "=", "Instance.new(\"ClickDetector\")"],
      wordBankExplanation: "That line creates the detector object and stores it locally.",
      predictPrompt: "What does this print?",
      predictCode: "local clickDetector = Instance.new(\"ClickDetector\")\nprint(typeof(clickDetector.MouseClick))",
      predictAnswer: "RBXScriptSignal",
      predictExplanation: "`MouseClick` is the detector's event signal, so `typeof` reports `RBXScriptSignal`.",
    },
    {
      mcOutputPrompt: "What does this print after the detector is parented?",
      mcOutputCode: "local part = Instance.new(\"Part\")\nlocal clickDetector = Instance.new(\"ClickDetector\")\nclickDetector.Parent = part\nprint(clickDetector.Parent == part)",
      mcOutputOptions: ["true", "false", "ClickDetector", "Part"],
      mcOutputCorrectIndex: 0,
      mcOutputExplanation: "The detector was parented to the part, so the comparison is true.",
      fillTypePrompt: "Type the event name so the script refers to the click signal on the detector.",
      fillTypeCode: "local clickDetector = Instance.new(\"ClickDetector\")\nprint(typeof(clickDetector.___))",
      fillTypeAnswer: "MouseClick",
      fillTypeExplanation: "`MouseClick` is the event signal fired when a player clicks the detector.",
      fillSelectPrompt: "Fill the blanks so the detector is parented into the part and then checked.",
      fillSelectCode: "local part = Instance.new(\"Part\")\nlocal clickDetector = Instance.new(\"ClickDetector\")\nclickDetector.Parent = ___\nprint(clickDetector.Parent == ___)",
      fillSelectTokens: ["part", "part", "workspace", "Players"],
      fillSelectAnswer: ["part", "part"],
      fillSelectExplanation: "The detector is parented to `part`, and the comparison checks against the same variable.",
      wordBankPrompt: "Build the line that parents the ClickDetector into the part.",
      wordBankTokens: ["clickDetector.Parent", "=", "part", "workspace", "clickDetector.Name", "\"DoorClick\""],
      wordBankAnswer: ["clickDetector.Parent", "=", "part"],
      wordBankExplanation: "That line attaches the detector to the world object players should click.",
      predictPrompt: "What does this print?",
      predictCode: "local part = Instance.new(\"Part\")\nlocal clickDetector = Instance.new(\"ClickDetector\")\nclickDetector.Parent = part\nprint(clickDetector.Parent.ClassName)",
      predictAnswer: "Part",
      predictExplanation: "The detector's parent is a Part, so the parent's class name prints as `Part`.",
    },
    {
      mcOutputPrompt: "What does this print if the detector is connected but never clicked?",
      mcOutputCode: "local clickDetector = Instance.new(\"ClickDetector\")\nlocal clicked = false\nclickDetector.MouseClick:Connect(function(player)\n    clicked = true\nend)\nprint(clicked)",
      mcOutputOptions: ["false", "true", "ClickDetector", "nil"],
      mcOutputCorrectIndex: 0,
      mcOutputExplanation: "The callback is connected, but nothing clicks the detector in this snippet, so `clicked` stays false.",
      fillTypePrompt: "Type the method name used to subscribe to the MouseClick event.",
      fillTypeCode: "local clickDetector = Instance.new(\"ClickDetector\")\nclickDetector.MouseClick:___(function(player)\n    print(player.Name)\nend)",
      fillTypeAnswer: "Connect",
      fillTypeExplanation: "`Connect` subscribes a callback to the MouseClick signal.",
      fillSelectPrompt: "Fill the blanks so the callback parameter is declared and then printed.",
      fillSelectCode: "local clickDetector = Instance.new(\"ClickDetector\")\nclickDetector.MouseClick:Connect(function(___)\n    print(___.Name)\nend)",
      fillSelectTokens: ["player", "player", "hit", "workspace"],
      fillSelectAnswer: ["player", "player"],
      fillSelectExplanation: "The MouseClick callback typically receives the clicking player, here named `player`.",
      wordBankPrompt: "Build the line that prints the type of the MouseClick signal.",
      wordBankTokens: ["print", "(", "typeof(clickDetector.MouseClick)", ")", "workspace", "Connect"],
      wordBankAnswer: ["print", "(", "typeof(clickDetector.MouseClick)", ")"],
      wordBankExplanation: "Printing `typeof(clickDetector.MouseClick)` confirms that it is an event signal.",
      predictPrompt: "What does this print?",
      predictCode: "local clickDetector = Instance.new(\"ClickDetector\")\nlocal connection = clickDetector.MouseClick:Connect(function() end)\nprint(typeof(connection))",
      predictAnswer: "RBXScriptConnection",
      predictExplanation: "Connecting the event returns an `RBXScriptConnection` object.",
    },
    {
      mcOutputPrompt: "What does this print?",
      mcOutputCode: "local clickDetector = Instance.new(\"ClickDetector\")\nprint(clickDetector.Name == \"ClickDetector\")",
      mcOutputOptions: ["true", "false", "ClickDetector", "RBXScriptSignal"],
      mcOutputCorrectIndex: 0,
      mcOutputExplanation: "A new ClickDetector starts with the default name `ClickDetector`, so the equality check is true.",
      fillTypePrompt: "Type the event name that runs when a player clicks the detector.",
      fillTypeCode: "clickDetector.___:Connect(function(player)\n    print(player.Name)\nend)",
      fillTypeAnswer: "MouseClick",
      fillTypeExplanation: "`MouseClick` is the event signal for player click interaction on a ClickDetector.",
      fillSelectPrompt: "Fill the blanks so the script reads the click signal and prints its type.",
      fillSelectCode: "local clickDetector = Instance.new(\"ClickDetector\")\nlocal signal = clickDetector.___\nprint(typeof(___))",
      fillSelectTokens: ["MouseClick", "signal", "Touched", "workspace"],
      fillSelectAnswer: ["MouseClick", "signal"],
      fillSelectExplanation: "The event is `MouseClick`, and `signal` is the variable storing it.",
      wordBankPrompt: "Build the line that listens for player clicks on the detector.",
      wordBankTokens: ["clickDetector.MouseClick:Connect(function(player)", "print(player.Name)", "end)", "workspace", "clickDetector.Name", "="],
      wordBankAnswer: ["clickDetector.MouseClick:Connect(function(player)", "print(player.Name)", "end)"],
      wordBankExplanation: "Those tokens form a valid one-line click event connection.",
      predictPrompt: "What does this print?",
      predictCode: "local clickDetector = Instance.new(\"ClickDetector\")\nprint(clickDetector.ClassName == \"ClickDetector\")",
      predictAnswer: "true",
      predictExplanation: "The created object's class is ClickDetector, so the equality check is true.",
    },
  ],
  arrange: [
    {
      prompt: "Arrange the code so a part is created, a ClickDetector is added to it, and the parent is printed.",
      lines: [
        "local part = Instance.new(\"Part\")",
        "local clickDetector = Instance.new(\"ClickDetector\")",
        "clickDetector.Parent = part",
      ],
      correctOrder: [0, 1, 2],
      explanation: "Create the part first, create the detector second, then parent the detector into the part.",
    },
    {
      prompt: "Arrange the code so the detector listens for clicks and prints the clicking player's name.",
      lines: [
        "local clickDetector = Instance.new(\"ClickDetector\")",
        "clickDetector.MouseClick:Connect(function(player)\n    print(player.Name)\nend)",
        "print(typeof(clickDetector.MouseClick))",
      ],
      correctOrder: [0, 1, 2],
      explanation: "The detector must exist before its event can be connected or inspected.",
    },
    {
      prompt: "Arrange the code so the MouseClick signal is stored and checked for nil.",
      lines: [
        "local clickDetector = Instance.new(\"ClickDetector\")",
        "local signal = clickDetector.MouseClick",
        "print(signal ~= nil)",
      ],
      correctOrder: [0, 1, 2],
      explanation: "Create the detector first, then store its signal, then check the result.",
    },
  ],
  bugs: [
    {
      prompt: "Which version has the bug if the goal is to create a ClickDetector?",
      versionA: "local clickDetector = Instance.new(\"ClickDetector\")",
      versionB: "local clickDetector = Instance.new(\"Click Detector\")",
      buggyVersion: "B",
      explanation: "The class name must be exactly `ClickDetector` without a space.",
    },
    {
      prompt: "Which version has the bug if the goal is to listen for player clicks?",
      versionA: "clickDetector.MouseClick:Connect(function(player)\n    print(player.Name)\nend)",
      versionB: "clickDetector.MouseClick(function(player)\n    print(player.Name)\nend)",
      buggyVersion: "B",
      explanation: "The click signal uses `:Connect()` to subscribe a callback.",
    },
    {
      prompt: "Which version has the bug if the goal is to attach the detector to the part?",
      versionA: "clickDetector.Parent = part",
      versionB: "part.Parent = clickDetector",
      buggyVersion: "B",
      explanation: "The ClickDetector should be parented into the part, not the other way around.",
    },
  ],
};

export const clickDetectorQuestions: Question[] = buildRobloxCodeConceptQuestions(clickDetectorSpec);
