import type { Question } from "@/lib/data/questions/types";
import { buildRobloxCodeConceptQuestions, type RobloxCodeConceptSpec } from "@/lib/robloxCourse/builders";

const dataStoreServiceSpec: RobloxCodeConceptSpec = {
  concept: "data-store-service",
  title: "DataStoreService",
  nodeType: "teaching",
  definitions: [
    {
      prompt: "What is `DataStoreService` mainly used for in Roblox?",
      options: [
        "Saving and loading persistent game data",
        "Drawing 2D GUI labels on the screen",
        "Animating parts with tweens",
        "Listing objects in the Explorer panel",
      ],
      correctIndex: 0,
      explanation: "`DataStoreService` provides access to persistent storage so Roblox games can save and load player or game data.",
    },
    {
      prompt: "Which method on `DataStoreService` gets a named datastore object?",
      options: [
        "GetDataStore()",
        "CreateStore()",
        "OpenStore()",
        "FetchSave()",
      ],
      correctIndex: 0,
      explanation: "`GetDataStore()` returns a named datastore handle that scripts can use for operations like `GetAsync` and `SetAsync`.",
    },
    {
      prompt: "Why do Roblox developers often wrap datastore operations in `pcall`?",
      options: [
        "Because datastore calls can fail and should be handled safely",
        "Because `pcall` is required for all `print()` statements",
        "Because datastore objects are Studio panels, not code objects",
        "Because `pcall` automatically creates the datastore for you",
      ],
      correctIndex: 0,
      explanation: "Datastore operations can error, so `pcall` helps scripts handle failures instead of crashing outright.",
    },
    {
      prompt: "Which line correctly gets DataStoreService?",
      options: [
        "local dataStoreService = game:GetService(\"DataStoreService\")",
        "local dataStoreService = DataStoreService.new()",
        "local dataStoreService = workspace.DataStoreService",
        "local dataStoreService = game:GetDataStoreService()",
      ],
      correctIndex: 0,
      explanation: "Like other Roblox services, DataStoreService is accessed with `game:GetService()`.",
    },
  ],
  truths: [
    {
      prompt: "`DataStoreService` is a Roblox service fetched with `game:GetService(\"DataStoreService\")`.",
      correct: true,
      explanation: "It is part of the Roblox service set and is accessed through the DataModel.",
      code: "local dataStoreService = game:GetService(\"DataStoreService\")\nprint(dataStoreService.Name)",
    },
    {
      prompt: "`GetDataStore(\"PlayerCoins\")` is how you request a named datastore handle.",
      correct: true,
      explanation: "`GetDataStore()` returns the datastore object associated with the given name.",
    },
    {
      prompt: "Datastore values are only for temporary per-frame variables that never need to persist.",
      correct: false,
      explanation: "Datastores are specifically for persistence across sessions, not just temporary runtime values.",
    },
    {
      prompt: "`DataStoreService` is a Studio tab like Home or View.",
      correct: false,
      explanation: "DataStoreService is a runtime Roblox service, not a Studio ribbon tab.",
    },
  ],
  examples: [
    {
      mcOutputPrompt: "What does this print?",
      mcOutputCode: "local dataStoreService = game:GetService(\"DataStoreService\")\nprint(dataStoreService.Name)",
      mcOutputOptions: ["DataStoreService", "DataStore", "Players", "nil"],
      mcOutputCorrectIndex: 0,
      mcOutputExplanation: "The service object's `Name` property is `DataStoreService`.",
      fillTypePrompt: "Type the service name so the script gets the Roblox datastore service.",
      fillTypeCode: "local dataStoreService = game:GetService(\"___\")",
      fillTypeAnswer: "DataStoreService",
      fillTypeExplanation: "The service name string must be exactly `DataStoreService`.",
      fillTypeHint: "Use the service that handles persistent saved data.",
      fillSelectPrompt: "Fill the blanks so the script gets the service and prints its class name.",
      fillSelectCode: "local dataStoreService = game:GetService(\"___\")\nprint(dataStoreService.___)",
      fillSelectTokens: ["DataStoreService", "ClassName", "Name", "Players"],
      fillSelectAnswer: ["DataStoreService", "ClassName"],
      fillSelectExplanation: "The service is `DataStoreService`, and `ClassName` prints its Roblox type.",
      wordBankPrompt: "Build the line that stores DataStoreService in a variable.",
      wordBankTokens: ["local", "dataStoreService", "=", "game:GetService(\"DataStoreService\")", "workspace", "dataStoreService.Name"],
      wordBankAnswer: ["local", "dataStoreService", "=", "game:GetService(\"DataStoreService\")"],
      wordBankExplanation: "That line fetches the service so the script can work with persistent data.",
      predictPrompt: "What does this print?",
      predictCode: "local dataStoreService = game:GetService(\"DataStoreService\")\nprint(dataStoreService.ClassName)",
      predictAnswer: "DataStoreService",
      predictExplanation: "The service object's class name is `DataStoreService`.",
    },
    {
      mcOutputPrompt: "What does this print?",
      mcOutputCode: "local dataStoreService = game:GetService(\"DataStoreService\")\nprint(dataStoreService == game:GetService(\"DataStoreService\"))",
      mcOutputOptions: ["true", "false", "DataStoreService", "nil"],
      mcOutputCorrectIndex: 0,
      mcOutputExplanation: "Both expressions fetch the same service object, so the comparison is true.",
      fillTypePrompt: "Type the method name used to request a named datastore handle.",
      fillTypeCode: "local store = game:GetService(\"DataStoreService\"):___(\"PlayerCoins\")",
      fillTypeAnswer: "GetDataStore",
      fillTypeExplanation: "`GetDataStore()` returns a named datastore object like `PlayerCoins`.",
      fillSelectPrompt: "Fill the blanks so the script gets the service and then requests the `PlayerCoins` datastore.",
      fillSelectCode: "local dataStoreService = game:GetService(\"___\")\nlocal store = dataStoreService:___(\"PlayerCoins\")",
      fillSelectTokens: ["DataStoreService", "GetDataStore", "Players", "CreateStore"],
      fillSelectAnswer: ["DataStoreService", "GetDataStore"],
      fillSelectExplanation: "The service is `DataStoreService`, and the handle is requested with `GetDataStore()`.",
      wordBankPrompt: "Build the line that requests the `PlayerCoins` datastore.",
      wordBankTokens: ["local", "store", "=", "dataStoreService:GetDataStore(\"PlayerCoins\")", "workspace", "store.Name"],
      wordBankAnswer: ["local", "store", "=", "dataStoreService:GetDataStore(\"PlayerCoins\")"],
      wordBankExplanation: "That line gets a datastore handle named `PlayerCoins`.",
      predictPrompt: "What does this print?",
      predictCode: "local store = game:GetService(\"DataStoreService\"):GetDataStore(\"PlayerCoins\")\nprint(store ~= nil)",
      predictAnswer: "true",
      predictExplanation: "`GetDataStore()` returns a datastore handle object, so the result is not nil.",
    },
    {
      mcOutputPrompt: "What does this print?",
      mcOutputCode: "local store = game:GetService(\"DataStoreService\"):GetDataStore(\"PlayerCoins\")\nprint(store ~= nil)",
      mcOutputOptions: ["true", "false", "PlayerCoins", "DataStoreService"],
      mcOutputCorrectIndex: 0,
      mcOutputExplanation: "Requesting a named datastore returns a datastore handle, so the comparison to nil is true.",
      fillTypePrompt: "Type the safety helper that commonly wraps datastore operations.",
      fillTypeCode: "local success, result = ___(function()\n    return store:GetAsync(\"Player_1\")\nend)",
      fillTypeAnswer: "pcall",
      fillTypeExplanation: "`pcall` safely catches errors from datastore operations like `GetAsync` and `SetAsync`.",
      fillSelectPrompt: "Fill the blanks so the code safely calls `GetAsync` on the datastore.",
      fillSelectCode: "local success, result = ___(function()\n    return store:___(\"Player_1\")\nend)",
      fillSelectTokens: ["pcall", "GetAsync", "SetAsync", "workspace"],
      fillSelectAnswer: ["pcall", "GetAsync"],
      fillSelectExplanation: "`pcall` wraps the call safely, and `GetAsync` reads a saved value.",
      wordBankPrompt: "Build the line that writes a value into the datastore handle.",
      wordBankTokens: ["store:SetAsync(\"Player_1\", 50)", "store:GetAsync(\"Player_1\")", "=", "workspace", "print(store)"],
      wordBankAnswer: ["store:SetAsync(\"Player_1\", 50)"],
      wordBankExplanation: "`SetAsync` is the method commonly used to save a value into a datastore key.",
      predictPrompt: "What does this print?",
      predictCode: "local dataStoreService = game:GetService(\"DataStoreService\")\nprint(dataStoreService.Name == \"DataStoreService\")",
      predictAnswer: "true",
      predictExplanation: "The service name is exactly `DataStoreService`, so the comparison is true.",
    },
    {
      mcOutputPrompt: "What does this print?",
      mcOutputCode: "local dataStoreService = game:GetService(\"DataStoreService\")\nprint(dataStoreService.ClassName == \"DataStoreService\")",
      mcOutputOptions: ["true", "false", "DataStore", "nil"],
      mcOutputCorrectIndex: 0,
      mcOutputExplanation: "The class name of the service object is `DataStoreService`, so the equality check is true.",
      fillTypePrompt: "Type the datastore method that saves a value for a key.",
      fillTypeCode: "store:___(\"Player_1\", 50)",
      fillTypeAnswer: "SetAsync",
      fillTypeExplanation: "`SetAsync` writes a value to a key in the datastore.",
      fillSelectPrompt: "Fill the blanks so the code safely saves a value with `SetAsync`.",
      fillSelectCode: "local success = ___(function()\n    store:___(\"Player_1\", 50)\nend)",
      fillSelectTokens: ["pcall", "SetAsync", "GetAsync", "workspace"],
      fillSelectAnswer: ["pcall", "SetAsync"],
      fillSelectExplanation: "`pcall` wraps the datastore write safely, and `SetAsync` performs the save.",
      wordBankPrompt: "Build the line that safely begins a datastore read call.",
      wordBankTokens: ["local", "success,", "result", "=", "pcall(function()", "workspace", "store:GetAsync(\"Player_1\")"],
      wordBankAnswer: ["local", "success,", "result", "=", "pcall(function()"],
      wordBankExplanation: "That token sequence starts the common `pcall` pattern used around datastore operations.",
      predictPrompt: "What does this print?",
      predictCode: "local dataStoreService = game:GetService(\"DataStoreService\")\nlocal sameService = dataStoreService == game:GetService(\"DataStoreService\")\nprint(sameService)",
      predictAnswer: "true",
      predictExplanation: "Both variables reference the same DataStoreService object.",
    },
  ],
  arrange: [
    {
      prompt: "Arrange the code so DataStoreService is fetched and a named datastore handle is requested.",
      lines: [
        "local dataStoreService = game:GetService(\"DataStoreService\")",
        "local store = dataStoreService:GetDataStore(\"PlayerCoins\")",
        "print(store ~= nil)",
      ],
      correctOrder: [0, 1, 2],
      explanation: "Get the service first, request the named datastore second, then inspect the result.",
    },
    {
      prompt: "Arrange the code so a datastore read is wrapped in `pcall`.",
      lines: [
        "local success, result = pcall(function()",
        "    return store:GetAsync(\"Player_1\")",
        "end)",
      ],
      correctOrder: [0, 1, 2],
      explanation: "The `pcall` starts first, the datastore call runs inside the function, and `end)` closes the safe wrapper.",
    },
    {
      prompt: "Arrange the code so a datastore write is wrapped in `pcall`.",
      lines: [
        "local success = pcall(function()",
        "    store:SetAsync(\"Player_1\", 50)",
        "end)",
      ],
      correctOrder: [0, 1, 2],
      explanation: "The `SetAsync` call belongs inside the function passed to `pcall`.",
    },
  ],
  bugs: [
    {
      prompt: "Which version has the bug if the goal is to get DataStoreService?",
      versionA: "local dataStoreService = game:GetService(\"DataStoreService\")",
      versionB: "local dataStoreService = game:GetService(\"Data Store Service\")",
      buggyVersion: "B",
      explanation: "The service name must be exactly `DataStoreService` without spaces.",
    },
    {
      prompt: "Which version has the bug if the goal is to request a named datastore handle?",
      versionA: "local store = dataStoreService:GetDataStore(\"PlayerCoins\")",
      versionB: "local store = dataStoreService:GetStore(\"PlayerCoins\")",
      buggyVersion: "B",
      explanation: "The correct method is `GetDataStore()`, not `GetStore()`.",
    },
    {
      prompt: "Which version has the bug if the goal is to save a value under a key?",
      versionA: "store:SetAsync(\"Player_1\", 50)",
      versionB: "store:Set(\"Player_1\", 50)",
      buggyVersion: "B",
      explanation: "Datastore writes use `SetAsync`, not `Set`.",
    },
  ],
};

export const dataStoreServiceQuestions: Question[] = buildRobloxCodeConceptQuestions(dataStoreServiceSpec);
