import type { Question } from "@/lib/data/questions/types";
import { buildRobloxCodeConceptQuestions, type RobloxCodeConceptSpec } from "@/lib/robloxCourse/builders";

const eventsConnectSpec: RobloxCodeConceptSpec = {
  concept: "events-connect",
  title: "Events and :Connect",
  nodeType: "practice",
  definitions: [
    {
      prompt: "What does `:Connect()` do on a Roblox event signal?",
      options: [
        "It attaches a function that runs when the event fires",
        "It creates a new Part in Workspace",
        "It publishes the place to Roblox",
        "It opens the Properties panel in Studio",
      ],
      correctIndex: 0,
      explanation: "`:Connect()` links an event signal to a callback function so your code can react when the event fires.",
    },
    {
      prompt: "Which value is usually to the left of `:Connect()` in Roblox Lua?",
      options: [
        "An event signal such as `bindable.Event` or `part.Touched`",
        "A Studio panel like Explorer",
        "A terrain brush size number",
        "A class name string like `\"Part\"`",
      ],
      correctIndex: 0,
      explanation: "You call `:Connect()` on an event signal, not on an editor panel or class name string.",
    },
    {
      prompt: "Why does Roblox Lua use a colon in `signal:Connect(function() end)`?",
      options: [
        "Because `Connect` is a method on the signal object",
        "Because the code is defining a new class",
        "Because the callback must run on the client only",
        "Because the event is a string, not an object",
      ],
      correctIndex: 0,
      explanation: "`Connect` is a method call on the event signal object, so Roblox Lua uses the method-call colon syntax.",
    },
    {
      prompt: "What is the function passed into `:Connect()` used for?",
      options: [
        "Handling the event when it happens",
        "Declaring a new Studio ribbon tab",
        "Renaming the event signal itself",
        "Replacing `game:GetService()`",
      ],
      correctIndex: 0,
      explanation: "The callback function contains the code that should run when the event actually fires.",
    },
  ],
  truths: [
    {
      prompt: "A Roblox event signal can run a callback through `:Connect(function() ... end)`.",
      correct: true,
      explanation: "That is the standard Roblox event subscription pattern for signals like `Touched`, `PlayerAdded`, and `OnServerEvent`.",
      code: "local bindable = Instance.new(\"BindableEvent\")\nbindable.Event:Connect(function()\n    print(\"Fired\")\nend)",
    },
    {
      prompt: "When an event fires with values, the callback function can receive those values as parameters.",
      correct: true,
      explanation: "Callback parameters are how Roblox passes event data like the touching part, player, or clicked button.",
    },
    {
      prompt: "You connect to a Roblox event by assigning text directly into `signal.Connect`.",
      correct: false,
      explanation: "Roblox event signals use the method call `signal:Connect(function() end)`, not string assignment.",
    },
    {
      prompt: "The callback passed to `:Connect()` runs immediately even if the event never fires.",
      correct: false,
      explanation: "The callback only runs when the event actually fires. Connecting alone does not trigger it.",
      code: "local bindable = Instance.new(\"BindableEvent\")\nbindable.Event:Connect(function()\n    print(\"Now\")\nend)",
    },
  ],
  examples: [
    {
      mcOutputPrompt: "What does this print?",
      mcOutputCode: "local bindable = Instance.new(\"BindableEvent\")\nbindable.Event:Connect(function()\n    print(\"Ping\")\nend)\nbindable:Fire()",
      mcOutputOptions: ["Ping", "BindableEvent", "true", "Nothing"],
      mcOutputCorrectIndex: 0,
      mcOutputExplanation: "The callback is connected first, then the event is fired once, so `Ping` is printed.",
      fillTypePrompt: "Type the missing method name so the callback is connected to the event.",
      fillTypeCode: "local bindable = Instance.new(\"BindableEvent\")\nbindable.Event:___(function()\n    print(\"Ping\")\nend)",
      fillTypeAnswer: "Connect",
      fillTypeExplanation: "`Connect` is the method used to subscribe a callback to a Roblox event signal.",
      fillTypeHint: "Use the usual event subscription method name.",
      fillSelectPrompt: "Fill the blanks so the event is connected and then fired.",
      fillSelectCode: "local bindable = Instance.new(\"BindableEvent\")\nbindable.Event:___(function()\n    print(\"Ping\")\nend)\nbindable:___()",
      fillSelectTokens: ["Connect", "Fire", "Wait", "Destroy"],
      fillSelectAnswer: ["Connect", "Fire"],
      fillSelectExplanation: "First you connect the callback, then you fire the BindableEvent.",
      wordBankPrompt: "Build the line that fires the BindableEvent.",
      wordBankTokens: ["bindable:Fire()", "bindable.Event", "=", "\"Fire\"", "workspace", "print(bindable)"],
      wordBankAnswer: ["bindable:Fire()"],
      wordBankExplanation: "`Fire()` triggers the BindableEvent so connected callbacks can run.",
      predictPrompt: "What does this print?",
      predictCode: "local bindable = Instance.new(\"BindableEvent\")\nlocal total = 0\nbindable.Event:Connect(function()\n    total = total + 1\nend)\nbindable:Fire()\nprint(total)",
      predictAnswer: "1",
      predictExplanation: "The event fires once, so the callback adds 1 to `total` one time.",
    },
    {
      mcOutputPrompt: "What does this print?",
      mcOutputCode: "local bindable = Instance.new(\"BindableEvent\")\nlocal total = 0\nbindable.Event:Connect(function()\n    total = total + 1\nend)\nbindable:Fire()\nbindable:Fire()\nprint(total)",
      mcOutputOptions: ["2", "1", "0", "true"],
      mcOutputCorrectIndex: 0,
      mcOutputExplanation: "The callback runs once for each fire, so the counter becomes 2.",
      fillTypePrompt: "Type the event property name on a BindableEvent so you can connect a callback.",
      fillTypeCode: "local bindable = Instance.new(\"BindableEvent\")\nbindable.___:Connect(function()\n    print(\"Hi\")\nend)",
      fillTypeAnswer: "Event",
      fillTypeExplanation: "BindableEvent exposes the signal through its `Event` property.",
      fillSelectPrompt: "Fill the blanks so the callback receives the fired message and prints it.",
      fillSelectCode: "local bindable = Instance.new(\"BindableEvent\")\nbindable.Event:Connect(function(___)\n    print(___)\nend)\nbindable:Fire(\"Coins\")",
      fillSelectTokens: ["message", "message", "players", "workspace"],
      fillSelectAnswer: ["message", "message"],
      fillSelectExplanation: "The same callback parameter name is used when receiving and printing the fired value.",
      wordBankPrompt: "Build the line that connects a callback to the BindableEvent signal.",
      wordBankTokens: ["bindable.Event:Connect(function()", "print(\"Hi\")", "end)", "workspace", "bindable.Name", "="],
      wordBankAnswer: ["bindable.Event:Connect(function()", "print(\"Hi\")", "end)"],
      wordBankExplanation: "Those tokens form a complete one-line event connection with a callback body.",
      predictPrompt: "What does this print?",
      predictCode: "local bindable = Instance.new(\"BindableEvent\")\nbindable.Event:Connect(function(message)\n    print(message)\nend)\nbindable:Fire(\"Coins\")",
      predictAnswer: "Coins",
      predictExplanation: "The event fires with the string `Coins`, and the callback prints the received parameter.",
    },
    {
      mcOutputPrompt: "What does this print?",
      mcOutputCode: "local bindable = Instance.new(\"BindableEvent\")\nlocal connection = bindable.Event:Connect(function()\nend)\nprint(typeof(connection))",
      mcOutputOptions: ["RBXScriptConnection", "RBXScriptSignal", "table", "nil"],
      mcOutputCorrectIndex: 0,
      mcOutputExplanation: "`Connect()` returns a connection object, so `typeof` prints `RBXScriptConnection`.",
      fillTypePrompt: "Type the method name so the event is triggered after it is connected.",
      fillTypeCode: "local bindable = Instance.new(\"BindableEvent\")\nbindable.Event:Connect(function()\n    print(\"Ready\")\nend)\nbindable:___()",
      fillTypeAnswer: "Fire",
      fillTypeExplanation: "BindableEvents are triggered with `Fire()`.",
      fillSelectPrompt: "Fill the blanks so the script stores the connection object and prints its type.",
      fillSelectCode: "local bindable = Instance.new(\"BindableEvent\")\nlocal connection = bindable.Event:___(function()\nend)\nprint(typeof(___))",
      fillSelectTokens: ["Connect", "connection", "Fire", "Event"],
      fillSelectAnswer: ["Connect", "connection"],
      fillSelectExplanation: "`Connect` returns a connection object, and the local variable `connection` is what gets inspected.",
      wordBankPrompt: "Build the line that stores the connection object from `Connect()`.",
      wordBankTokens: ["local", "connection", "=", "bindable.Event:Connect(function() end)", "workspace", "bindable:Fire()"],
      wordBankAnswer: ["local", "connection", "=", "bindable.Event:Connect(function() end)"],
      wordBankExplanation: "That line captures the `RBXScriptConnection` returned by `Connect()`.",
      predictPrompt: "What does this print?",
      predictCode: "local bindable = Instance.new(\"BindableEvent\")\nprint(typeof(bindable.Event))",
      predictAnswer: "RBXScriptSignal",
      predictExplanation: "The `Event` property on a BindableEvent is a signal object.",
    },
    {
      mcOutputPrompt: "What does this print if the event is connected but never fired?",
      mcOutputCode: "local bindable = Instance.new(\"BindableEvent\")\nlocal called = false\nbindable.Event:Connect(function()\n    called = true\nend)\nprint(called)",
      mcOutputOptions: ["false", "true", "nil", "BindableEvent"],
      mcOutputCorrectIndex: 0,
      mcOutputExplanation: "The callback is connected, but it never runs because the event was not fired.",
      fillTypePrompt: "Type the callback parameter name so the fired value can be printed.",
      fillTypeCode: "local bindable = Instance.new(\"BindableEvent\")\nbindable.Event:Connect(function(___)\n    print(message)\nend)",
      fillTypeAnswer: "message",
      fillTypeExplanation: "The callback parameter can be named `message`, and then the callback can print that variable.",
      fillSelectPrompt: "Fill the blanks so the same parameter name is declared and printed.",
      fillSelectCode: "local bindable = Instance.new(\"BindableEvent\")\nbindable.Event:Connect(function(___)\n    print(___)\nend)",
      fillSelectTokens: ["message", "message", "workspace", "Event"],
      fillSelectAnswer: ["message", "message"],
      fillSelectExplanation: "The callback declares `message` and then prints the same variable.",
      wordBankPrompt: "Build the line that prints whether the callback has run yet.",
      wordBankTokens: ["print", "(", "called", ")", "bindable", "Connect"],
      wordBankAnswer: ["print", "(", "called", ")"],
      wordBankExplanation: "Printing `called` shows whether the event callback has executed yet.",
      predictPrompt: "What does this print?",
      predictCode: "local bindable = Instance.new(\"BindableEvent\")\nlocal called = false\nbindable.Event:Connect(function()\n    called = true\nend)\nprint(called)",
      predictAnswer: "false",
      predictExplanation: "Nothing fires the event, so the callback never updates the flag.",
    },
  ],
  arrange: [
    {
      prompt: "Arrange the code so a BindableEvent is created, connected, and fired.",
      lines: [
        "local bindable = Instance.new(\"BindableEvent\")",
        "bindable.Event:Connect(function()\n    print(\"Ping\")\nend)",
        "bindable:Fire()",
      ],
      correctOrder: [0, 1, 2],
      explanation: "Create the event first, connect the callback second, and fire it last.",
    },
    {
      prompt: "Arrange the code so the callback receives a message and the event fires with `Coins`.",
      lines: [
        "local bindable = Instance.new(\"BindableEvent\")",
        "bindable.Event:Connect(function(message)\n    print(message)\nend)",
        "bindable:Fire(\"Coins\")",
      ],
      correctOrder: [0, 1, 2],
      explanation: "The event must exist and be connected before firing the message value.",
    },
    {
      prompt: "Arrange the code so the connection object is stored and its type is printed.",
      lines: [
        "local bindable = Instance.new(\"BindableEvent\")",
        "local connection = bindable.Event:Connect(function() end)",
        "print(typeof(connection))",
      ],
      correctOrder: [0, 1, 2],
      explanation: "Connect returns the connection object, which you can then inspect.",
    },
  ],
  bugs: [
    {
      prompt: "Which version has the bug if the goal is to connect to the event?",
      versionA: "bindable.Event:Connect(function()\n    print(\"Ping\")\nend)",
      versionB: "bindable.Event.Connect(function()\n    print(\"Ping\")\nend)",
      buggyVersion: "B",
      explanation: "`Connect` is a method call on the signal, so the normal Roblox Lua form uses a colon.",
    },
    {
      prompt: "Which version has the bug if the goal is to react when the event fires?",
      versionA: "bindable.Event:Connect(function(message)\n    print(message)\nend)",
      versionB: "bindable.Event:Connect(\"message\")",
      buggyVersion: "B",
      explanation: "`Connect` expects a function callback, not a string.",
    },
    {
      prompt: "Which version has the bug if the goal is to trigger the BindableEvent?",
      versionA: "bindable:Fire()",
      versionB: "bindable.Event:Fire()",
      buggyVersion: "B",
      explanation: "You fire the BindableEvent object itself with `bindable:Fire()`. The signal property is what you connect to.",
    },
  ],
};

export const eventsConnectQuestions: Question[] = buildRobloxCodeConceptQuestions(eventsConnectSpec);
