import { Question } from "@/lib/data/questions/types";

export const explorerPanelQuestions: Question[] = [
  {
    id: "roblox-explorer-panel-mc-1",
    type: "mc_concept",
    concept: "explorer-panel",
    language: "lua",
    difficulty: 1,
    prompt: "What does the Explorer panel show in Roblox Studio?",
    options: [
      "A table of numeric properties for the selected object",
      "A list of Output messages from scripts",
      "The parent-child hierarchy of Instances in the place",
      "A catalog of free models from the Toolbox",
    ],
    correctIndex: 2,
    explanation:
      "Explorer shows the DataModel as a hierarchy of parent and child objects. That is where you see services, folders, parts, scripts, and GUI objects arranged in a tree. Properties, Output, and Toolbox are separate Studio panels with different jobs.",
  },
  {
    id: "roblox-explorer-panel-mc-2",
    type: "mc_concept",
    concept: "explorer-panel",
    language: "lua",
    difficulty: 1,
    prompt: "If a Part is indented under `Workspace` in Explorer, what does that mean?",
    options: [
      "It was created only by a plugin and will not run in-game",
      "It is a sibling of `Workspace`",
      "It exists only in the viewport and not in the DataModel",
      "It is a child of `Workspace`",
    ],
    correctIndex: 3,
    explanation:
      "Indentation in Explorer represents parent-child relationships. If a Part is shown under `Workspace`, then its `Parent` is `Workspace`. That same relationship is what your scripts read and change through the `Parent` property.",
  },
  {
    id: "roblox-explorer-panel-tf-1",
    type: "true_false",
    concept: "explorer-panel",
    language: "lua",
    difficulty: 1,
    prompt: "In Roblox Lua, the object directly above a Script in Explorer is usually what `script.Parent` refers to.",
    code: "local parentObject = script.Parent\nprint(parentObject.Name)",
    options: ["True", "False"],
    correctIndex: 0,
    correctAnswer: "True",
    explanation:
      "Explorer shows the same hierarchy that Roblox Lua uses for `Parent` relationships. If a Script sits under `ServerScriptService` or a Folder in Explorer, `script.Parent` points to that containing object. This is one of the most important links between the UI tree and scripting.",
  },
  {
    id: "roblox-explorer-panel-ft-1",
    type: "fill_type",
    concept: "explorer-panel",
    language: "lua",
    difficulty: 1,
    prompt: "Type the exact child name from Explorer so this code looks for a Part named `Floor` under `Workspace`.",
    code: "local floor = workspace:FindFirstChild(\"___\")",
    correctAnswer: "Floor",
    explanation:
      "Names in Explorer are the same strings your scripts use when calling methods like `FindFirstChild()`. If the Part is named `Floor` in the tree, the script has to search for `\"Floor\"` exactly. A different capitalization or spelling would search for a different object.",
  },
  {
    id: "roblox-explorer-panel-ft-2",
    type: "fill_type",
    concept: "explorer-panel",
    language: "lua",
    difficulty: 1,
    prompt: "Type the method name that searches for a direct child by its Explorer name.",
    code: "local crate = workspace:___(\"Crate\")",
    correctAnswer: "FindFirstChild",
    explanation:
      "`FindFirstChild()` is the standard method for looking up a child Instance by name. This matches how objects are listed in Explorer, where each child has a `Name`. It is different from `WaitForChild()`, which can yield while waiting for an object to appear.",
  },
  {
    id: "roblox-explorer-panel-mco-1",
    type: "mc_output",
    concept: "explorer-panel",
    language: "lua",
    difficulty: 1,
    prompt: "What does this code print?",
    code: "local folder = Instance.new(\"Folder\")\nfolder.Name = \"Items\"\nfolder.Parent = workspace\nlocal part = Instance.new(\"Part\")\npart.Name = \"Floor\"\npart.Parent = folder\nprint(part.Parent.Name)",
    options: ["Floor", "Workspace", "Items", "nil"],
    correctIndex: 2,
    explanation:
      "The Part is parented to the Folder named `Items`, so `part.Parent` is that Folder. Printing `part.Parent.Name` therefore prints `Items`. Explorer would show the Part nested under the Folder for the same reason.",
  },
  {
    id: "roblox-explorer-panel-mc-3",
    type: "mc_concept",
    concept: "explorer-panel",
    language: "lua",
    difficulty: 2,
    prompt: "Which method returns only the direct children listed one level under an Instance in Explorer?",
    options: ["GetDescendants()", "GetChildren()", "FindFirstChild()", "IsA()"],
    correctIndex: 1,
    explanation:
      "`GetChildren()` returns only the objects directly under that Instance. `GetDescendants()` goes deeper through the whole nested tree, while `FindFirstChild()` searches by name. `IsA()` checks type and does not return child lists at all.",
  },
  {
    id: "roblox-explorer-panel-fs-1",
    type: "fill_select",
    concept: "explorer-panel",
    language: "lua",
    difficulty: 2,
    prompt: "Fill the blanks so the Folder becomes a child of `Workspace`, then check that relationship in code.",
    code: "local folder = Instance.new(\"Folder\")\nfolder.Parent = ___\nprint(folder.___ == workspace)",
    tokens: ["workspace", "Parent", "Name", "script"],
    correctTokens: ["workspace", "Parent"],
    correctBlanks: ["workspace", "Parent"],
    explanation:
      "The first blank is `workspace` because that is the parent you want to assign. The second blank is `Parent`, because that property stores the same nesting relationship you can see in Explorer. `Name` would compare the Folder's text name instead of its container.",
  },
  {
    id: "roblox-explorer-panel-sb-1",
    type: "spot_bug",
    concept: "explorer-panel",
    language: "lua",
    difficulty: 2,
    prompt: "Which version has the bug if the goal is to find a child named `Floor` under `Workspace`?",
    code: "### Version A\nlocal floor = workspace:FindFirstChild(\"Floor\")\n### Version B\nlocal floor = workspace:FindChild(\"Floor\")",
    options: ["Version A", "Version B"],
    correctIndex: 1,
    explanation:
      "Version B is wrong because `FindChild` is not the method Roblox provides here. The correct method is `FindFirstChild()`. This is a common beginner mistake when translating what they see in Explorer into code.",
  },
  {
    id: "roblox-explorer-panel-tf-2",
    type: "true_false",
    concept: "explorer-panel",
    language: "lua",
    difficulty: 2,
    prompt: "Renaming an Instance in Explorer changes only the label you see in Studio, not the actual `Name` property used by scripts.",
    options: ["True", "False"],
    correctIndex: 1,
    correctAnswer: "False",
    explanation:
      "Explorer edits the real `Name` property on the Instance. That means scripts using `FindFirstChild()` or comparing `object.Name` will see the updated value. Explorer is not showing a fake label separate from the object.",
  },
  {
    id: "roblox-explorer-panel-pt-1",
    type: "predict_type",
    concept: "explorer-panel",
    language: "lua",
    difficulty: 2,
    prompt: "What does this code print?",
    code: "local folder = Instance.new(\"Folder\")\nlocal part = Instance.new(\"Part\")\npart.Parent = folder\nprint(#folder:GetChildren())",
    correctAnswer: "1",
    explanation:
      "The Folder has exactly one direct child: the Part. `GetChildren()` returns a table of direct children only, and the `#` operator reads that table length. So the printed result is `1`.",
  },
  {
    id: "roblox-explorer-panel-arr-1",
    type: "arrange",
    concept: "explorer-panel",
    language: "lua",
    difficulty: 2,
    prompt: "Arrange the code so a Folder named `Checkpoints` is created and a Part is placed inside it.",
    lines: [
      "local folder = Instance.new(\"Folder\")",
      "folder.Name = \"Checkpoints\"",
      "local part = Instance.new(\"Part\")",
      "part.Parent = folder",
    ],
    correctOrder: [0, 1, 2, 3],
    explanation:
      "The Folder has to exist before the Part can be parented into it. Renaming the Folder also has to happen after the Folder is created. In Explorer, the final result would be a Folder named `Checkpoints` containing one Part.",
  },
  {
    id: "roblox-explorer-panel-mc-4",
    type: "mc_concept",
    concept: "explorer-panel",
    language: "lua",
    difficulty: 2,
    prompt: "Which method searches direct children by name and returns `nil` if the named child is not there?",
    options: ["FindFirstChild()", "GetChildren()", "GetDescendants()", "WaitForChild()"],
    correctIndex: 0,
    explanation:
      "`FindFirstChild()` looks for a named child and returns the Instance or `nil`. `WaitForChild()` is different because it can yield until the child exists. `GetChildren()` and `GetDescendants()` return tables rather than a single named object.",
  },
  {
    id: "roblox-explorer-panel-mco-2",
    type: "mc_output",
    concept: "explorer-panel",
    language: "lua",
    difficulty: 2,
    prompt: "What does this code print?",
    code: "local folder = Instance.new(\"Folder\")\nlocal model = Instance.new(\"Model\")\nmodel.Parent = folder\nlocal part = Instance.new(\"Part\")\npart.Parent = model\nprint(#folder:GetDescendants())",
    options: ["1", "0", "3", "2"],
    correctIndex: 3,
    explanation:
      "`folder:GetDescendants()` includes every nested object under the Folder, not just direct children. The Model is one descendant, and the Part inside the Model is another, so the total is `2`. This is why `GetDescendants()` is broader than `GetChildren()`.",
  },
  {
    id: "roblox-explorer-panel-mc-5",
    type: "mc_concept",
    concept: "explorer-panel",
    language: "lua",
    difficulty: 2,
    prompt: "Can Explorer list an object even if the camera is not currently looking at it in the viewport?",
    options: [
      "No, Explorer only shows objects currently on-screen",
      "Only while the game is running in Play mode",
      "Yes, because Explorer shows the hierarchy, not the camera view",
      "Only for Scripts and LocalScripts",
    ],
    correctIndex: 2,
    explanation:
      "Explorer is based on the DataModel hierarchy, not on what the camera can currently see. An object can be off-screen, hidden inside a Folder, or outside the current camera angle and still appear in Explorer. That is one reason Explorer is so useful when selecting hard-to-click objects.",
  },
];
