import type { Question } from "@/lib/data/questions/types";
import { buildRobloxCodeConceptQuestions, type RobloxCodeConceptSpec } from "@/lib/robloxCourse/builders";

const playersServiceSpec: RobloxCodeConceptSpec = {
  concept: "players-service",
  title: "Players",
  nodeType: "practice",
  definitions: [
    {
      prompt: "What does the Roblox `Players` service manage?",
      options: [
        "The player objects connected to the game",
        "Only the 3D parts currently in Workspace",
        "The Studio Toolbox search results",
        "Only terrain materials and water brushes",
      ],
      correctIndex: 0,
      explanation: "The `Players` service tracks the game's player objects and player-related events like `PlayerAdded`.",
    },
    {
      prompt: "Which line correctly gets the `Players` service in Roblox Lua?",
      options: [
        "local players = game:GetService(\"Players\")",
        "local players = Players.new()",
        "local players = workspace.Players",
        "local players = game:GetPlayersService()",
      ],
      correctIndex: 0,
      explanation: "Roblox services are normally accessed with `game:GetService(\"ServiceName\")`.",
    },
    {
      prompt: "Which method on the `Players` service returns the current player list?",
      options: [
        "GetPlayers()",
        "ListPlayers()",
        "AllPlayers()",
        "FetchPlayers()",
      ],
      correctIndex: 0,
      explanation: "`Players:GetPlayers()` returns a Lua array-style table of the current player objects.",
    },
    {
      prompt: "Why would a Roblox script use the `Players` service?",
      options: [
        "To react to joined players and inspect current player objects",
        "To sculpt mountains and water in Studio",
        "To create tweens for part animation",
        "To browse free models from the Toolbox",
      ],
      correctIndex: 0,
      explanation: "`Players` is for player-related runtime logic such as joins, lists, and player containers.",
    },
  ],
  truths: [
    {
      prompt: "The expression `game:GetService(\"Players\")` returns the same service object as `game.Players`.",
      correct: true,
      explanation: "Both expressions reference the Players service. `GetService` is the standard explicit lookup pattern.",
      code: "local players = game:GetService(\"Players\")\nprint(players == game.Players)",
    },
    {
      prompt: "`Players:GetPlayers()` returns a table of the current player objects.",
      correct: true,
      explanation: "Roblox returns the current player list as a Lua table, which means `typeof` reports `table`.",
      code: "local players = game:GetService(\"Players\")\nprint(typeof(players:GetPlayers()))",
    },
    {
      prompt: "`PlayerAdded` belongs to the `Players` service and can be connected with `:Connect()`.",
      correct: true,
      explanation: "The `Players` service exposes `PlayerAdded` so scripts can react when a new player joins.",
    },
    {
      prompt: "The `Players` service is a Studio panel you reopen from the View tab.",
      correct: false,
      explanation: "`Players` is a runtime service in the DataModel. Studio panels like Explorer and Properties are separate UI tools.",
    },
  ],
  examples: [
    {
      mcOutputPrompt: "What does this print?",
      mcOutputCode: "local players = game:GetService(\"Players\")\nprint(players.Name)",
      mcOutputOptions: ["Players", "Player", "Workspace", "nil"],
      mcOutputCorrectIndex: 0,
      mcOutputExplanation: "The service object's `Name` property is `Players`.",
      fillTypePrompt: "Type the service name so the script gets the Roblox player service.",
      fillTypeCode: "local players = game:GetService(\"___\")",
      fillTypeAnswer: "Players",
      fillTypeExplanation: "The service name string must match the Roblox service name exactly.",
      fillTypeHint: "This service manages connected player objects.",
      fillSelectPrompt: "Fill the blanks so the script gets the service and prints its class name.",
      fillSelectCode: "local players = game:GetService(\"___\")\nprint(players.___)",
      fillSelectTokens: ["Players", "ClassName", "Parent", "Workspace"],
      fillSelectAnswer: ["Players", "ClassName"],
      fillSelectExplanation: "The first blank is the service name, and `ClassName` prints the Roblox class.",
      wordBankPrompt: "Build the line that stores the Players service in a local variable.",
      wordBankTokens: ["local", "players", "=", "game:GetService(\"Players\")", "workspace", "print(players)"],
      wordBankAnswer: ["local", "players", "=", "game:GetService(\"Players\")"],
      wordBankExplanation: "That is the standard pattern for storing a service reference.",
      predictPrompt: "What does this print?",
      predictCode: "local playerList = game:GetService(\"Players\"):GetPlayers()\nprint(typeof(playerList))",
      predictAnswer: "table",
      predictExplanation: "`GetPlayers()` returns a Lua table of player objects, so `typeof` prints `table`.",
    },
    {
      mcOutputPrompt: "What does this print?",
      mcOutputCode: "local players = game:GetService(\"Players\")\nprint(players == game.Players)",
      mcOutputOptions: ["true", "false", "Players", "Instance"],
      mcOutputCorrectIndex: 0,
      mcOutputExplanation: "Both expressions point to the same Players service object.",
      fillTypePrompt: "Type the method name that returns the current player list.",
      fillTypeCode: "local playerList = game:GetService(\"Players\"):___()",
      fillTypeAnswer: "GetPlayers",
      fillTypeExplanation: "`GetPlayers()` is the Players service method that returns the current player objects.",
      fillSelectPrompt: "Fill the blanks so the script gets the player list and prints its type.",
      fillSelectCode: "local list = game:GetService(\"Players\"):___()\nprint(typeof(___))",
      fillSelectTokens: ["GetPlayers", "list", "PlayerAdded", "workspace"],
      fillSelectAnswer: ["GetPlayers", "list"],
      fillSelectExplanation: "The player list comes from `GetPlayers()`, and the local variable `list` is what gets printed.",
      wordBankPrompt: "Build the expression that checks whether the two Players references match.",
      wordBankTokens: ["game:GetService(\"Players\")", "==", "game.Players", "=", "workspace", "script"],
      wordBankAnswer: ["game:GetService(\"Players\")", "==", "game.Players"],
      wordBankExplanation: "The expression is true because both sides refer to the same service.",
      predictPrompt: "What does this print?",
      predictCode: "local players = game:GetService(\"Players\")\nprint(players.ClassName)",
      predictAnswer: "Players",
      predictExplanation: "The service object's class name is `Players`.",
    },
    {
      mcOutputPrompt: "What does this print?",
      mcOutputCode: "local players = game:GetService(\"Players\")\nprint(typeof(players.PlayerAdded))",
      mcOutputOptions: ["RBXScriptSignal", "Player", "table", "string"],
      mcOutputCorrectIndex: 0,
      mcOutputExplanation: "`PlayerAdded` is an event signal, so `typeof` reports `RBXScriptSignal`.",
      fillTypePrompt: "Type the event name so the script refers to the join signal on the Players service.",
      fillTypeCode: "local players = game:GetService(\"Players\")\nprint(typeof(players.___))",
      fillTypeAnswer: "PlayerAdded",
      fillTypeExplanation: "`PlayerAdded` is the service event fired when a new player joins.",
      fillSelectPrompt: "Fill the blanks so the code stores the Players service and checks the join signal type.",
      fillSelectCode: "local players = game:GetService(\"Players\")\nlocal signal = players.___\nprint(typeof(___))",
      fillSelectTokens: ["PlayerAdded", "signal", "GetPlayers", "workspace"],
      fillSelectAnswer: ["PlayerAdded", "signal"],
      fillSelectExplanation: "The event is `PlayerAdded`, and `signal` is the local variable that stores it.",
      wordBankPrompt: "Build the line that stores the current player list in a variable.",
      wordBankTokens: ["local", "playerList", "=", "players:GetPlayers()", "workspace", "players.Name"],
      wordBankAnswer: ["local", "playerList", "=", "players:GetPlayers()"],
      wordBankExplanation: "That line captures the current list of player objects from the service.",
      predictPrompt: "What does this print?",
      predictCode: "local players = game:GetService(\"Players\")\nlocal playerList = players:GetPlayers()\nprint(#playerList >= 0)",
      predictAnswer: "true",
      predictExplanation: "The length of a Lua table of players is always zero or greater, so the comparison prints `true`.",
    },
    {
      mcOutputPrompt: "What does this print?",
      mcOutputCode: "local players = game:GetService(\"Players\")\nprint(players.MaxPlayers > 0)",
      mcOutputOptions: ["true", "false", "Players", "nil"],
      mcOutputCorrectIndex: 0,
      mcOutputExplanation: "Roblox places have a positive maximum player count, so this comparison prints `true`.",
      fillTypePrompt: "Type the property name so the script reads the maximum player count.",
      fillTypeCode: "local players = game:GetService(\"Players\")\nprint(players.___)",
      fillTypeAnswer: "MaxPlayers",
      fillTypeExplanation: "`MaxPlayers` is the Players service property that stores the allowed player cap.",
      fillSelectPrompt: "Fill the blanks so the script reads the maximum player count and checks whether it is positive.",
      fillSelectCode: "local players = game:GetService(\"Players\")\nprint(players.___ > ___)",
      fillSelectTokens: ["MaxPlayers", "0", "Name", "\"0\""],
      fillSelectAnswer: ["MaxPlayers", "0"],
      fillSelectExplanation: "`MaxPlayers` gives the numeric cap, and the comparison checks against zero.",
      wordBankPrompt: "Build the line that prints the Players service name.",
      wordBankTokens: ["print", "(", "players.Name", ")", "players.MaxPlayers", "workspace"],
      wordBankAnswer: ["print", "(", "players.Name", ")"],
      wordBankExplanation: "Printing `players.Name` shows the service's name string.",
      predictPrompt: "What does this print?",
      predictCode: "local players = game:GetService(\"Players\")\nprint(players.Name == \"Players\")",
      predictAnswer: "true",
      predictExplanation: "The Players service name is exactly `Players`, so the equality check is true.",
    },
  ],
  arrange: [
    {
      prompt: "Arrange the code so the Players service is fetched and its name is printed.",
      lines: [
        "local players = game:GetService(\"Players\")",
        "local serviceName = players.Name",
        "print(serviceName)",
      ],
      correctOrder: [0, 1, 2],
      explanation: "Fetch the service first, then read the property, then print it.",
    },
    {
      prompt: "Arrange the code so the current player list is stored and its type is printed.",
      lines: [
        "local players = game:GetService(\"Players\")",
        "local playerList = players:GetPlayers()",
        "print(typeof(playerList))",
      ],
      correctOrder: [0, 1, 2],
      explanation: "The service must be stored before calling `GetPlayers()` on it.",
    },
    {
      prompt: "Arrange the code so the script checks whether the service reference matches `game.Players`.",
      lines: [
        "local players = game:GetService(\"Players\")",
        "local sameService = players == game.Players",
        "print(sameService)",
      ],
      correctOrder: [0, 1, 2],
      explanation: "Fetch the service, compare the references, then print the boolean result.",
    },
  ],
  bugs: [
    {
      prompt: "Which version has the bug if the goal is to get the Players service?",
      versionA: "local players = game:GetService(\"Players\")",
      versionB: "local players = game:GetService(\"Player\")",
      buggyVersion: "B",
      explanation: "The service name must be `Players`, not `Player`.",
    },
    {
      prompt: "Which version has the bug if the goal is to get the current player list?",
      versionA: "local playerList = players:GetPlayers()",
      versionB: "local playerList = players.GetPlayers()",
      buggyVersion: "B",
      explanation: "`GetPlayers` is a method call, so the usual Roblox Lua call uses a colon.",
    },
    {
      prompt: "Which version has the bug if the goal is to read the join event signal?",
      versionA: "print(typeof(players.PlayerAdded))",
      versionB: "print(typeof(players.PlayerJoin))",
      buggyVersion: "B",
      explanation: "The Players service event is named `PlayerAdded`, not `PlayerJoin`.",
    },
  ],
};

export const playersServiceQuestions: Question[] = buildRobloxCodeConceptQuestions(playersServiceSpec);
