import type { Question } from "@/lib/data/questions/types";
import type { LessonContent } from "@/lib/robloxCourse/types";
import { isQuestionContent } from "@/lib/robloxCourse/types";

export const propertiesPanelContent: LessonContent[] = [
  {
    id: "roblox-properties-panel-explain-1",
    type: "explain",
    concept: "properties-panel",
    language: "lua",
    title: "Tune the Start Pad",
    body:
      "Today you're taking a plain block and turning it into the real start pad for your obby. The Properties panel is where Studio lets you change exact values on the selected object, so this is where you make the pad wide enough to stand on and stable enough not to fall. We'll focus on `Size` and `Anchored` first because those two settings decide whether the pad is usable at all. By the end of this step, your players will have a safe place to begin the course.",
    docUrl: "https://create.roblox.com/docs/studio/properties",
    code: "local pad = Instance.new(\"Part\")\npad.Name = \"StartPad\"\npad.Size = Vector3.new(20, 1, 20)\npad.Anchored = true",
    position: "start",
    lessonIndex: 2,
  },
  {
    id: "roblox-properties-panel-mc-1",
    type: "mc_concept",
    concept: "properties-panel",
    language: "lua",
    difficulty: 2,
    prompt: "On your new start pad, which property should you change so the pad does not fall when play begins?",
    options: ["Size", "Anchored", "Material", "BrickColor"],
    correctIndex: 1,
    explanation:
      "`Anchored` decides whether the part stays fixed in place instead of responding to gravity and physics. A large pad with the wrong color is still useless if it drops away when the round starts. `Size`, `Material`, and `BrickColor` change how the pad looks or feels, but they do not keep it from falling.",
  },
  {
    id: "roblox-properties-panel-ft-1",
    type: "fill_type",
    concept: "properties-panel",
    language: "lua",
    difficulty: 2,
    prompt: "Type the property name that keeps the start pad fixed in place.",
    code: "local pad = Instance.new(\"Part\")\npad.___ = true",
    correctAnswer: "Anchored",
    explanation:
      "The property is `Anchored`, and setting it to `true` stops the part from moving under physics. This is the same setting you would click in the Properties panel after selecting the pad. Roblox uses the exact same property name in Studio and in code, which is why this is worth learning early.",
  },
  {
    id: "roblox-properties-panel-tf-1",
    type: "true_false",
    concept: "properties-panel",
    language: "lua",
    difficulty: 2,
    prompt: "If you make the start pad wider in the Properties panel, a script reading `pad.Size` will see that new size.",
    options: ["True", "False"],
    correctIndex: 0,
    correctAnswer: "True",
    explanation:
      "The Properties panel edits the real properties stored on the selected Instance. That means when you change `Size` in Studio, scripts later read the updated `Size` value from the same object. The panel is not a fake preview layer; it is editing the data the game actually uses.",
  },
  {
    id: "roblox-properties-panel-mco-1",
    type: "mc_output",
    concept: "properties-panel",
    language: "lua",
    difficulty: 2,
    prompt: "You widened the start pad with code instead of the Properties panel. What does this print?",
    code: "local pad = Instance.new(\"Part\")\npad.Size = Vector3.new(20, 1, 20)\nprint(pad.Size.Y)",
    options: ["20", "0", "1", "Vector3"],
    correctIndex: 2,
    explanation:
      "The part's size is being set to `Vector3.new(20, 1, 20)`, which means X is 20, Y is 1, and Z is 20. The code prints the Y component, so the result is `1`. This is useful because the Properties panel and code both describe the same size values from different angles.",
  },
  {
    id: "roblox-properties-panel-mc-2",
    type: "mc_concept",
    concept: "properties-panel",
    language: "lua",
    difficulty: 2,
    prompt: "Players keep stepping off the start pad because it is too narrow. Which property should you change in the Properties panel first?",
    options: ["Material", "Transparency", "BrickColor", "Size"],
    correctIndex: 3,
    explanation:
      "`Size` controls how large the part is, so it is the first property to change when the platform is too small. `Material`, `Transparency`, and `BrickColor` can improve readability, but they do not make the walkable surface larger. In a real obby build, pad size directly affects how forgiving the opening jump feels.",
  },
  {
    id: "roblox-properties-panel-explain-2",
    type: "explain",
    concept: "properties-panel",
    language: "lua",
    title: "Style the Gate",
    body:
      "Now you're building a blue glass gate that marks the edge of your lobby. Good Roblox levels communicate through visuals, so players should be able to tell what a part is for before they touch it. In this step you'll use `BrickColor`, `Material`, and `Transparency` to make the gate look like glass instead of a generic block. These appearance settings all live in the Properties panel and all have matching names in Roblox Lua.",
    docUrl: "https://create.roblox.com/docs/parts",
    code: "local gate = Instance.new(\"Part\")\ngate.BrickColor = BrickColor.new(\"Bright blue\")\ngate.Material = Enum.Material.Glass\ngate.Transparency = 0.35",
    position: "mid",
    lessonIndex: 2,
  },
  {
    id: "roblox-properties-panel-mc-3",
    type: "mc_concept",
    concept: "properties-panel",
    language: "lua",
    difficulty: 2,
    prompt: "To make your lobby gate look like tinted glass while still being visible, which group of properties matters most?",
    options: [
      "BrickColor, Material, and Transparency",
      "Name and Position",
      "Parent and ClassName",
      "Anchored and CanCollide",
    ],
    correctIndex: 0,
    explanation:
      "`BrickColor` controls the tint, `Material` controls the surface type, and `Transparency` controls how see-through the gate becomes. Those three settings work together to make a part look like glass. The other answers affect organization, identity, or physics, but not the visual style you are trying to communicate to the player.",
  },
  {
    id: "roblox-properties-panel-fs-1",
    type: "fill_select",
    concept: "properties-panel",
    language: "lua",
    difficulty: 3,
    prompt: "Fill the blanks to give the gate a glass material in code, matching the value you would set in Properties.",
    code: "local gate = Instance.new(\"Part\")\ngate.___ = ___",
    tokens: ["Material", "Enum.Material.Glass", "Transparency", "BrickColor.new(\"Bright blue\")"],
    correctTokens: ["Material", "Enum.Material.Glass"],
    correctBlanks: ["Material", "Enum.Material.Glass"],
    explanation:
      "The property name is `Material`, and the Roblox enum value for glass is `Enum.Material.Glass`. This mirrors what you choose from the material dropdown in the Properties panel. The distractors are real-looking values, but they belong to different properties.",
  },
  {
    id: "roblox-properties-panel-sb-1",
    type: "spot_bug",
    concept: "properties-panel",
    language: "lua",
    difficulty: 3,
    prompt: "Which version has the bug if the goal is to make the gate semi-transparent instead of fully visible?",
    code: "### Version A\ngate.Transparency = 0.35\n### Version B\ngate.Transparency = 35",
    options: ["Version A", "Version B"],
    correctIndex: 1,
    explanation:
      "Version B has the bug because Roblox transparency values are meant to be in the 0 to 1 range, not 0 to 100. A beginner might think in percentages and type `35`, but that is not how this property works. Version A uses a normal fractional value that matches the way you would adjust transparency in the Properties panel.",
  },
  {
    id: "roblox-properties-panel-pt-1",
    type: "predict_type",
    concept: "properties-panel",
    language: "lua",
    difficulty: 3,
    prompt: "You color the gate in code instead of through Properties. What does this print?",
    code: "local gate = Instance.new(\"Part\")\ngate.BrickColor = BrickColor.new(\"Bright blue\")\nprint(gate.BrickColor.Name)",
    correctAnswer: "Bright blue",
    explanation:
      "The code sets the part's `BrickColor` to the built-in color named `Bright blue`. Printing `gate.BrickColor.Name` returns that exact BrickColor name. This is the same value you are effectively choosing when you pick a color in Studio.",
  },
  {
    id: "roblox-properties-panel-wb-1",
    type: "word_bank",
    concept: "properties-panel",
    language: "lua",
    difficulty: 3,
    prompt: "Build the line that makes the gate partly see-through.",
    tokens: ["gate.Transparency", "=", "0.35", "gate.Material", "Enum.Material.Glass", "workspace"],
    correctTokens: ["gate.Transparency", "=", "0.35"],
    correctAnswer: "gate.Transparency = 0.35",
    explanation:
      "The `Transparency` property controls how visible the part is, and `0.35` makes it partly transparent without hiding it completely. This is a common sweet spot for a glass-like gate because players can still see it clearly. The other tokens belong to different properties or unrelated objects.",
  },
  {
    id: "roblox-properties-panel-explain-3",
    type: "explain",
    concept: "properties-panel",
    language: "lua",
    title: "Let Players Pass",
    body:
      "A glass gate can look correct and still play badly if it blocks the player at the wrong time. In this step you're turning the gate into a visible marker that players can walk through by changing `CanCollide`. This is one of the best examples of why properties matter: the gate's appearance and its gameplay behavior are controlled by different values. Once you understand that split, you stop guessing and start building intentionally.",
    docUrl: "https://create.roblox.com/docs/parts",
    code: "local gate = Instance.new(\"Part\")\ngate.Anchored = true\ngate.CanCollide = false\ngate.Transparency = 0.35",
    position: "mid",
    lessonIndex: 2,
  },
  {
    id: "roblox-properties-panel-mco-2",
    type: "mc_output",
    concept: "properties-panel",
    language: "lua",
    difficulty: 3,
    prompt: "You disable collisions for the gate. What does this code print?",
    code: "local gate = Instance.new(\"Part\")\ngate.CanCollide = false\nprint(gate.CanCollide)",
    options: ["true", "nil", "false", "0"],
    correctIndex: 2,
    explanation:
      "The script sets `gate.CanCollide` to `false`, so printing that property returns `false`. This is the code version of unchecking the collision setting in the Properties panel. `nil` and `0` are common beginner guesses, but Roblox boolean properties print as `true` or `false`.",
  },
  {
    id: "roblox-properties-panel-ft-2",
    type: "fill_type",
    concept: "properties-panel",
    language: "lua",
    difficulty: 3,
    prompt: "Type the property name that lets players walk through the gate when you set it to `false`.",
    code: "local gate = Instance.new(\"Part\")\ngate.___ = false",
    correctAnswer: "CanCollide",
    explanation:
      "`CanCollide` controls whether physical characters and objects are blocked by the part. Setting it to `false` turns the gate into a visible marker that does not stop movement. This is different from `Transparency`, which changes the look, not the collision behavior.",
  },
  {
    id: "roblox-properties-panel-tf-2",
    type: "true_false",
    concept: "properties-panel",
    language: "lua",
    difficulty: 3,
    prompt: "If you set `CanCollide` to `false`, Roblox also automatically sets `Transparency` to `1`.",
    options: ["True", "False"],
    correctIndex: 1,
    correctAnswer: "False",
    explanation:
      "`CanCollide` and `Transparency` are separate properties that solve different problems. Turning collisions off does not make the part invisible, and making a part invisible does not automatically change whether it blocks the player. A real Roblox developer needs to control both on purpose.",
  },
  {
    id: "roblox-properties-panel-arr-1",
    type: "arrange",
    concept: "properties-panel",
    language: "lua",
    difficulty: 3,
    prompt: "Arrange the code so the lobby gate stays in place, looks like glass, and lets players walk through it.",
    lines: [
      "local gate = workspace.GlassGate",
      "gate.Anchored = true",
      "gate.Transparency = 0.35",
      "gate.CanCollide = false",
    ],
    correctOrder: [0, 1, 2, 3],
    explanation:
      "The script first gets the existing gate part, then sets the properties that define how it behaves and looks. Anchoring comes before the appearance and collision tweaks simply because you need the object reference first, then you apply the changes. In practice, all three property assignments work together to create the finished gate.",
  },
  {
    id: "roblox-properties-panel-mc-4",
    type: "mc_concept",
    concept: "properties-panel",
    language: "lua",
    difficulty: 3,
    prompt: "You want the gate to become invisible but still block the player during a later challenge. Which single property should you change first for that visual effect?",
    options: ["CanCollide", "Anchored", "Material", "Transparency"],
    correctIndex: 3,
    explanation:
      "If the goal is specifically to make the gate invisible, `Transparency` is the property that controls that effect. You would likely leave `CanCollide` turned on so the invisible gate still blocks movement. `Anchored` and `Material` matter for other reasons, but they do not hide the part.",
  },
];

export const propertiesPanelQuestions: Question[] = propertiesPanelContent.filter(isQuestionContent);
