import type { Question } from "@/lib/data/questions/types";
import { buildRobloxCodeConceptQuestions, type RobloxCodeConceptSpec } from "@/lib/robloxCourse/builders";

const remoteEventSpec: RobloxCodeConceptSpec = {
  concept: "remote-event",
  title: "RemoteEvent",
  nodeType: "teaching",
  definitions: [
    {
      prompt: "What is a `RemoteEvent` mainly used for in Roblox?",
      options: [
        "One-way communication between the client and the server",
        "Saving permanent player data automatically",
        "Replacing Parts in Workspace with GUI objects",
        "Opening Studio panels from a script",
      ],
      correctIndex: 0,
      explanation: "`RemoteEvent` sends data one way between client and server. It is a core networking tool in Roblox games.",
    },
    {
      prompt: "Where is a `RemoteEvent` commonly stored so both sides can access it?",
      options: [
        "ReplicatedStorage",
        "The Toolbox panel",
        "Only in Terrain Editor",
        "Inside the View tab ribbon",
      ],
      correctIndex: 0,
      explanation: "Developers often store `RemoteEvent` objects in `ReplicatedStorage` so both server and client code can reference the same object.",
    },
    {
      prompt: "Which event is commonly connected on the server side of a `RemoteEvent`?",
      options: [
        "OnServerEvent",
        "Touched",
        "PlayerAdded",
        "OnInvoke",
      ],
      correctIndex: 0,
      explanation: "`OnServerEvent` is the server-side signal that runs when a client fires the remote with `FireServer()`.",
    },
    {
      prompt: "How is `RemoteEvent` different from `RemoteFunction`?",
      options: [
        "RemoteEvent is one-way and does not directly return a value",
        "RemoteEvent can only be used in Studio, not in a running game",
        "RemoteEvent is only for saving datastores",
        "RemoteEvent automatically creates GUI buttons",
      ],
      correctIndex: 0,
      explanation: "`RemoteEvent` is fire-and-forget communication. `RemoteFunction` is the request-response version.",
    },
  ],
  truths: [
    {
      prompt: "A `RemoteEvent` is a Roblox Instance class that can be created with `Instance.new(\"RemoteEvent\")`.",
      correct: true,
      explanation: "Like other Roblox objects, a `RemoteEvent` can be created by class name with `Instance.new()`.",
      code: "local remote = Instance.new(\"RemoteEvent\")\nprint(remote.ClassName)",
    },
    {
      prompt: "Server code can listen to a `RemoteEvent` with `remote.OnServerEvent:Connect(...)`.",
      correct: true,
      explanation: "`OnServerEvent` is the server-side event signal for incoming client messages.",
    },
    {
      prompt: "A `RemoteEvent` automatically returns a value to the caller the way a function call does.",
      correct: false,
      explanation: "`RemoteEvent` does not return a direct response. Use `RemoteFunction` when you need request-response behavior.",
    },
    {
      prompt: "`RemoteEvent` is a Studio panel that appears next to Explorer and Properties.",
      correct: false,
      explanation: "`RemoteEvent` is a runtime networking object, not a Studio panel.",
    },
  ],
  examples: [
    {
      mcOutputPrompt: "What does this print?",
      mcOutputCode: "local remote = Instance.new(\"RemoteEvent\")\nprint(remote.ClassName)",
      mcOutputOptions: ["RemoteEvent", "RemoteFunction", "BindableEvent", "Instance"],
      mcOutputCorrectIndex: 0,
      mcOutputExplanation: "The new object's class name is `RemoteEvent`.",
      fillTypePrompt: "Type the class name so the code creates a one-way networking object.",
      fillTypeCode: "local remote = Instance.new(\"___\")",
      fillTypeAnswer: "RemoteEvent",
      fillTypeExplanation: "`RemoteEvent` is the class name for the one-way client-server messaging object.",
      fillTypeHint: "Use the networking object that fires without returning a value.",
      fillSelectPrompt: "Fill the blanks so the script creates a RemoteEvent and prints its class name.",
      fillSelectCode: "local remote = Instance.new(\"___\")\nprint(remote.___)",
      fillSelectTokens: ["RemoteEvent", "ClassName", "Name", "Players"],
      fillSelectAnswer: ["RemoteEvent", "ClassName"],
      fillSelectExplanation: "The object class is `RemoteEvent`, and `ClassName` prints that Roblox type.",
      wordBankPrompt: "Build the line that stores a new RemoteEvent in a variable.",
      wordBankTokens: ["local", "remote", "=", "Instance.new(\"RemoteEvent\")", "workspace", "remote.Name"],
      wordBankAnswer: ["local", "remote", "=", "Instance.new(\"RemoteEvent\")"],
      wordBankExplanation: "That line creates a new RemoteEvent and stores it in `remote`.",
      predictPrompt: "What does this print?",
      predictCode: "local remote = Instance.new(\"RemoteEvent\")\nprint(typeof(remote.OnServerEvent))",
      predictAnswer: "RBXScriptSignal",
      predictExplanation: "`OnServerEvent` is an event signal, so `typeof` reports `RBXScriptSignal`.",
    },
    {
      mcOutputPrompt: "What does this print?",
      mcOutputCode: "local remote = Instance.new(\"RemoteEvent\")\nremote.Name = \"RoundStarted\"\nprint(remote.Name)",
      mcOutputOptions: ["RoundStarted", "RemoteEvent", "ReplicatedStorage", "true"],
      mcOutputCorrectIndex: 0,
      mcOutputExplanation: "The `Name` property was changed to `RoundStarted`, so that is what prints.",
      fillTypePrompt: "Type the server-side event name that listens for client messages.",
      fillTypeCode: "local remote = Instance.new(\"RemoteEvent\")\nprint(typeof(remote.___))",
      fillTypeAnswer: "OnServerEvent",
      fillTypeExplanation: "`OnServerEvent` is the signal server code listens to on a RemoteEvent.",
      fillSelectPrompt: "Fill the blanks so the remote is renamed and then printed.",
      fillSelectCode: "local remote = Instance.new(\"RemoteEvent\")\nremote.___ = \"RoundStarted\"\nprint(remote.___)",
      fillSelectTokens: ["Name", "Name", "ClassName", "Parent"],
      fillSelectAnswer: ["Name", "Name"],
      fillSelectExplanation: "The `Name` property is used both to rename the object and then print the new value.",
      wordBankPrompt: "Build the line that stores the server-side signal in a variable.",
      wordBankTokens: ["local", "signal", "=", "remote.OnServerEvent", "workspace", "remote.Name"],
      wordBankAnswer: ["local", "signal", "=", "remote.OnServerEvent"],
      wordBankExplanation: "That line captures the server event signal from the RemoteEvent.",
      predictPrompt: "What does this print?",
      predictCode: "local remote = Instance.new(\"RemoteEvent\")\nprint(typeof(remote.OnClientEvent))",
      predictAnswer: "RBXScriptSignal",
      predictExplanation: "`OnClientEvent` is also an event signal on the RemoteEvent.",
    },
    {
      mcOutputPrompt: "What does this print after the remote is parented?",
      mcOutputCode: "local remote = Instance.new(\"RemoteEvent\")\nlocal replicatedStorage = game:GetService(\"ReplicatedStorage\")\nremote.Parent = replicatedStorage\nprint(remote.Parent == replicatedStorage)",
      mcOutputOptions: ["true", "false", "RemoteEvent", "ReplicatedStorage"],
      mcOutputCorrectIndex: 0,
      mcOutputExplanation: "The remote's parent was set to `ReplicatedStorage`, so the comparison is true.",
      fillTypePrompt: "Type the common shared service name so the remote can be placed where client and server can both reference it.",
      fillTypeCode: "local remote = Instance.new(\"RemoteEvent\")\nremote.Parent = game:GetService(\"___\")",
      fillTypeAnswer: "ReplicatedStorage",
      fillTypeExplanation: "`ReplicatedStorage` is a common place to keep remotes that both sides use.",
      fillSelectPrompt: "Fill the blanks so the remote is parented to ReplicatedStorage and then checked.",
      fillSelectCode: "local remote = Instance.new(\"RemoteEvent\")\nlocal replicatedStorage = game:GetService(\"___\")\nremote.Parent = replicatedStorage\nprint(remote.Parent == ___)",
      fillSelectTokens: ["ReplicatedStorage", "replicatedStorage", "Players", "workspace"],
      fillSelectAnswer: ["ReplicatedStorage", "replicatedStorage"],
      fillSelectExplanation: "The service is `ReplicatedStorage`, and the comparison is made against the local variable of the same object.",
      wordBankPrompt: "Build the line that places the RemoteEvent into ReplicatedStorage.",
      wordBankTokens: ["remote.Parent", "=", "game:GetService(\"ReplicatedStorage\")", "workspace", "remote.Name", "\"RoundStarted\""],
      wordBankAnswer: ["remote.Parent", "=", "game:GetService(\"ReplicatedStorage\")"],
      wordBankExplanation: "That line stores the RemoteEvent in the shared replication container.",
      predictPrompt: "What does this print?",
      predictCode: "local remote = Instance.new(\"RemoteEvent\")\nremote.Parent = game:GetService(\"ReplicatedStorage\")\nprint(remote.Parent.Name)",
      predictAnswer: "ReplicatedStorage",
      predictExplanation: "The parent service is ReplicatedStorage, so its name prints as `ReplicatedStorage`.",
    },
    {
      mcOutputPrompt: "What does this print?",
      mcOutputCode: "local remote = Instance.new(\"RemoteEvent\")\nprint(remote.Name == \"RemoteEvent\")",
      mcOutputOptions: ["true", "false", "RemoteEvent", "nil"],
      mcOutputCorrectIndex: 0,
      mcOutputExplanation: "A new RemoteEvent starts with the default name `RemoteEvent`, so the equality check is true.",
      fillTypePrompt: "Type the method name used on the server to broadcast to all clients.",
      fillTypeCode: "remote:___(\"RoundStart\")",
      fillTypeAnswer: "FireAllClients",
      fillTypeExplanation: "`FireAllClients` is the RemoteEvent method that broadcasts a message from the server to all clients.",
      fillSelectPrompt: "Fill the blanks so the code subscribes to the server-side event signal.",
      fillSelectCode: "remote.___:Connect(function(player, message)\n    print(message)\nend)",
      fillSelectTokens: ["OnServerEvent", "OnClientEvent", "Touched", "PlayerAdded"],
      fillSelectAnswer: ["OnServerEvent"],
      fillSelectExplanation: "`OnServerEvent` is the signal the server listens to for incoming client messages.",
      wordBankPrompt: "Build the line that broadcasts `RoundStart` to all clients.",
      wordBankTokens: ["remote:FireAllClients(\"RoundStart\")", "remote.OnServerEvent", "=", "workspace", "remote.Name"],
      wordBankAnswer: ["remote:FireAllClients(\"RoundStart\")"],
      wordBankExplanation: "That line sends a one-way message from the server to all clients.",
      predictPrompt: "What does this print?",
      predictCode: "local remote = Instance.new(\"RemoteEvent\")\nprint(remote.ClassName == \"RemoteEvent\")",
      predictAnswer: "true",
      predictExplanation: "The object's class is `RemoteEvent`, so the equality check is true.",
    },
  ],
  arrange: [
    {
      prompt: "Arrange the code so a RemoteEvent is created, renamed, and parented to ReplicatedStorage.",
      lines: [
        "local remote = Instance.new(\"RemoteEvent\")",
        "remote.Name = \"RoundStarted\"",
        "remote.Parent = game:GetService(\"ReplicatedStorage\")",
      ],
      correctOrder: [0, 1, 2],
      explanation: "Create the remote first, rename it second, and parent it last.",
    },
    {
      prompt: "Arrange the code so server code gets the remote and listens for incoming messages.",
      lines: [
        "local remote = Instance.new(\"RemoteEvent\")",
        "remote.OnServerEvent:Connect(function(player, message)\n    print(message)\nend)",
        "print(typeof(remote.OnServerEvent))",
      ],
      correctOrder: [0, 1, 2],
      explanation: "The RemoteEvent must exist before its server-side signal can be connected or inspected.",
    },
    {
      prompt: "Arrange the code so a RemoteEvent is created, parented, and its parent name is printed.",
      lines: [
        "local remote = Instance.new(\"RemoteEvent\")",
        "remote.Parent = game:GetService(\"ReplicatedStorage\")",
        "print(remote.Parent.Name)",
      ],
      correctOrder: [0, 1, 2],
      explanation: "Create the object first, then parent it, then print the parent name.",
    },
  ],
  bugs: [
    {
      prompt: "Which version has the bug if the goal is to create a RemoteEvent?",
      versionA: "local remote = Instance.new(\"RemoteEvent\")",
      versionB: "local remote = Instance.new(\"Remote Event\")",
      buggyVersion: "B",
      explanation: "The class name must match exactly. `Remote Event` with a space is not the Roblox class name.",
    },
    {
      prompt: "Which version has the bug if the goal is to listen on the server for incoming client messages?",
      versionA: "remote.OnServerEvent:Connect(function(player, message)\n    print(message)\nend)",
      versionB: "remote.OnServer:Connect(function(player, message)\n    print(message)\nend)",
      buggyVersion: "B",
      explanation: "The server-side signal is named `OnServerEvent`, not `OnServer`.",
    },
    {
      prompt: "Which version has the bug if the goal is to broadcast to all clients?",
      versionA: "remote:FireAllClients(\"RoundStart\")",
      versionB: "remote.FireAllClients(\"RoundStart\")",
      buggyVersion: "B",
      explanation: "`FireAllClients` is a method call, so the normal Roblox Lua syntax uses a colon.",
    },
  ],
};

export const remoteEventQuestions: Question[] = buildRobloxCodeConceptQuestions(remoteEventSpec);
