import type { Question } from "@/lib/data/questions/types";
import { buildRobloxCodeConceptQuestions, type RobloxCodeConceptSpec } from "@/lib/robloxCourse/builders";

const screenGuiSpec: RobloxCodeConceptSpec = {
  concept: "screen-gui",
  title: "ScreenGui",
  nodeType: "teaching",
  definitions: [
    {
      prompt: "What is a `ScreenGui` used for in Roblox?",
      options: [
        "Displaying 2D interface elements on the player's screen",
        "Creating physical collisions in Workspace",
        "Saving player data permanently on Roblox servers",
        "Browsing free models in the Toolbox",
      ],
      correctIndex: 0,
      explanation: "`ScreenGui` is the top-level container for many on-screen UI objects such as `TextLabel`, `TextButton`, and `Frame`.",
    },
    {
      prompt: "Where is a `ScreenGui` commonly placed so players receive the interface?",
      options: [
        "StarterGui",
        "Terrain Editor",
        "ServerStorage only",
        "Output",
      ],
      correctIndex: 0,
      explanation: "A `ScreenGui` is often parented under `StarterGui`, which Roblox uses to give GUI objects to players.",
    },
    {
      prompt: "Which object is a common child of a `ScreenGui`?",
      options: [
        "TextLabel",
        "TweenService",
        "Players",
        "TerrainRegion",
      ],
      correctIndex: 0,
      explanation: "`TextLabel` is a standard GUI child object placed inside a `ScreenGui`.",
    },
    {
      prompt: "Why would a Roblox developer use `ScreenGui`?",
      options: [
        "To build HUDs, menus, score displays, and other player interface screens",
        "To create server-only player join events",
        "To sculpt terrain mountains with brushes",
        "To replace `Instance.new()` for object creation",
      ],
      correctIndex: 0,
      explanation: "`ScreenGui` is the entry point for player-facing screen interfaces such as menus and HUDs.",
    },
  ],
  truths: [
    {
      prompt: "A `ScreenGui` is a Roblox Instance that can be created with `Instance.new(\"ScreenGui\")`.",
      correct: true,
      explanation: "UI containers like `ScreenGui` are normal Roblox objects and can be created through `Instance.new()`.",
      code: "local gui = Instance.new(\"ScreenGui\")\nprint(gui.ClassName)",
    },
    {
      prompt: "`ScreenGui` is for on-screen interface, not for physical world collisions.",
      correct: true,
      explanation: "World collisions use physical objects like Parts. `ScreenGui` is for 2D player UI.",
    },
    {
      prompt: "A `TextLabel` can be parented inside a `ScreenGui`.",
      correct: true,
      explanation: "GUI objects like `TextLabel` are commonly nested under a `ScreenGui` container.",
    },
    {
      prompt: "`ScreenGui` is a service fetched with `game:GetService(\"ScreenGui\")`.",
      correct: false,
      explanation: "`ScreenGui` is an Instance class, not a service. A script creates it with `Instance.new()`.",
    },
  ],
  examples: [
    {
      mcOutputPrompt: "What does this print?",
      mcOutputCode: "local gui = Instance.new(\"ScreenGui\")\nprint(gui.ClassName)",
      mcOutputOptions: ["ScreenGui", "TextLabel", "StarterGui", "GuiObject"],
      mcOutputCorrectIndex: 0,
      mcOutputExplanation: "The created object's class is `ScreenGui`.",
      fillTypePrompt: "Type the class name so the code creates an on-screen GUI container.",
      fillTypeCode: "local gui = Instance.new(\"___\")",
      fillTypeAnswer: "ScreenGui",
      fillTypeExplanation: "`ScreenGui` is the correct class name for a top-level screen interface container.",
      fillTypeHint: "Use the GUI container that lives on the player's screen.",
      fillSelectPrompt: "Fill the blanks so the code creates a ScreenGui and prints its name.",
      fillSelectCode: "local gui = Instance.new(\"___\")\nprint(gui.___)",
      fillSelectTokens: ["ScreenGui", "Name", "Players", "Touched"],
      fillSelectAnswer: ["ScreenGui", "Name"],
      fillSelectExplanation: "The class is `ScreenGui`, and new Instances expose the `Name` property.",
      wordBankPrompt: "Build the line that stores a new ScreenGui in a variable.",
      wordBankTokens: ["local", "gui", "=", "Instance.new(\"ScreenGui\")", "workspace", "gui.Parent"],
      wordBankAnswer: ["local", "gui", "=", "Instance.new(\"ScreenGui\")"],
      wordBankExplanation: "That line creates the GUI container and stores it in `gui`.",
      predictPrompt: "What does this print?",
      predictCode: "local gui = Instance.new(\"ScreenGui\")\nprint(gui.Name == \"ScreenGui\")",
      predictAnswer: "true",
      predictExplanation: "A new ScreenGui starts with the default name `ScreenGui`.",
    },
    {
      mcOutputPrompt: "What does this print after the ScreenGui is parented?",
      mcOutputCode: "local gui = Instance.new(\"ScreenGui\")\nlocal starterGui = game:GetService(\"StarterGui\")\ngui.Parent = starterGui\nprint(gui.Parent == starterGui)",
      mcOutputOptions: ["true", "false", "StarterGui", "ScreenGui"],
      mcOutputCorrectIndex: 0,
      mcOutputExplanation: "The GUI's parent is explicitly set to `StarterGui`, so the comparison is true.",
      fillTypePrompt: "Type the service name so the ScreenGui is parented to the usual starter UI container.",
      fillTypeCode: "local gui = Instance.new(\"ScreenGui\")\ngui.Parent = game:GetService(\"___\")",
      fillTypeAnswer: "StarterGui",
      fillTypeExplanation: "`StarterGui` is a common container for player screen interfaces.",
      fillSelectPrompt: "Fill the blanks so the script gets StarterGui and parents the ScreenGui into it.",
      fillSelectCode: "local gui = Instance.new(\"ScreenGui\")\nlocal starterGui = game:GetService(\"___\")\ngui.Parent = ___",
      fillSelectTokens: ["StarterGui", "starterGui", "Players", "workspace"],
      fillSelectAnswer: ["StarterGui", "starterGui"],
      fillSelectExplanation: "The service is `StarterGui`, and the local variable `starterGui` is used for parenting.",
      wordBankPrompt: "Build the line that parents the ScreenGui to StarterGui.",
      wordBankTokens: ["gui.Parent", "=", "game:GetService(\"StarterGui\")", "workspace", "gui.Name", "\"MainHud\""],
      wordBankAnswer: ["gui.Parent", "=", "game:GetService(\"StarterGui\")"],
      wordBankExplanation: "That line places the ScreenGui under the starter UI container.",
      predictPrompt: "What does this print?",
      predictCode: "local gui = Instance.new(\"ScreenGui\")\ngui.Parent = game:GetService(\"StarterGui\")\nprint(gui.Parent.Name)",
      predictAnswer: "StarterGui",
      predictExplanation: "The parent service is StarterGui, so that service name is printed.",
    },
    {
      mcOutputPrompt: "What does this print?",
      mcOutputCode: "local gui = Instance.new(\"ScreenGui\")\nlocal label = Instance.new(\"TextLabel\")\nlabel.Parent = gui\nprint(label.Parent.ClassName)",
      mcOutputOptions: ["ScreenGui", "TextLabel", "StarterGui", "GuiObject"],
      mcOutputCorrectIndex: 0,
      mcOutputExplanation: "The label is parented into the ScreenGui, so its parent's class is `ScreenGui`.",
      fillTypePrompt: "Type the class name so the code creates a text UI child inside the ScreenGui.",
      fillTypeCode: "local label = Instance.new(\"___\")",
      fillTypeAnswer: "TextLabel",
      fillTypeExplanation: "`TextLabel` is the standard class for showing text in a GUI.",
      fillSelectPrompt: "Fill the blanks so the TextLabel is created and given display text.",
      fillSelectCode: "local label = Instance.new(\"___\")\nlabel.___ = \"Start\"",
      fillSelectTokens: ["TextLabel", "Text", "Name", "Players"],
      fillSelectAnswer: ["TextLabel", "Text"],
      fillSelectExplanation: "`TextLabel` creates the GUI text object, and `Text` controls the displayed string.",
      wordBankPrompt: "Build the line that makes the TextLabel a child of the ScreenGui.",
      wordBankTokens: ["label.Parent", "=", "gui", "workspace", "label.Text", "\"Start\""],
      wordBankAnswer: ["label.Parent", "=", "gui"],
      wordBankExplanation: "Parenting the label to `gui` puts it inside the ScreenGui container.",
      predictPrompt: "What does this print?",
      predictCode: "local label = Instance.new(\"TextLabel\")\nlabel.Text = \"Start\"\nprint(label.Text)",
      predictAnswer: "Start",
      predictExplanation: "The `Text` property was set to `Start`, so that exact text prints.",
    },
    {
      mcOutputPrompt: "What does this print?",
      mcOutputCode: "local gui = Instance.new(\"ScreenGui\")\ngui.Name = \"MainHud\"\nprint(gui.Name)",
      mcOutputOptions: ["MainHud", "ScreenGui", "StarterGui", "true"],
      mcOutputCorrectIndex: 0,
      mcOutputExplanation: "The GUI was renamed to `MainHud`, so that is what prints.",
      fillTypePrompt: "Type the property name so the ScreenGui is renamed to `MainHud`.",
      fillTypeCode: "local gui = Instance.new(\"ScreenGui\")\ngui.___ = \"MainHud\"",
      fillTypeAnswer: "Name",
      fillTypeExplanation: "Like other Instances, a ScreenGui is renamed through its `Name` property.",
      fillSelectPrompt: "Fill the blanks so the ScreenGui is renamed and then printed.",
      fillSelectCode: "local gui = Instance.new(\"ScreenGui\")\ngui.___ = \"MainHud\"\nprint(gui.___)",
      fillSelectTokens: ["Name", "Name", "Text", "ClassName"],
      fillSelectAnswer: ["Name", "Name"],
      fillSelectExplanation: "The `Name` property is used both for renaming and printing the new name.",
      wordBankPrompt: "Build the line that gives the TextLabel visible text.",
      wordBankTokens: ["label.Text", "=", "\"Coins\"", "workspace", "label.Parent", "gui"],
      wordBankAnswer: ["label.Text", "=", "\"Coins\""],
      wordBankExplanation: "The `Text` property controls what a TextLabel displays on the screen.",
      predictPrompt: "What does this print?",
      predictCode: "local gui = Instance.new(\"ScreenGui\")\nlocal label = Instance.new(\"TextLabel\")\nlabel.Parent = gui\nprint(gui.ClassName)",
      predictAnswer: "ScreenGui",
      predictExplanation: "The container object is a ScreenGui, so its class name prints as `ScreenGui`.",
    },
  ],
  arrange: [
    {
      prompt: "Arrange the code so a ScreenGui is created and parented to StarterGui.",
      lines: [
        "local gui = Instance.new(\"ScreenGui\")",
        "gui.Name = \"MainHud\"",
        "gui.Parent = game:GetService(\"StarterGui\")",
      ],
      correctOrder: [0, 1, 2],
      explanation: "Create the ScreenGui first, optionally rename it second, and parent it last.",
    },
    {
      prompt: "Arrange the code so a TextLabel is created, given text, and parented into the ScreenGui.",
      lines: [
        "local label = Instance.new(\"TextLabel\")",
        "label.Text = \"Coins\"",
        "label.Parent = gui",
      ],
      correctOrder: [0, 1, 2],
      explanation: "Create the label first, assign its text second, then put it into the GUI container.",
    },
    {
      prompt: "Arrange the code so a ScreenGui is created and its class is printed.",
      lines: [
        "local gui = Instance.new(\"ScreenGui\")",
        "local kind = gui.ClassName",
        "print(kind)",
      ],
      correctOrder: [0, 1, 2],
      explanation: "The GUI must exist before its class name can be read and printed.",
    },
  ],
  bugs: [
    {
      prompt: "Which version has the bug if the goal is to create a ScreenGui?",
      versionA: "local gui = Instance.new(\"ScreenGui\")",
      versionB: "local gui = Instance.new(\"Screen GUI\")",
      buggyVersion: "B",
      explanation: "The class name must be exactly `ScreenGui` without a space.",
    },
    {
      prompt: "Which version has the bug if the goal is to show text on a TextLabel?",
      versionA: "local label = Instance.new(\"TextLabel\")\nlabel.Text = \"Start\"",
      versionB: "local label = Instance.new(\"TextLabel\")\nlabel.Name = \"Start\"",
      buggyVersion: "B",
      explanation: "The visible displayed text uses the `Text` property, not the object's `Name`.",
    },
    {
      prompt: "Which version has the bug if the goal is to parent the ScreenGui to StarterGui?",
      versionA: "gui.Parent = game:GetService(\"StarterGui\")",
      versionB: "gui.Parent = game:GetService(\"ScreenGui\")",
      buggyVersion: "B",
      explanation: "`ScreenGui` is not a service. The usual service container is `StarterGui`.",
    },
  ],
};

export const screenGuiQuestions: Question[] = buildRobloxCodeConceptQuestions(screenGuiSpec);
