import { Question } from "@/lib/data/questions/types";

export const studioLayoutQuestions: Question[] = [
  {
    id: "roblox-studio-layout-mc-1",
    type: "mc_concept",
    concept: "studio-layout",
    language: "lua",
    difficulty: 1,
    prompt: "Which ribbon tab contains the controls used to show or hide panels such as Explorer, Properties, and Output?",
    options: ["Home", "Model", "Test", "View"],
    correctIndex: 3,
    explanation:
      "The `View` tab is where Roblox Studio groups panel visibility controls. If you close Explorer, Properties, or Output, you normally bring them back from `View`. The other tabs focus on building tools, testing, or modeling rather than panel visibility.",
  },
  {
    id: "roblox-studio-layout-mc-2",
    type: "mc_concept",
    concept: "studio-layout",
    language: "lua",
    difficulty: 1,
    prompt: "What is the name of the central Studio area that displays the 3D place while you edit it?",
    options: ["Explorer", "Properties", "3D Viewport", "Output"],
    correctIndex: 2,
    explanation:
      "The 3D Viewport is the part of Studio where you see and manipulate the world directly. Explorer shows the object tree, Properties shows values for the selected object, and Output shows messages. Only the viewport renders the place itself.",
  },
  {
    id: "roblox-studio-layout-tf-1",
    type: "true_false",
    concept: "studio-layout",
    language: "lua",
    difficulty: 1,
    prompt: "In this code, `Workspace` refers to a runtime service, not to a Studio panel.",
    code: "local world = game:GetService(\"Workspace\")\nprint(world.Name)",
    options: ["True", "False"],
    correctIndex: 0,
    correctAnswer: "True",
    explanation:
      "This code accesses the `Workspace` service from the running DataModel. That is different from Studio interface panels like Explorer or Properties. The viewport shows objects from Workspace, but the panel layout itself is not something you fetch with `game:GetService()`.",
  },
  {
    id: "roblox-studio-layout-ft-1",
    type: "fill_type",
    concept: "studio-layout",
    language: "lua",
    difficulty: 1,
    prompt: "Type the service name that matches the live world you see in the 3D viewport.",
    code: "local world = game:GetService(\"___\")",
    correctAnswer: "Workspace",
    explanation:
      "The 3D viewport shows the place's world, and the runtime service for that world is `Workspace`. In Roblox Lua, the normal way to get it explicitly is `game:GetService(\"Workspace\")`. This question connects the editor view you see to the service your scripts actually use.",
  },
  {
    id: "roblox-studio-layout-ft-2",
    type: "fill_type",
    concept: "studio-layout",
    language: "lua",
    difficulty: 1,
    prompt: "Type the property that prints the service name `Workspace`.",
    code: "local world = game:GetService(\"Workspace\")\nprint(world.___)",
    correctAnswer: "Name",
    explanation:
      "Every Instance in Roblox has a `Name` property, including services. Here, `world.Name` prints the service's actual name, which is `Workspace`. `ClassName` would also be meaningful, but it answers a different question: what class the object is, not what its current name is.",
  },
  {
    id: "roblox-studio-layout-mco-1",
    type: "mc_output",
    concept: "studio-layout",
    language: "lua",
    difficulty: 1,
    prompt: "What does this code print?",
    code: "print(game:GetService(\"Workspace\").Name)",
    options: ["workspace", "Explorer", "Workspace", "View"],
    correctIndex: 2,
    explanation:
      "The code gets the `Workspace` service and prints its `Name` property. Roblox service names are case-sensitive, so the result is `Workspace` with a capital `W`. `Explorer` and `View` are Studio UI terms, not the value produced by this script.",
  },
  {
    id: "roblox-studio-layout-sb-1",
    type: "spot_bug",
    concept: "studio-layout",
    language: "lua",
    difficulty: 2,
    prompt: "Which version has the bug if the goal is to get the runtime world that Studio shows in the viewport?",
    code: "### Version A\nlocal world = game:GetService(\"Workspace\")\n### Version B\nlocal world = game:GetService(\"Explorer\")",
    options: ["Version A", "Version B"],
    correctIndex: 1,
    explanation:
      "Version B is wrong because `Explorer` is a Studio panel, not a Roblox runtime service. `Workspace` is the actual service that represents the live 3D world. This distinction matters because Studio UI and the game's DataModel are separate things.",
  },
  {
    id: "roblox-studio-layout-mc-3",
    type: "mc_concept",
    concept: "studio-layout",
    language: "lua",
    difficulty: 2,
    prompt: "If you drag the Explorer panel from one side of Studio to another, what changes?",
    options: [
      "Only the panel's dock position in the editor",
      "The parent-child relationships of Instances in the game",
      "Which service `game:GetService(\"Workspace\")` returns",
      "Which objects are saved in the place file",
    ],
    correctIndex: 0,
    explanation:
      "Dragging Explorer changes where the panel sits in the Studio window. It does not modify the DataModel, reparent objects, or change runtime services. This is an editor-layout action, not a game-data action.",
  },
  {
    id: "roblox-studio-layout-fs-1",
    type: "fill_select",
    concept: "studio-layout",
    language: "lua",
    difficulty: 2,
    prompt: "Fill the blanks so the script gets the world service and prints its Roblox class.",
    code: "local world = game:GetService(\"___\")\nprint(world.___)",
    tokens: ["Workspace", "ClassName", "Explorer", "Parent"],
    correctTokens: ["Workspace", "ClassName"],
    correctBlanks: ["Workspace", "ClassName"],
    explanation:
      "The first blank is `Workspace` because that is the service backing the world you see in the viewport. The second blank is `ClassName`, which prints the Roblox class of the object. `Explorer` is not a service name, and `Parent` would print the object's parent instead of its class.",
  },
  {
    id: "roblox-studio-layout-tf-2",
    type: "true_false",
    concept: "studio-layout",
    language: "lua",
    difficulty: 2,
    prompt: "Hiding the Output panel deletes the scripts that previously wrote messages to it.",
    options: ["True", "False"],
    correctIndex: 1,
    correctAnswer: "False",
    explanation:
      "Hiding Output only affects whether you can currently see that panel in the editor. It does not delete any scripts, services, or Instances in the place. Output is part of Studio layout, not part of the saved game hierarchy.",
  },
  {
    id: "roblox-studio-layout-mc-4",
    type: "mc_concept",
    concept: "studio-layout",
    language: "lua",
    difficulty: 2,
    prompt: "Which of the following is part of the Studio layout rather than a runtime Roblox service?",
    options: ["Players", "TweenService", "Ribbon", "DataStoreService"],
    correctIndex: 2,
    explanation:
      "The ribbon is a Studio UI element at the top of the editor window. `Players`, `TweenService`, and `DataStoreService` are runtime services inside the DataModel that scripts can access. Knowing the difference keeps you from trying to treat editor UI as game code.",
  },
  {
    id: "roblox-studio-layout-pt-1",
    type: "predict_type",
    concept: "studio-layout",
    language: "lua",
    difficulty: 2,
    prompt: "What does this code print?",
    code: "local world = game:GetService(\"Workspace\")\nprint(world == workspace)",
    correctAnswer: "true",
    explanation:
      "Both expressions refer to the same `Workspace` object. `game:GetService(\"Workspace\")` gets it explicitly, while `workspace` is the global shortcut Roblox provides. That is why the equality check prints `true`.",
  },
  {
    id: "roblox-studio-layout-arr-1",
    type: "arrange",
    concept: "studio-layout",
    language: "lua",
    difficulty: 2,
    prompt: "Arrange the code so it gets the world service shown in the viewport, stores its class, and prints it.",
    lines: [
      "local world = game:GetService(\"Workspace\")",
      "local kind = world.ClassName",
      "print(kind)",
    ],
    correctOrder: [0, 1, 2],
    explanation:
      "The script has to fetch the service before it can read a property from it. After that, it can store `ClassName` in a variable and print the result. Reversing the order would try to use `world` before it exists.",
  },
  {
    id: "roblox-studio-layout-mc-5",
    type: "mc_concept",
    concept: "studio-layout",
    language: "lua",
    difficulty: 2,
    prompt: "What is the name of the top Studio command area that groups tools under tabs such as Home, Model, Test, and View?",
    options: ["Toolbox", "Explorer", "Status Bar", "Ribbon"],
    correctIndex: 3,
    explanation:
      "That top command area is called the ribbon. It organizes tools into tabs instead of placing every command in one long list. Toolbox and Explorer are separate panels, and the status bar is not the tabbed command area.",
  },
  {
    id: "roblox-studio-layout-mc-6",
    type: "mc_concept",
    concept: "studio-layout",
    language: "lua",
    difficulty: 2,
    prompt: "Installed plugins typically add buttons under which Studio tab?",
    options: ["View", "Plugins", "Home", "Test"],
    correctIndex: 1,
    explanation:
      "Roblox Studio exposes plugin tools through the `Plugins` tab. That keeps plugin commands separate from the built-in Home, Test, and View tab controls. If a user installs a plugin, its buttons usually appear there rather than as a runtime service in code.",
  },
];
