import type { Question } from "@/lib/data/questions/types";
import { buildRobloxCodeConceptQuestions, type RobloxCodeConceptSpec } from "@/lib/robloxCourse/builders";

const touchedEventSpec: RobloxCodeConceptSpec = {
  concept: "touched-event",
  title: "Part.Touched",
  nodeType: "teaching",
  definitions: [
    {
      prompt: "What does the `Touched` event on a Part represent in Roblox?",
      options: [
        "A signal that can fire when the part touches another part",
        "A Studio panel that lists all collisions in the map",
        "A service used to save player data permanently",
        "A method that publishes the place to Roblox",
      ],
      correctIndex: 0,
      explanation: "`Touched` is an event signal on BasePart objects. Scripts use it to react to physical contact.",
    },
    {
      prompt: "Which object type commonly exposes the `Touched` event?",
      options: [
        "A Part or other BasePart object",
        "A ScreenGui only",
        "The Explorer panel",
        "A DataStore object",
      ],
      correctIndex: 0,
      explanation: "`Touched` belongs to physical part objects like `Part`, not to GUI objects or Studio panels.",
    },
    {
      prompt: "What value is usually passed into the callback for `part.Touched:Connect(function(hit) ... end)`?",
      options: [
        "The other part that touched it",
        "A text string naming the Studio tool",
        "The Players service object",
        "A tween animation object",
      ],
      correctIndex: 0,
      explanation: "The callback parameter usually represents the touching part, often named `hit`.",
    },
    {
      prompt: "Why would a Roblox developer use `Touched`?",
      options: [
        "To react to collisions such as checkpoints, traps, pads, or pickups",
        "To open the Terrain Editor from code",
        "To browse toolbox assets inside a script",
        "To get the list of current players from the server",
      ],
      correctIndex: 0,
      explanation: "`Touched` is commonly used for collision-driven gameplay systems like checkpoints and damage pads.",
    },
  ],
  truths: [
    {
      prompt: "The expression `part.Touched` is an event signal, not a normal string property.",
      correct: true,
      explanation: "Roblox exposes `Touched` as an `RBXScriptSignal`, which is why you connect it with `:Connect()`.",
      code: "local part = Instance.new(\"Part\")\nprint(typeof(part.Touched))",
    },
    {
      prompt: "A script usually connects to `Touched` with `part.Touched:Connect(function(hit) ... end)`.",
      correct: true,
      explanation: "That is the normal Roblox pattern for reacting to touches on a part.",
    },
    {
      prompt: "The callback parameter in `Touched` is automatically the Players service.",
      correct: false,
      explanation: "The parameter usually represents the touching part, not the whole Players service.",
    },
    {
      prompt: "Simply connecting a callback means the `Touched` event has already fired.",
      correct: false,
      explanation: "Connecting prepares the callback, but the event still has to happen before the callback runs.",
      code: "local part = Instance.new(\"Part\")\npart.Touched:Connect(function(hit)\n    print(hit.Name)\nend)",
    },
  ],
  examples: [
    {
      mcOutputPrompt: "What does this print?",
      mcOutputCode: "local part = Instance.new(\"Part\")\nprint(typeof(part.Touched))",
      mcOutputOptions: ["RBXScriptSignal", "RBXScriptConnection", "Part", "string"],
      mcOutputCorrectIndex: 0,
      mcOutputExplanation: "`Touched` is a signal on the part, so `typeof` prints `RBXScriptSignal`.",
      fillTypePrompt: "Type the event name so the script refers to the touch signal on the part.",
      fillTypeCode: "local part = Instance.new(\"Part\")\nprint(typeof(part.___))",
      fillTypeAnswer: "Touched",
      fillTypeExplanation: "`Touched` is the event signal exposed by a Part for contact detection.",
      fillTypeHint: "Use the collision event name on a Part.",
      fillSelectPrompt: "Fill the blanks so the script stores the touch signal and prints its type.",
      fillSelectCode: "local part = Instance.new(\"Part\")\nlocal signal = part.___\nprint(typeof(___))",
      fillSelectTokens: ["Touched", "signal", "Connect", "workspace"],
      fillSelectAnswer: ["Touched", "signal"],
      fillSelectExplanation: "The signal is `part.Touched`, and the local variable `signal` is what gets inspected.",
      wordBankPrompt: "Build the line that stores the touch signal in a variable.",
      wordBankTokens: ["local", "signal", "=", "part.Touched", "workspace", "part.Name"],
      wordBankAnswer: ["local", "signal", "=", "part.Touched"],
      wordBankExplanation: "That line captures the touch signal from the part.",
      predictPrompt: "What does this print?",
      predictCode: "local part = Instance.new(\"Part\")\nprint(part.Touched ~= nil)",
      predictAnswer: "true",
      predictExplanation: "A new Part already exposes the `Touched` signal, so the comparison is true.",
    },
    {
      mcOutputPrompt: "What does this print if the part never gets touched?",
      mcOutputCode: "local part = Instance.new(\"Part\")\nlocal connected = false\npart.Touched:Connect(function(hit)\n    connected = true\nend)\nprint(connected)",
      mcOutputOptions: ["false", "true", "Part", "nil"],
      mcOutputCorrectIndex: 0,
      mcOutputExplanation: "The callback is connected, but it never runs because no touch happens in this snippet.",
      fillTypePrompt: "Type the method name used to subscribe to the touch event.",
      fillTypeCode: "local part = Instance.new(\"Part\")\npart.Touched:___(function(hit)\n    print(hit.Name)\nend)",
      fillTypeAnswer: "Connect",
      fillTypeExplanation: "`Connect` subscribes a callback to the event signal.",
      fillSelectPrompt: "Fill the blanks so the callback parameter is declared and then printed.",
      fillSelectCode: "local part = Instance.new(\"Part\")\npart.Touched:Connect(function(___)\n    print(___.Name)\nend)",
      fillSelectTokens: ["hit", "hit", "player", "workspace"],
      fillSelectAnswer: ["hit", "hit"],
      fillSelectExplanation: "The same parameter name `hit` is declared in the callback and then used inside it.",
      wordBankPrompt: "Build the line that connects a callback to the touch event.",
      wordBankTokens: ["part.Touched:Connect(function(hit)", "print(hit.Name)", "end)", "workspace", "part.Name", "="],
      wordBankAnswer: ["part.Touched:Connect(function(hit)", "print(hit.Name)", "end)"],
      wordBankExplanation: "Those tokens form a valid one-line event connection for the `Touched` signal.",
      predictPrompt: "What does this print?",
      predictCode: "local part = Instance.new(\"Part\")\npart.Touched:Connect(function(hit)\n    print(hit.Name)\nend)\nprint(\"ready\")",
      predictAnswer: "ready",
      predictExplanation: "The callback does not run by itself here, so only the final `print(\"ready\")` produces output.",
    },
    {
      mcOutputPrompt: "What does this print?",
      mcOutputCode: "local part = Instance.new(\"Part\")\nlocal hitName = \"none\"\npart.Touched:Connect(function(hit)\n    hitName = hit.Name\nend)\nprint(hitName)",
      mcOutputOptions: ["none", "Part", "true", "Workspace"],
      mcOutputCorrectIndex: 0,
      mcOutputExplanation: "No touch occurs, so `hitName` stays `none`.",
      fillTypePrompt: "Type the callback parameter name so the touching part can be referenced as `hit`.",
      fillTypeCode: "local part = Instance.new(\"Part\")\npart.Touched:Connect(function(___)\n    print(hit.ClassName)\nend)",
      fillTypeAnswer: "hit",
      fillTypeExplanation: "Naming the callback parameter `hit` makes `hit.ClassName` refer to the touching part inside the function.",
      fillSelectPrompt: "Fill the blanks so the touch signal is connected and the callback receives `hit`.",
      fillSelectCode: "local part = Instance.new(\"Part\")\npart.___:Connect(function(___)\n    print(hit.Name)\nend)",
      fillSelectTokens: ["Touched", "hit", "Event", "player"],
      fillSelectAnswer: ["Touched", "hit"],
      fillSelectExplanation: "The event is `Touched`, and the callback parameter is the touching part variable `hit`.",
      wordBankPrompt: "Build the line that prints the type of the touch signal.",
      wordBankTokens: ["print", "(", "typeof(part.Touched)", ")", "workspace", "Connect"],
      wordBankAnswer: ["print", "(", "typeof(part.Touched)", ")"],
      wordBankExplanation: "Printing `typeof(part.Touched)` confirms that the signal is an `RBXScriptSignal`.",
      predictPrompt: "What does this print?",
      predictCode: "local part = Instance.new(\"Part\")\nlocal connection = part.Touched:Connect(function() end)\nprint(typeof(connection))",
      predictAnswer: "RBXScriptConnection",
      predictExplanation: "Connecting to `Touched` returns an `RBXScriptConnection` object.",
    },
    {
      mcOutputPrompt: "What does this print?",
      mcOutputCode: "local part = Instance.new(\"Part\")\nlocal connection = part.Touched:Connect(function() end)\nprint(connection ~= nil)",
      mcOutputOptions: ["true", "false", "Part", "RBXScriptSignal"],
      mcOutputCorrectIndex: 0,
      mcOutputExplanation: "`Connect()` returns a connection object, so it is not `nil`.",
      fillTypePrompt: "Type the method name so the code connects and stores the returned connection object.",
      fillTypeCode: "local part = Instance.new(\"Part\")\nlocal connection = part.Touched:___(function() end)",
      fillTypeAnswer: "Connect",
      fillTypeExplanation: "`Connect` returns the `RBXScriptConnection` used for the event subscription.",
      fillSelectPrompt: "Fill the blanks so the returned connection object is stored and inspected.",
      fillSelectCode: "local part = Instance.new(\"Part\")\nlocal connection = part.Touched:___(function() end)\nprint(typeof(___))",
      fillSelectTokens: ["Connect", "connection", "Touched", "workspace"],
      fillSelectAnswer: ["Connect", "connection"],
      fillSelectExplanation: "The event uses `Connect`, and the connection object is stored in `connection`.",
      wordBankPrompt: "Build the line that stores the returned connection object from the touch event.",
      wordBankTokens: ["local", "connection", "=", "part.Touched:Connect(function() end)", "workspace", "part.Touched"],
      wordBankAnswer: ["local", "connection", "=", "part.Touched:Connect(function() end)"],
      wordBankExplanation: "That line captures the event subscription object returned by `Connect()`.",
      predictPrompt: "What does this print?",
      predictCode: "local part = Instance.new(\"Part\")\nlocal connected = false\npart.Touched:Connect(function()\n    connected = true\nend)\nprint(connected)",
      predictAnswer: "false",
      predictExplanation: "The event is connected, but it is never triggered in this snippet.",
    },
  ],
  arrange: [
    {
      prompt: "Arrange the code so a part is created, its touch event is connected, and a message prints when hit.",
      lines: [
        "local part = Instance.new(\"Part\")",
        "part.Touched:Connect(function(hit)\n    print(hit.Name)\nend)",
        "print(typeof(part.Touched))",
      ],
      correctOrder: [0, 1, 2],
      explanation: "The part must exist before you can connect its touch event or inspect the signal.",
    },
    {
      prompt: "Arrange the code so the returned connection object is stored and its type is printed.",
      lines: [
        "local part = Instance.new(\"Part\")",
        "local connection = part.Touched:Connect(function() end)",
        "print(typeof(connection))",
      ],
      correctOrder: [0, 1, 2],
      explanation: "Create the part first, then connect the event, then inspect the returned connection object.",
    },
    {
      prompt: "Arrange the code so the touch signal is stored and then checked for nil.",
      lines: [
        "local part = Instance.new(\"Part\")",
        "local signal = part.Touched",
        "print(signal ~= nil)",
      ],
      correctOrder: [0, 1, 2],
      explanation: "The part must exist before the touch signal can be stored and checked.",
    },
  ],
  bugs: [
    {
      prompt: "Which version has the bug if the goal is to connect to the touch event?",
      versionA: "part.Touched:Connect(function(hit)\n    print(hit.Name)\nend)",
      versionB: "part.Touch:Connect(function(hit)\n    print(hit.Name)\nend)",
      buggyVersion: "B",
      explanation: "The event name is `Touched`, not `Touch`.",
    },
    {
      prompt: "Which version has the bug if the goal is to subscribe to the touch signal?",
      versionA: "part.Touched:Connect(function(hit)\n    print(hit.Name)\nend)",
      versionB: "part.Touched(function(hit)\n    print(hit.Name)\nend)",
      buggyVersion: "B",
      explanation: "`Touched` is a signal property, so you subscribe with `:Connect()`.",
    },
    {
      prompt: "Which version has the bug if the goal is to print the touching part name?",
      versionA: "part.Touched:Connect(function(hit)\n    print(hit.Name)\nend)",
      versionB: "part.Touched:Connect(function(hit)\n    print(player.Name)\nend)",
      buggyVersion: "B",
      explanation: "The callback parameter here is `hit`, so `player` is the wrong variable name.",
    },
  ],
};

export const touchedEventQuestions: Question[] = buildRobloxCodeConceptQuestions(touchedEventSpec);
