import type { Question } from "@/lib/data/questions/types";
import { buildRobloxCodeConceptQuestions, type RobloxCodeConceptSpec } from "@/lib/robloxCourse/builders";

const tweenServiceSpec: RobloxCodeConceptSpec = {
  concept: "tween-service",
  title: "TweenService",
  nodeType: "teaching",
  definitions: [
    {
      prompt: "What is `TweenService` mainly used for in Roblox?",
      options: [
        "Animating object properties smoothly over time",
        "Saving player data permanently",
        "Reading the Explorer hierarchy",
        "Connecting player join events",
      ],
      correctIndex: 0,
      explanation: "`TweenService` creates smooth transitions for properties like position, size, color, and transparency.",
    },
    {
      prompt: "Which object is used to configure tween timing in Roblox?",
      options: [
        "TweenInfo",
        "PlayerInfo",
        "RemoteInfo",
        "PartInfo",
      ],
      correctIndex: 0,
      explanation: "`TweenInfo` stores timing and easing settings used when creating a tween.",
    },
    {
      prompt: "Which line correctly gets TweenService?",
      options: [
        "local tweenService = game:GetService(\"TweenService\")",
        "local tweenService = TweenService.new()",
        "local tweenService = workspace.TweenService",
        "local tweenService = game.TweenService()",
      ],
      correctIndex: 0,
      explanation: "Roblox services are accessed with `game:GetService(\"ServiceName\")`.",
    },
    {
      prompt: "What does `TweenService:Create(...)` return?",
      options: [
        "A Tween object",
        "A ScreenGui",
        "A DataStore",
        "A player table",
      ],
      correctIndex: 0,
      explanation: "`TweenService:Create()` builds a Tween object that you can later play with `:Play()`.",
    },
  ],
  truths: [
    {
      prompt: "`TweenService` is a Roblox service accessed through `game:GetService(\"TweenService\")`.",
      correct: true,
      explanation: "TweenService is part of the DataModel service set, so it is fetched with `GetService`.",
      code: "local tweenService = game:GetService(\"TweenService\")\nprint(tweenService.Name)",
    },
    {
      prompt: "`TweenInfo.new(...)` is commonly passed into `TweenService:Create(...)`.",
      correct: true,
      explanation: "TweenInfo describes timing and easing, and `Create` uses that information to build the tween.",
    },
    {
      prompt: "Creating a tween automatically plays it even if `:Play()` is never called.",
      correct: false,
      explanation: "A Tween object is created first. You typically call `tween:Play()` to start it.",
    },
    {
      prompt: "`TweenService` is only for Studio panel animation and cannot affect Roblox objects.",
      correct: false,
      explanation: "Tweens are commonly used on in-game objects like Parts and GUI objects.",
    },
  ],
  examples: [
    {
      mcOutputPrompt: "What does this print?",
      mcOutputCode: "local tweenService = game:GetService(\"TweenService\")\nprint(tweenService.Name)",
      mcOutputOptions: ["TweenService", "Tween", "Workspace", "nil"],
      mcOutputCorrectIndex: 0,
      mcOutputExplanation: "The service object's `Name` property is `TweenService`.",
      fillTypePrompt: "Type the service name so the script gets Roblox's tween animation service.",
      fillTypeCode: "local tweenService = game:GetService(\"___\")",
      fillTypeAnswer: "TweenService",
      fillTypeExplanation: "The service name must match exactly: `TweenService`.",
      fillTypeHint: "Use the Roblox service that creates smooth property animations.",
      fillSelectPrompt: "Fill the blanks so the code gets TweenService and prints its class name.",
      fillSelectCode: "local tweenService = game:GetService(\"___\")\nprint(tweenService.___)",
      fillSelectTokens: ["TweenService", "ClassName", "Name", "Players"],
      fillSelectAnswer: ["TweenService", "ClassName"],
      fillSelectExplanation: "The service is `TweenService`, and `ClassName` prints its Roblox type.",
      wordBankPrompt: "Build the line that stores TweenService in a variable.",
      wordBankTokens: ["local", "tweenService", "=", "game:GetService(\"TweenService\")", "workspace", "tweenService.Name"],
      wordBankAnswer: ["local", "tweenService", "=", "game:GetService(\"TweenService\")"],
      wordBankExplanation: "That line gets the service and stores it locally for reuse.",
      predictPrompt: "What does this print?",
      predictCode: "local tweenInfo = TweenInfo.new(1)\nprint(tweenInfo.Time)",
      predictAnswer: "1",
      predictExplanation: "The TweenInfo was created with a one-second duration, so `.Time` prints `1`.",
    },
    {
      mcOutputPrompt: "What does this print?",
      mcOutputCode: "local tweenInfo = TweenInfo.new(2)\nprint(tweenInfo.Time)",
      mcOutputOptions: ["2", "1", "0", "TweenInfo"],
      mcOutputCorrectIndex: 0,
      mcOutputExplanation: "The TweenInfo duration was set to 2 seconds, so `.Time` prints `2`.",
      fillTypePrompt: "Type the constructor name used to make a tween timing object.",
      fillTypeCode: "local tweenInfo = ___.new(1)",
      fillTypeAnswer: "TweenInfo",
      fillTypeExplanation: "`TweenInfo.new(...)` creates the timing object used by TweenService.",
      fillSelectPrompt: "Fill the blanks so the script creates a tween timing object and prints its duration.",
      fillSelectCode: "local tweenInfo = ___.new(1)\nprint(tweenInfo.___)",
      fillSelectTokens: ["TweenInfo", "Time", "Name", "Players"],
      fillSelectAnswer: ["TweenInfo", "Time"],
      fillSelectExplanation: "`TweenInfo.new` creates the timing object, and `Time` reads its duration.",
      wordBankPrompt: "Build the line that creates a one-second TweenInfo object.",
      wordBankTokens: ["local", "tweenInfo", "=", "TweenInfo.new(1)", "workspace", "print(tweenInfo)"],
      wordBankAnswer: ["local", "tweenInfo", "=", "TweenInfo.new(1)"],
      wordBankExplanation: "That line constructs a TweenInfo value with a one-second duration.",
      predictPrompt: "What does this print?",
      predictCode: "local part = Instance.new(\"Part\")\nlocal tween = game:GetService(\"TweenService\"):Create(part, TweenInfo.new(1), {Transparency = 0.5})\nprint(tween.ClassName)",
      predictAnswer: "Tween",
      predictExplanation: "`TweenService:Create()` returns a Tween object, so its class name prints as `Tween`.",
    },
    {
      mcOutputPrompt: "What does this print?",
      mcOutputCode: "local part = Instance.new(\"Part\")\nlocal tween = game:GetService(\"TweenService\"):Create(part, TweenInfo.new(1), {Transparency = 0.5})\nprint(tween.ClassName)",
      mcOutputOptions: ["Tween", "Part", "TweenService", "table"],
      mcOutputCorrectIndex: 0,
      mcOutputExplanation: "Creating the tween returns a Tween object.",
      fillTypePrompt: "Type the method name used on TweenService to build a tween object.",
      fillTypeCode: "local tween = game:GetService(\"TweenService\"):___(part, TweenInfo.new(1), {Transparency = 0.5})",
      fillTypeAnswer: "Create",
      fillTypeExplanation: "`Create` is the TweenService method that builds a tween from a target object, TweenInfo, and goal table.",
      fillSelectPrompt: "Fill the blanks so the tween is created and then started.",
      fillSelectCode: "local tween = game:GetService(\"TweenService\"):Create(part, ___, {Transparency = 0.5})\ntween:___()",
      fillSelectTokens: ["TweenInfo.new(1)", "Play", "Name", "Touched"],
      fillSelectAnswer: ["TweenInfo.new(1)", "Play"],
      fillSelectExplanation: "The tween uses `TweenInfo.new(1)` for timing, and `Play()` starts the animation.",
      wordBankPrompt: "Build the line that starts the tween.",
      wordBankTokens: ["tween:Play()", "tween.Play()", "=", "workspace", "tween.ClassName"],
      wordBankAnswer: ["tween:Play()"],
      wordBankExplanation: "Once a Tween object exists, `:Play()` starts the animation.",
      predictPrompt: "What does this print if the tween is created but not played?",
      predictCode: "local part = Instance.new(\"Part\")\nlocal tween = game:GetService(\"TweenService\"):Create(part, TweenInfo.new(1), {Transparency = 0.5})\nprint(part.Transparency)",
      predictAnswer: "0",
      predictExplanation: "Creating a tween does not change the property immediately. Without playing it, the part keeps its default transparency of `0`.",
    },
    {
      mcOutputPrompt: "What does this print?",
      mcOutputCode: "local tweenInfo = TweenInfo.new(0.5)\nprint(tweenInfo.Time > 0)",
      mcOutputOptions: ["true", "false", "0.5", "TweenInfo"],
      mcOutputCorrectIndex: 0,
      mcOutputExplanation: "The duration is positive, so the comparison prints `true`.",
      fillTypePrompt: "Type the method name that actually starts a Tween object.",
      fillTypeCode: "local tween = game:GetService(\"TweenService\"):Create(Instance.new(\"Part\"), TweenInfo.new(1), {Transparency = 0.5})\ntween:___()",
      fillTypeAnswer: "Play",
      fillTypeExplanation: "`Play()` starts the tween after it has been created.",
      fillSelectPrompt: "Fill the blanks so the code creates the tween and prints its class name.",
      fillSelectCode: "local tween = game:GetService(\"TweenService\"):___(Instance.new(\"Part\"), TweenInfo.new(1), {Transparency = 0.5})\nprint(tween.___)",
      fillSelectTokens: ["Create", "ClassName", "Play", "Touched"],
      fillSelectAnswer: ["Create", "ClassName"],
      fillSelectExplanation: "`Create` builds the Tween object, and `ClassName` prints its type.",
      wordBankPrompt: "Build the line that gets TweenService from the game.",
      wordBankTokens: ["local", "tweenService", "=", "game:GetService(\"TweenService\")", "workspace", "TweenInfo.new(1)"],
      wordBankAnswer: ["local", "tweenService", "=", "game:GetService(\"TweenService\")"],
      wordBankExplanation: "That line fetches the TweenService so the script can create tweens.",
      predictPrompt: "What does this print?",
      predictCode: "local tween = game:GetService(\"TweenService\"):Create(Instance.new(\"Part\"), TweenInfo.new(1), {Transparency = 0.5})\nprint(tween ~= nil)",
      predictAnswer: "true",
      predictExplanation: "Create returns a Tween object, so the result is not nil.",
    },
  ],
  arrange: [
    {
      prompt: "Arrange the code so TweenService is fetched, a TweenInfo is created, and a tween is built.",
      lines: [
        "local tweenService = game:GetService(\"TweenService\")",
        "local tweenInfo = TweenInfo.new(1)",
        "local tween = tweenService:Create(Instance.new(\"Part\"), tweenInfo, {Transparency = 0.5})",
      ],
      correctOrder: [0, 1, 2],
      explanation: "Get the service first, create the timing object second, and build the tween third.",
    },
    {
      prompt: "Arrange the code so a tween is created and then played.",
      lines: [
        "local part = Instance.new(\"Part\")",
        "local tween = game:GetService(\"TweenService\"):Create(part, TweenInfo.new(1), {Transparency = 0.5})",
        "tween:Play()",
      ],
      correctOrder: [0, 1, 2],
      explanation: "The target part must exist first, then the tween can be created and played.",
    },
    {
      prompt: "Arrange the code so TweenInfo is created and its duration is printed.",
      lines: [
        "local tweenInfo = TweenInfo.new(2)",
        "local seconds = tweenInfo.Time",
        "print(seconds)",
      ],
      correctOrder: [0, 1, 2],
      explanation: "Create the TweenInfo first, read its `Time` next, then print the result.",
    },
  ],
  bugs: [
    {
      prompt: "Which version has the bug if the goal is to get TweenService?",
      versionA: "local tweenService = game:GetService(\"TweenService\")",
      versionB: "local tweenService = game:GetService(\"Tween Service\")",
      buggyVersion: "B",
      explanation: "The service name must be exactly `TweenService` without a space.",
    },
    {
      prompt: "Which version has the bug if the goal is to build a tween?",
      versionA: "local tween = tweenService:Create(part, TweenInfo.new(1), {Transparency = 0.5})",
      versionB: "local tween = tweenService.Create(part, TweenInfo.new(1), {Transparency = 0.5})",
      buggyVersion: "B",
      explanation: "`Create` is a method call on TweenService, so the normal syntax uses a colon.",
    },
    {
      prompt: "Which version has the bug if the goal is to start the tween?",
      versionA: "tween:Play()",
      versionB: "tween:Start()",
      buggyVersion: "B",
      explanation: "Tween objects are started with `Play()`, not `Start()`.",
    },
  ],
};

export const tweenServiceQuestions: Question[] = buildRobloxCodeConceptQuestions(tweenServiceSpec);
