import type { LessonData } from "./questionBank";

const lesson = (teaching: LessonData["teaching"], questions: LessonData["questions"]): LessonData => ({
  teaching,
  questions,
});

export const JAVASCRIPT_QUESTION_BANK: Record<string, Record<string, LessonData>> = {
  "1": {
    "1": lesson(
      {
        title: "Meet console.log()",
        explanation: "console.log() shows values in the console. It is one of the first things beginners use in JavaScript. You can use it to make your code talk back to you.",
        example: "console.log('Hello, world!');",
        tip: "Text needs quotes, and JavaScript lines often end with a semicolon.",
      },
      [
        {
          type: "arrange",
          instruction: "Fill in the blanks to print Hello",
          codeLines: ["console.log(___);"],
          tiles: ["'Hello'", "\"Hello\"", "Hello", "42", "name", "true"],
          answer: ["'Hello'"],
          explanation: "console.log('Hello'); prints the word Hello in JavaScript.",
          consoleOutput: "Hello",
        },
        {
          type: "fill",
          instruction: "Complete the code to print a greeting",
          codeLines: ["console.log(___);"],
          tiles: ["'Hi!'", "Hi!", "true", "name"],
          answer: "'Hi!'",
          explanation: "Text must be inside quotes. Without quotes, JavaScript looks for a variable name.",
          consoleOutput: "Hi!",
        },
        {
          type: "multiple_choice",
          instruction: "What does console.log('Hello') output?",
          options: ["Hello", "'Hello'", "console.log Hello", "Nothing"],
          answer: "Hello",
          explanation: "console.log displays the text without the quotes.",
        },
        {
          type: "output",
          instruction: "What does this code print?",
          codeLines: ["console.log('Pico');"],
          options: ["Pico", "'Pico'", "console.log('Pico')", "undefined"],
          answer: "Pico",
          explanation: "console.log shows the string value in the console.",
          consoleOutput: null,
        },
      ]
    ),
    "2": lesson(
      {
        title: "Logging Numbers",
        explanation: "JavaScript can log numbers too. Numbers do not need quotes. You can also do math inside console.log().",
        example: "console.log(42);\nconsole.log(3.14);\nconsole.log(10 + 5);",
        tip: "Numbers are not strings, so leave the quotes off.",
      },
      [
        {
          type: "arrange",
          instruction: "Fill in the blanks to print 42",
          codeLines: ["console.log(___);"],
          tiles: ["42", "'42'", "\"42\"", "0", "name", "true"],
          answer: ["42"],
          explanation: "42 is a number, so it does not need quotes.",
          consoleOutput: "42",
        },
        {
          type: "fill",
          instruction: "Complete the code to print the result of 10 + 5",
          codeLines: ["console.log(10 ___ 5);"],
          tiles: ["+", "-", "x", "&"],
          answer: "+",
          explanation: "+ adds the two numbers together.",
          consoleOutput: "15",
        },
        {
          type: "multiple_choice",
          instruction: "Which of these prints the number 7?",
          options: ["console.log(7);", "console.log('7');", "console.log(\"7\");", "console.log('seven');"],
          answer: "console.log(7);",
          explanation: "7 without quotes is the number 7.",
        },
        {
          type: "output",
          instruction: "What does this code print?",
          codeLines: ["console.log(3 * 4);"],
          options: ["12", "34", "7", "3 * 4"],
          answer: "12",
          explanation: "JavaScript does the math first, then logs the answer.",
          consoleOutput: null,
        },
      ]
    ),
    "3": lesson(
      {
        title: "Logging Multiple Values",
        explanation: "You can log more than one value at a time in JavaScript. console.log puts spaces between comma-separated values when it displays them in the console.",
        example: "console.log('Age:', 10);\nconsole.log('Hello', 'world');",
        tip: "Commas let console.log show several values in one line.",
      },
      [
        {
          type: "arrange",
          instruction: "Fill in the blanks to print Hello and world",
          codeLines: ["___('Hello', 'world')___"],
          tiles: ["console.log", ";", "prompt", "return", ":", ","],
          answer: ["console.log", ";"],
          explanation: "console.log can show both strings with a comma between them.",
          consoleOutput: "Hello world",
        },
        {
          type: "fill",
          instruction: "Complete the code to log a name and age",
          codeLines: ["console.log('Alice', ___);"],
          tiles: ["25", "'25'", "age", "true"],
          answer: "25",
          explanation: "25 is the number being logged here.",
          consoleOutput: "Alice 25",
        },
        {
          type: "multiple_choice",
          instruction: "What does console.log('Hello', 'world') display?",
          options: ["Hello world", "Helloworld", "Hello,world", "'Hello' 'world'"],
          answer: "Hello world",
          explanation: "The values are shown with a space between them in the console.",
        },
        {
          type: "output",
          instruction: "What does this code print?",
          codeLines: ["console.log('I am', 10, 'years old');"],
          options: ["I am 10 years old", "I am10years old", "I am, 10, years old", "undefined"],
          answer: "I am 10 years old",
          explanation: "console.log prints each value with spaces between them.",
          consoleOutput: null,
        },
      ]
    ),
    "4": lesson(
      {
        title: "Comments in JavaScript",
        explanation: "Comments are notes for humans reading your code. JavaScript ignores them when it runs. Single-line comments start with //.",
        example: "// This prints a greeting\nconsole.log('Hello');",
        tip: "Comments explain your code, but they do not run.",
      },
      [
        {
          type: "arrange",
          instruction: "Fill in the blanks to write a comment and then print Hello",
          codeLines: ["___ This is a note", "console.log('Hello')___"],
          tiles: ["//", ";", "#", "--", ":", ","],
          answer: ["//", ";"],
          explanation: "// starts a comment in JavaScript, and the semicolon ends the console.log line.",
          consoleOutput: "Hello",
        },
        {
          type: "fill",
          instruction: "Complete the comment symbol",
          codeLines: ["___ print a greeting", "console.log('Hi');"],
          tiles: ["//", "#", "!", "/*"],
          answer: "//",
          explanation: "// is the normal single-line comment symbol in JavaScript.",
          consoleOutput: "Hi",
        },
        {
          type: "multiple_choice",
          instruction: "What does this line do? // console.log('Hello');",
          options: ["Nothing - it is a comment", "Prints Hello", "Causes an error", "Prints // Hello"],
          answer: "Nothing - it is a comment",
          explanation: "Comments are ignored by JavaScript.",
        },
        {
          type: "output",
          instruction: "What does this code print?",
          codeLines: ["// console.log('Hello');", "console.log('World');"],
          options: ["World", "Hello\nWorld", "// console.log('Hello')\nWorld", "Nothing"],
          answer: "World",
          explanation: "The comment does nothing, so only World is printed.",
          consoleOutput: null,
        },
      ]
    ),
  },
  "2": {
    "1": lesson(
      {
        title: "Creating Variables",
        explanation: "Variables store values so you can use them later. In JavaScript, beginners often use let for values that can change and const for values that stay the same.",
        example: "let name = 'Alice';\nconst age = 25;\nconsole.log(name);",
        tip: "Pick clear variable names so your code is easy to read.",
      },
      [
        {
          type: "arrange",
          instruction: "Fill in the blanks to store Alice in a variable and print it",
          codeLines: ["___ name = 'Alice';", "___(name);"],
          tiles: ["let", "console.log", "if", "return", "==", "prompt"],
          answer: ["let", "console.log"],
          explanation: "let creates the variable, and console.log shows its value.",
          consoleOutput: "Alice",
        },
        {
          type: "fill",
          instruction: "Complete the code to create a variable",
          codeLines: ["let score ___ 100;"],
          tiles: ["=", "==", ":", "->"],
          answer: "=",
          explanation: "= stores a value in the variable.",
          consoleOutput: null,
        },
        {
          type: "multiple_choice",
          instruction: "Which line correctly creates a variable called city?",
          options: ["let city = 'Paris';", "city let = 'Paris';", "'Paris' = city;", "let = city 'Paris';"],
          answer: "let city = 'Paris';",
          explanation: "JavaScript variables use a keyword, a name, =, and a value.",
        },
        {
          type: "output",
          instruction: "What does this code print?",
          codeLines: ["let pet = 'dog';", "console.log(pet);"],
          options: ["dog", "pet", "'dog'", "undefined"],
          answer: "dog",
          explanation: "console.log(pet) shows the value stored in pet.",
          consoleOutput: null,
        },
      ]
    ),
    "2": lesson(
      {
        title: "let and const",
        explanation: "Use const when a value should stay the same. Use let when you plan to change the value later. This makes your code clearer.",
        example: "const planet = 'Earth';\nlet score = 0;\nscore = 10;",
        tip: "If you need to reassign a variable later, use let.",
      },
      [
        {
          type: "multiple_choice",
          instruction: "Which keyword is best for a value that will not change?",
          options: ["const", "let", "var", "change"],
          answer: "const",
          explanation: "const is used for values you do not plan to reassign.",
        },
        {
          type: "multiple_choice",
          instruction: "Which keyword is best for a score that changes during a game?",
          options: ["let", "const", "fixed", "static"],
          answer: "let",
          explanation: "let is used when the value needs to change later.",
        },
        {
          type: "fill",
          instruction: "Complete the code for a value that can change",
          codeLines: ["___ lives = 3;"],
          tiles: ["let", "const", "log", "if"],
          answer: "let",
          explanation: "lives can change, so let is the better choice.",
          consoleOutput: null,
        },
        {
          type: "multiple_choice",
          instruction: "What happens in this code? const name = 'Ava';",
          options: ["It creates a variable named name", "It prints Ava", "It deletes a variable", "It creates a loop"],
          answer: "It creates a variable named name",
          explanation: "const creates a new variable with the given value.",
        },
      ]
    ),
    "3": lesson(
      {
        title: "Changing Variables",
        explanation: "A variable made with let can hold a new value later. This is called reassignment. It is how your program keeps track of changing information.",
        example: "let score = 0;\nscore = 5;\nscore = score + 1;",
        tip: "The new value replaces the old one.",
      },
      [
        {
          type: "arrange",
          instruction: "Fill in the blanks to change score to 10",
          codeLines: ["let score = 0;", "___ ___ 10;", "console.log(score);"],
          tiles: ["score", "=", "==", "const", "let", ":"],
          answer: ["score", "="],
          explanation: "score = 10 changes the variable to the new value.",
          consoleOutput: "10",
        },
        {
          type: "fill",
          instruction: "Complete the code to add 1 to points",
          codeLines: ["let points = 2;", "points = points ___ 1;"],
          tiles: ["+", "-", "*", "/"],
          answer: "+",
          explanation: "Using + 1 increases the variable by one.",
          consoleOutput: "3",
        },
        {
          type: "multiple_choice",
          instruction: "Which line changes a variable named level to 4?",
          options: ["level = 4;", "let = level 4;", "level == 4;", "change level 4;"],
          answer: "level = 4;",
          explanation: "= is used to assign the new value.",
        },
        {
          type: "output",
          instruction: "What does this code print?",
          codeLines: ["let x = 5;", "x = x + 3;", "console.log(x);"],
          options: ["8", "5", "53", "3"],
          answer: "8",
          explanation: "x starts at 5, then 3 is added, so the answer is 8.",
          consoleOutput: null,
        },
      ]
    ),
    "4": lesson(
      {
        title: "Logging Variables",
        explanation: "Once a variable has a value, you can show it with console.log. This lets you see what your program is storing.",
        example: "let city = 'Tokyo';\nconsole.log(city);\nconsole.log('City:', city);",
        tip: "Leave variable names unquoted when you want their stored value.",
      },
      [
        {
          type: "arrange",
          instruction: "Fill in the blanks to print a variable named city",
          codeLines: ["let city = 'Rome';", "___(___)___"],
          tiles: ["console.log", "city", ";", "'city'", "prompt", "return"],
          answer: ["console.log", "city", ";"],
          explanation: "console.log(city); prints the value inside city.",
          consoleOutput: "Rome",
        },
        {
          type: "fill",
          instruction: "Complete the code to print the variable",
          codeLines: ["let name = 'Mia';", "console.log(___);"],
          tiles: ["name", "'name'", "\"name\"", "Mia"],
          answer: "name",
          explanation: "Using the variable name without quotes prints its value.",
          consoleOutput: "Mia",
        },
        {
          type: "multiple_choice",
          instruction: "Which line prints the value stored in score?",
          options: ["console.log(score);", "console.log('score');", "score(console.log);", "print(score);"],
          answer: "console.log(score);",
          explanation: "console.log(score); prints the variable's value.",
        },
        {
          type: "output",
          instruction: "What does this code print?",
          codeLines: ["let food = 'pizza';", "console.log('I like', food);"],
          options: ["I like pizza", "I likefood", "food", "undefined"],
          answer: "I like pizza",
          explanation: "console.log shows both values with a space between them.",
          consoleOutput: null,
        },
      ]
    ),
  },
  "3": {
    "1": lesson(
      {
        title: "Meet prompt()",
        explanation: "prompt() asks the user to type something. Whatever the user types comes back as text. This makes your JavaScript interactive.",
        example: "const name = prompt('What is your name?');\nconsole.log(name);",
        tip: "prompt always gives back text.",
      },
      [
        {
          type: "arrange",
          instruction: "Fill in the blanks to ask for a name",
          codeLines: ["const name = ___(___)___"],
          tiles: ["prompt", "'Your name?'", ";", "console.log", "return", "42"],
          answer: ["prompt", "'Your name?'", ";"],
          explanation: "prompt('Your name?'); asks the user for text input.",
          consoleOutput: null,
        },
        {
          type: "fill",
          instruction: "Complete the code to ask a question",
          codeLines: ["const color = prompt(___);"],
          tiles: ["'Favorite color?'", "Favorite color?", "true", "7"],
          answer: "'Favorite color?'",
          explanation: "The message shown in prompt must be a string.",
          consoleOutput: null,
        },
        {
          type: "multiple_choice",
          instruction: "What does prompt() give back?",
          options: ["Text", "Only numbers", "A loop", "Nothing"],
          answer: "Text",
          explanation: "prompt returns what the user typed as text.",
        },
        {
          type: "multiple_choice",
          instruction: "Which line asks the user for input?",
          options: ["prompt('Type here');", "console.log('Type here');", "return 'Type here';", "let input == 'Type here';"],
          answer: "prompt('Type here');",
          explanation: "prompt shows a box for the user to type into.",
        },
      ]
    ),
    "2": lesson(
      {
        title: "Storing Input",
        explanation: "You usually save the result of prompt in a variable. Then you can use that answer later in your code.",
        example: "const name = prompt('Name?');\nconsole.log('Hi', name);",
        tip: "Store the prompt result in a variable if you want to use it again.",
      },
      [
        {
          type: "arrange",
          instruction: "Fill in the blanks to store user input in a variable",
          codeLines: ["const name ___ prompt('Name?')___"],
          tiles: ["=", "==", ":", "->", ";", "const"],
          answer: ["=", ";"],
          explanation: "= stores the prompt result in the variable, and the line ends with a semicolon.",
          consoleOutput: null,
        },
        {
          type: "fill",
          instruction: "Complete the code to store the user's city",
          codeLines: ["const city = ___('City?');"],
          tiles: ["prompt", "console.log", "return", "let"],
          answer: "prompt",
          explanation: "prompt collects the user input here.",
          consoleOutput: null,
        },
        {
          type: "multiple_choice",
          instruction: "Which variable stores what the user typed?",
          options: ["const name = prompt('Name?');", "console.log(prompt('Name?'));", "prompt('Name?');", "return prompt('Name?');"],
          answer: "const name = prompt('Name?');",
          explanation: "The value is saved into name so you can use it again later.",
        },
        {
          type: "output",
          instruction: "What prints if the user types Sam?",
          codeLines: ["const name = prompt('Name?');", "console.log('Hi', name);"],
          options: ["Hi Sam", "name", "prompt", "undefined"],
          answer: "Hi Sam",
          explanation: "The typed value is stored in name and then printed.",
          consoleOutput: null,
        },
      ]
    ),
    "3": lesson(
      {
        title: "Turning Text into Numbers",
        explanation: "prompt gives back text, even when the user types digits. Number() changes that text into a real number so you can do math with it.",
        example: "const age = Number(prompt('Age?'));\nconsole.log(age + 1);",
        tip: "Use Number(...) before doing math with prompt input.",
      },
      [
        {
          type: "arrange",
          instruction: "Fill in the blanks to turn prompt input into a number",
          codeLines: ["const age = ___(prompt('Age?'));"],
          tiles: ["Number", "String", "console.log", "return", "Alert", "let"],
          answer: ["Number"],
          explanation: "Number(prompt(...)) turns the text into a number.",
          consoleOutput: null,
        },
        {
          type: "fill",
          instruction: "Complete the code so count becomes a number",
          codeLines: ["const count = ___(prompt('Count?'));"],
          tiles: ["Number", "console.log", "prompt", "String"],
          answer: "Number",
          explanation: "Number converts the prompt result from text into a number.",
          consoleOutput: null,
        },
        {
          type: "multiple_choice",
          instruction: "Why use Number(prompt('Age?'))?",
          options: ["To turn text into a number", "To print the age", "To create a loop", "To add quotes"],
          answer: "To turn text into a number",
          explanation: "prompt returns text, so Number helps when you need math.",
        },
        {
          type: "output",
          instruction: "If the user types 5, what does this code print?",
          codeLines: ["const count = Number(prompt('Count?'));", "console.log(count + 2);"],
          options: ["7", "52", "5", "2"],
          answer: "7",
          explanation: "Number makes 5 a number, so 5 + 2 becomes 7.",
          consoleOutput: null,
        },
      ]
    ),
    "4": lesson(
      {
        title: "Using Input in console.log",
        explanation: "Once input is stored in a variable, you can show it back to the user. This is how simple interactive programs respond to what someone typed.",
        example: "const name = prompt('Name?');\nconsole.log('Hello', name);",
        tip: "Store input first, then use the variable in console.log.",
      },
      [
        {
          type: "arrange",
          instruction: "Fill in the blanks to greet the user",
          codeLines: ["const name = prompt('Name?');", "___('Hello', ___)___"],
          tiles: ["console.log", "name", ";", "'name'", "prompt", "return"],
          answer: ["console.log", "name", ";"],
          explanation: "console.log('Hello', name); prints the greeting with the user's input.",
          consoleOutput: "Hello Sam",
        },
        {
          type: "fill",
          instruction: "Complete the code to print the user's color",
          codeLines: ["const color = prompt('Color?');", "console.log(___);"],
          tiles: ["color", "'color'", "\"color\"", "prompt"],
          answer: "color",
          explanation: "Use the variable name to print the value the user typed.",
          consoleOutput: null,
        },
        {
          type: "multiple_choice",
          instruction: "Which line prints a stored user name?",
          options: ["console.log(name);", "console.log('name');", "prompt(name);", "return name;"],
          answer: "console.log(name);",
          explanation: "console.log(name) shows the value stored in the variable.",
        },
        {
          type: "output",
          instruction: "If the user types blue, what does this code print?",
          codeLines: ["const color = prompt('Color?');", "console.log('Your color is', color);"],
          options: ["Your color is blue", "color", "Your color is", "undefined"],
          answer: "Your color is blue",
          explanation: "The input gets stored and then printed with the text.",
          consoleOutput: null,
        },
      ]
    ),
  },
  "4": {
    "1": lesson(
      {
        title: "Joining Strings",
        explanation: "Strings are pieces of text. In JavaScript, you can join strings with the + operator. This lets you build bigger messages from smaller parts.",
        example: "console.log('Hello' + ' ' + 'world');",
        tip: "Add a space string like ' ' when you want words separated.",
      },
      [
        {
          type: "arrange",
          instruction: "Fill in the blanks to join Hello and world",
          codeLines: ["console.log('Hello' ___ ' ' ___ 'world');"],
          tiles: ["+", "+", ",", "-", "*", "/"],
          answer: ["+", "+"],
          explanation: "+ joins strings together in JavaScript.",
          consoleOutput: "Hello world",
        },
        {
          type: "fill",
          instruction: "Complete the code to join two words",
          codeLines: ["console.log('ice' ___ 'cream');"],
          tiles: ["+", ",", "and", "&"],
          answer: "+",
          explanation: "+ is used to connect strings here.",
          consoleOutput: "icecream",
        },
        {
          type: "multiple_choice",
          instruction: "What does 'Hi' + '!' become?",
          options: ["Hi!", "Hi !", "Hi+!", "Error"],
          answer: "Hi!",
          explanation: "The strings are joined exactly as written.",
        },
        {
          type: "output",
          instruction: "What does this code print?",
          codeLines: ["console.log('A' + 'B');"],
          options: ["AB", "A B", "A+B", "undefined"],
          answer: "AB",
          explanation: "The two strings are stuck together with no space added.",
          consoleOutput: null,
        },
      ]
    ),
    "2": lesson(
      {
        title: "String Length",
        explanation: "Every string in JavaScript has a length property. It tells you how many characters are inside the string.",
        example: "const word = 'cat';\nconsole.log(word.length);",
        tip: "Spaces count as characters too.",
      },
      [
        {
          type: "arrange",
          instruction: "Fill in the blanks to print the length of cat",
          codeLines: ["const word = 'cat';", "console.log(word.___)___"],
          tiles: ["length", ";", "size", "count", "()", ":"],
          answer: ["length", ";"],
          explanation: ".length tells you how many characters are in the string.",
          consoleOutput: "3",
        },
        {
          type: "fill",
          instruction: "Complete the code to get the string length",
          codeLines: ["const name = 'Mia';", "console.log(name.___);"],
          tiles: ["length", "size", "count", "long"],
          answer: "length",
          explanation: "length is the correct string property in JavaScript.",
          consoleOutput: "3",
        },
        {
          type: "multiple_choice",
          instruction: "What is the length of 'dog'?",
          options: ["3", "2", "4", "1"],
          answer: "3",
          explanation: "d, o, and g are three characters.",
        },
        {
          type: "output",
          instruction: "What does this code print?",
          codeLines: ["console.log('hi'.length);"],
          options: ["2", "1", "3", "hi"],
          answer: "2",
          explanation: "'hi' has two characters.",
          consoleOutput: null,
        },
      ]
    ),
    "3": lesson(
      {
        title: "Uppercase and Lowercase",
        explanation: "JavaScript strings have methods that can change letter case. toUpperCase() makes all letters uppercase, and toLowerCase() makes them lowercase.",
        example: "console.log('hello'.toUpperCase());\nconsole.log('HELLO'.toLowerCase());",
        tip: "Methods use parentheses at the end.",
      },
      [
        {
          type: "arrange",
          instruction: "Fill in the blanks to make hello uppercase",
          codeLines: ["console.log('hello'.___())___"],
          tiles: ["toUpperCase", ";", "upper", "toLowerCase", "length", ":"],
          answer: ["toUpperCase", ";"],
          explanation: "toUpperCase() changes every letter to uppercase.",
          consoleOutput: "HELLO",
        },
        {
          type: "fill",
          instruction: "Complete the code to make HELLO lowercase",
          codeLines: ["console.log('HELLO'.___());"],
          tiles: ["toLowerCase", "toUpperCase", "lower", "length"],
          answer: "toLowerCase",
          explanation: "toLowerCase() changes each letter to lowercase.",
          consoleOutput: "hello",
        },
        {
          type: "multiple_choice",
          instruction: "What does 'cat'.toUpperCase() return?",
          options: ["CAT", "cat", "Cat", "Error"],
          answer: "CAT",
          explanation: "Every letter becomes uppercase.",
        },
        {
          type: "output",
          instruction: "What does this code print?",
          codeLines: ["console.log('WOW'.toLowerCase());"],
          options: ["wow", "WOW", "WoW", "undefined"],
          answer: "wow",
          explanation: "The string is changed to all lowercase letters.",
          consoleOutput: null,
        },
      ]
    ),
    "4": lesson(
      {
        title: "Template Literals",
        explanation: "Template literals let you put variables inside strings. They use backticks instead of normal quotes. Variables go inside ${ }.",
        example: "const name = 'Lia';\nconsole.log(`Hello ${name}`);",
        tip: "Backticks are different from single quotes.",
      },
      [
        {
          type: "arrange",
          instruction: "Fill in the blanks to greet the user with a template literal",
          codeLines: ["const name = 'Lia';", "console.log(`Hello ___`)___"],
          tiles: ["${name}", ";", "{name}", "$name", "name", ":"],
          answer: ["${name}", ";"],
          explanation: "In a template literal, variables go inside ${ }.",
          consoleOutput: "Hello Lia",
        },
        {
          type: "fill",
          instruction: "Complete the code to insert a variable",
          codeLines: ["const food = 'pizza';", "console.log(`I like ___`);"],
          tiles: ["${food}", "{food}", "$food", "food"],
          answer: "${food}",
          explanation: "${food} inserts the value of food into the string.",
          consoleOutput: "I like pizza",
        },
        {
          type: "multiple_choice",
          instruction: "Which symbol starts and ends a template literal?",
          options: ["Backticks", "Single quotes", "Double quotes", "Parentheses"],
          answer: "Backticks",
          explanation: "Template literals use backticks: `like this`.",
        },
        {
          type: "output",
          instruction: "What does this code print?",
          codeLines: ["const age = 9;", "console.log(`Age: ${age}`);"],
          options: ["Age: 9", "Age: ${age}", "9", "undefined"],
          answer: "Age: 9",
          explanation: "The value of age is inserted into the template literal.",
          consoleOutput: null,
        },
      ]
    ),
  },
  "5": {
    "1": lesson(
      {
        title: "if Statements",
        explanation: "An if statement runs code only when a condition is true. This helps your program make decisions.",
        example: "let score = 10;\nif (score > 5) {\n  console.log('High');\n}",
        tip: "JavaScript if statements use parentheses and curly braces.",
      },
      [
        {
          type: "arrange",
          instruction: "Fill in the blanks to print Big when x is greater than 3",
          codeLines: ["let x = 5;", "if (x > 3) ___", "  console.log('Big');", "___"],
          tiles: ["{", "}", "(", ")", ":" , ";"],
          answer: ["{", "}"],
          explanation: "JavaScript uses { and } to mark the code inside the if statement.",
          consoleOutput: "Big",
        },
        {
          type: "fill",
          instruction: "Complete the condition symbol",
          codeLines: ["if (age ___ 18) {", "  console.log('Adult');", "}"],
          tiles: [">=", "=>", "==", "="],
          answer: ">=",
          explanation: ">= means greater than or equal to.",
          consoleOutput: "Adult",
        },
        {
          type: "multiple_choice",
          instruction: "When does an if statement run its code?",
          options: ["When the condition is true", "Always", "Only when the condition is false", "Never"],
          answer: "When the condition is true",
          explanation: "if only runs the block when the condition is true.",
        },
        {
          type: "output",
          instruction: "What does this code print?",
          codeLines: ["let x = 5;", "if (x > 3) {", "  console.log('Big');", "}"],
          options: ["Big", "Small", "Nothing", "5"],
          answer: "Big",
          explanation: "x is 5, so x > 3 is true.",
          consoleOutput: null,
        },
      ]
    ),
    "2": lesson(
      {
        title: "else Statements",
        explanation: "else gives your program another path when the if condition is false. It is the 'otherwise' part of a decision.",
        example: "if (score > 5) {\n  console.log('High');\n} else {\n  console.log('Low');\n}",
        tip: "Use else right after an if block.",
      },
      [
        {
          type: "arrange",
          instruction: "Fill in the blanks to print Low when score is not above 5",
          codeLines: ["let score = 3;", "if (score > 5) {", "  console.log('High');", "} ___ {", "  console.log('Low');", "}"],
          tiles: ["else", "if", "then", "or"],
          answer: ["else"],
          explanation: "else runs when the if condition is false.",
          consoleOutput: "Low",
        },
        {
          type: "fill",
          instruction: "Complete the keyword for the other path",
          codeLines: ["if (x > 0) {", "  console.log('Positive');", "} ___ {", "  console.log('Not positive');", "}"],
          tiles: ["else", "if", "then", "loop"],
          answer: "else",
          explanation: "else is the fallback block.",
          consoleOutput: null,
        },
        {
          type: "multiple_choice",
          instruction: "What does else mean in code?",
          options: ["Do this when the if condition is false", "Repeat the code", "Ask the user for input", "Create a variable"],
          answer: "Do this when the if condition is false",
          explanation: "else handles the other case.",
        },
        {
          type: "output",
          instruction: "What does this code print?",
          codeLines: ["let x = 1;", "if (x > 5) {", "  console.log('Big');", "} else {", "  console.log('Small');", "}"],
          options: ["Small", "Big", "Nothing", "1"],
          answer: "Small",
          explanation: "x > 5 is false, so the else block runs.",
          consoleOutput: null,
        },
      ]
    ),
    "3": lesson(
      {
        title: "else if Statements",
        explanation: "else if lets you check another condition after the first one. It is helpful when there are more than two possible paths.",
        example: "if (score >= 90) {\n  console.log('A');\n} else if (score >= 80) {\n  console.log('B');\n}",
        tip: "Check the most specific condition first.",
      },
      [
        {
          type: "arrange",
          instruction: "Fill in the blanks to check a second condition",
          codeLines: ["if (score >= 90) {", "  console.log('A');", "} ___ (score >= 80) {", "  console.log('B');", "}"],
          tiles: ["else if", "if else", "elseif", "or if"],
          answer: ["else if"],
          explanation: "JavaScript uses else if as two words.",
          consoleOutput: null,
        },
        {
          type: "fill",
          instruction: "Complete the two-word keyword",
          codeLines: ["if (temp > 90) {", "  console.log('Hot');", "} ___ (temp > 70) {", "  console.log('Warm');", "}"],
          tiles: ["else if", "else", "if", "or"],
          answer: "else if",
          explanation: "else if checks another condition after the first one.",
          consoleOutput: null,
        },
        {
          type: "multiple_choice",
          instruction: "Why use else if?",
          options: ["To check another condition", "To create a variable", "To repeat code forever", "To end the program"],
          answer: "To check another condition",
          explanation: "else if gives you more decision branches.",
        },
        {
          type: "output",
          instruction: "What does this code print when score is 85?",
          codeLines: ["let score = 85;", "if (score >= 90) {", "  console.log('A');", "} else if (score >= 80) {", "  console.log('B');", "} else {", "  console.log('C');", "}"],
          options: ["B", "A", "C", "Nothing"],
          answer: "B",
          explanation: "85 is not at least 90, but it is at least 80.",
          consoleOutput: null,
        },
      ]
    ),
    "4": lesson(
      {
        title: "Combining Conditions",
        explanation: "You can combine conditions with &&, ||, and !. This lets you build more detailed decisions.",
        example: "if (age > 10 && age < 20) {\n  console.log('Teen');\n}",
        tip: "&& means both must be true. || means at least one must be true.",
      },
      [
        {
          type: "arrange",
          instruction: "Fill in the blanks so both conditions must be true",
          codeLines: ["if (age > 10 ___ age < 20) {", "  console.log('Teen');", "}"],
          tiles: ["&&", "||", "==", "+"],
          answer: ["&&"],
          explanation: "&& means both conditions must be true.",
          consoleOutput: "Teen",
        },
        {
          type: "fill",
          instruction: "Complete the symbol for either condition",
          codeLines: ["if (day === 'Sat' ___ day === 'Sun') {", "  console.log('Weekend');", "}"],
          tiles: ["||", "&&", "!", "+"],
          answer: "||",
          explanation: "|| means one condition or the other can be true.",
          consoleOutput: "Weekend",
        },
        {
          type: "multiple_choice",
          instruction: "What does && mean?",
          options: ["Both conditions must be true", "One condition must be true", "Not", "Equals"],
          answer: "Both conditions must be true",
          explanation: "&& checks that the left and right sides are both true.",
        },
        {
          type: "output",
          instruction: "What does this code print?",
          codeLines: ["let age = 15;", "if (age > 10 && age < 20) {", "  console.log('Teen');", "}"],
          options: ["Teen", "Adult", "Nothing", "15"],
          answer: "Teen",
          explanation: "15 is greater than 10 and less than 20.",
          consoleOutput: null,
        },
      ]
    ),
  },
  "6": {
    "1": lesson(
      {
        title: "while Loops",
        explanation: "A while loop repeats code while a condition stays true. It is useful when you do not know the exact number of repeats ahead of time.",
        example: "let x = 1;\nwhile (x <= 3) {\n  console.log(x);\n  x = x + 1;\n}",
        tip: "Make sure something changes inside the loop, or it may run forever.",
      },
      [
        {
          type: "arrange",
          instruction: "Fill in the blanks to make a while loop",
          codeLines: ["let x = 1;", "___ (x <= 3) {", "  console.log(x);", "  x = x + 1;", "}"],
          tiles: ["while", "for", "if", "loop"],
          answer: ["while"],
          explanation: "while starts a loop that repeats while the condition is true.",
          consoleOutput: "1\n2\n3",
        },
        {
          type: "fill",
          instruction: "Complete the code to increase x",
          codeLines: ["let x = 1;", "x = x ___ 1;"],
          tiles: ["+", "-", "*", "/"],
          answer: "+",
          explanation: "Adding 1 moves the loop forward.",
          consoleOutput: null,
        },
        {
          type: "multiple_choice",
          instruction: "What keyword starts a while loop?",
          options: ["while", "for", "repeat", "loop"],
          answer: "while",
          explanation: "while is the correct JavaScript keyword.",
        },
        {
          type: "output",
          instruction: "How many times does this loop run?",
          codeLines: ["let x = 1;", "while (x <= 3) {", "  console.log(x);", "  x = x + 1;", "}"],
          options: ["3", "2", "4", "Forever"],
          answer: "3",
          explanation: "It runs for x = 1, 2, and 3.",
          consoleOutput: null,
        },
      ]
    ),
    "2": lesson(
      {
        title: "for Loops",
        explanation: "A for loop is great when you know how many times you want to repeat. It keeps the starting value, condition, and change together in one line.",
        example: "for (let i = 0; i < 3; i++) {\n  console.log(i);\n}",
        tip: "The loop variable often starts at 0.",
      },
      [
        {
          type: "arrange",
          instruction: "Fill in the blanks to start a for loop",
          codeLines: ["___ (let i = 0; i < 3; i++) {", "  console.log(i);", "}"],
          tiles: ["for", "while", "if", "const"],
          answer: ["for"],
          explanation: "for starts a counted loop in JavaScript.",
          consoleOutput: "0\n1\n2",
        },
        {
          type: "fill",
          instruction: "Complete the loop condition",
          codeLines: ["for (let i = 0; i ___ 3; i++) {", "  console.log(i);", "}"],
          tiles: ["<", ">", "=", "!="],
          answer: "<",
          explanation: "i < 3 means the loop runs while i is smaller than 3.",
          consoleOutput: null,
        },
        {
          type: "multiple_choice",
          instruction: "Which keyword starts this kind of loop?",
          options: ["for", "while", "if", "return"],
          answer: "for",
          explanation: "for is used for counted loops.",
        },
        {
          type: "output",
          instruction: "How many times does this loop run?",
          codeLines: ["for (let i = 0; i < 4; i++) {", "  console.log(i);", "}"],
          options: ["4", "3", "5", "Forever"],
          answer: "4",
          explanation: "It runs with i = 0, 1, 2, and 3.",
          consoleOutput: null,
        },
      ]
    ),
    "3": lesson(
      {
        title: "Loop Counters",
        explanation: "A loop counter tracks which repeat you are on. In a for loop, it often changes with i++ each time around.",
        example: "for (let i = 1; i <= 3; i++) {\n  console.log(i);\n}",
        tip: "i++ means add 1 to i.",
      },
      [
        {
          type: "arrange",
          instruction: "Fill in the blanks to count up by 1",
          codeLines: ["for (let i = 1; i <= 3; ___) {", "  console.log(i);", "}"],
          tiles: ["i++", "i--", "++3", "i+1"],
          answer: ["i++"],
          explanation: "i++ increases i by 1 each time the loop runs.",
          consoleOutput: "1\n2\n3",
        },
        {
          type: "fill",
          instruction: "Complete the code to count down",
          codeLines: ["for (let i = 3; i > 0; ___) {", "  console.log(i);", "}"],
          tiles: ["i--", "i++", "i+1", "i*2"],
          answer: "i--",
          explanation: "i-- subtracts 1 each loop.",
          consoleOutput: "3\n2\n1",
        },
        {
          type: "multiple_choice",
          instruction: "What does i++ do?",
          options: ["Adds 1 to i", "Subtracts 1 from i", "Prints i", "Ends the loop"],
          answer: "Adds 1 to i",
          explanation: "i++ is shorthand for increasing i by one.",
        },
        {
          type: "output",
          instruction: "What does this code print first?",
          codeLines: ["for (let i = 1; i <= 3; i++) {", "  console.log(i);", "}"],
          options: ["1", "0", "2", "3"],
          answer: "1",
          explanation: "The loop starts with i set to 1.",
          consoleOutput: null,
        },
      ]
    ),
    "4": lesson(
      {
        title: "break and continue",
        explanation: "break stops a loop early. continue skips the rest of the current loop turn and moves to the next one.",
        example: "for (let i = 1; i <= 3; i++) {\n  if (i === 2) continue;\n  console.log(i);\n}",
        tip: "Use break to stop, and continue to skip.",
      },
      [
        {
          type: "arrange",
          instruction: "Fill in the blanks to skip printing 2",
          codeLines: ["for (let i = 1; i <= 3; i++) {", "  if (i === 2) ___;", "  console.log(i);", "}"],
          tiles: ["continue", "break", "return", "stop"],
          answer: ["continue"],
          explanation: "continue skips the rest of that loop turn.",
          consoleOutput: "1\n3",
        },
        {
          type: "fill",
          instruction: "Complete the code to stop the loop early",
          codeLines: ["for (let i = 1; i <= 5; i++) {", "  if (i === 3) ___;", "  console.log(i);", "}"],
          tiles: ["break", "continue", "return", "skip"],
          answer: "break",
          explanation: "break ends the loop immediately.",
          consoleOutput: "1\n2",
        },
        {
          type: "multiple_choice",
          instruction: "What does break do?",
          options: ["Stops the loop", "Skips one turn", "Starts a new loop", "Prints a value"],
          answer: "Stops the loop",
          explanation: "break ends the loop right away.",
        },
        {
          type: "output",
          instruction: "What does this code print?",
          codeLines: ["for (let i = 1; i <= 3; i++) {", "  if (i === 2) continue;", "  console.log(i);", "}"],
          options: ["1\n3", "1\n2\n3", "2", "Nothing"],
          answer: "1\n3",
          explanation: "When i is 2, continue skips the console.log line.",
          consoleOutput: null,
        },
      ]
    ),
  },
  "7": {
    "1": lesson(
      {
        title: "Defining Functions",
        explanation: "A function is a reusable block of code. In JavaScript, you can define one with the function keyword.",
        example: "function greet() {\n  console.log('Hi');\n}",
        tip: "A function runs only when you call it.",
      },
      [
        {
          type: "arrange",
          instruction: "Fill in the blanks to define a function",
          codeLines: ["___ greet() {", "  console.log('Hi');", "}"],
          tiles: ["function", "def", "func", "let"],
          answer: ["function"],
          explanation: "function is the JavaScript keyword for defining a function.",
          consoleOutput: null,
        },
        {
          type: "fill",
          instruction: "Complete the code to start a function",
          codeLines: ["___ add() {", "}"],
          tiles: ["function", "return", "const", "call"],
          answer: "function",
          explanation: "Functions begin with the function keyword here.",
          consoleOutput: null,
        },
        {
          type: "multiple_choice",
          instruction: "What keyword defines a function in JavaScript?",
          options: ["function", "def", "make", "create"],
          answer: "function",
          explanation: "JavaScript uses function, not def.",
        },
        {
          type: "multiple_choice",
          instruction: "What is greet in function greet() {}?",
          options: ["The function name", "A string", "A number", "A loop"],
          answer: "The function name",
          explanation: "greet is the name you use to call the function later.",
        },
      ]
    ),
    "2": lesson(
      {
        title: "Calling Functions",
        explanation: "After you define a function, you run it by calling its name with parentheses. This tells JavaScript to use the code inside the function.",
        example: "function greet() {\n  console.log('Hi');\n}\ngreet();",
        tip: "Parentheses are what actually call the function.",
      },
      [
        {
          type: "arrange",
          instruction: "Fill in the blanks to call greet",
          codeLines: ["function greet() {", "  console.log('Hi');", "}", "___()___"],
          tiles: ["greet", ";", "hello", "call", "return", ":"],
          answer: ["greet", ";"],
          explanation: "greet(); runs the function.",
          consoleOutput: "Hi",
        },
        {
          type: "fill",
          instruction: "Complete the code to call the function",
          codeLines: ["function jump() {", "  console.log('Jump');", "}", "___();"],
          tiles: ["jump", "function", "console.log", "return"],
          answer: "jump",
          explanation: "Use the function name to call it.",
          consoleOutput: "Jump",
        },
        {
          type: "multiple_choice",
          instruction: "How do you call a function named wave?",
          options: ["wave();", "function wave();", "call wave;", "wave;"],
          answer: "wave();",
          explanation: "The name and parentheses call the function.",
        },
        {
          type: "output",
          instruction: "What does this code print?",
          codeLines: ["function sayHi() {", "  console.log('Hi');", "}", "sayHi();"],
          options: ["Hi", "sayHi", "Nothing", "undefined"],
          answer: "Hi",
          explanation: "Calling sayHi() runs the console.log line inside it.",
          consoleOutput: null,
        },
      ]
    ),
    "3": lesson(
      {
        title: "Parameters",
        explanation: "Parameters are inputs a function can use. They let one function work with different values each time it is called.",
        example: "function greet(name) {\n  console.log('Hi', name);\n}\ngreet('Ava');",
        tip: "Parameters go inside the parentheses of the function definition.",
      },
      [
        {
          type: "arrange",
          instruction: "Fill in the blanks to define a function with one parameter",
          codeLines: ["function greet(___) {", "  console.log('Hi', name);", "}"],
          tiles: ["name", "'name'", "console.log", "return"],
          answer: ["name"],
          explanation: "The parameter name receives the value you pass in later.",
          consoleOutput: null,
        },
        {
          type: "fill",
          instruction: "Complete the function call",
          codeLines: ["function greet(name) {", "  console.log('Hi', name);", "}", "greet(___);"],
          tiles: ["'Leo'", "Leo", "name", "true"],
          answer: "'Leo'",
          explanation: "The string 'Leo' is passed into the name parameter.",
          consoleOutput: "Hi Leo",
        },
        {
          type: "multiple_choice",
          instruction: "What is name in function greet(name) {}?",
          options: ["A parameter", "A loop", "A comment", "An array"],
          answer: "A parameter",
          explanation: "Parameters are the input names inside the function definition.",
        },
        {
          type: "output",
          instruction: "What does this code print?",
          codeLines: ["function say(color) {", "  console.log(color);", "}", "say('blue');"],
          options: ["blue", "color", "'blue'", "undefined"],
          answer: "blue",
          explanation: "The value 'blue' gets passed into the parameter.",
          consoleOutput: null,
        },
      ]
    ),
    "4": lesson(
      {
        title: "Return Values",
        explanation: "A function can send a value back with return. This is useful when you want to save or use the result somewhere else.",
        example: "function add(a, b) {\n  return a + b;\n}\nconsole.log(add(2, 3));",
        tip: "return sends the answer back out of the function.",
      },
      [
        {
          type: "arrange",
          instruction: "Fill in the blanks to return a sum",
          codeLines: ["function add(a, b) {", "  ___ a + b;", "}"],
          tiles: ["return", "console.log", "prompt", "let"],
          answer: ["return"],
          explanation: "return sends the result back from the function.",
          consoleOutput: null,
        },
        {
          type: "fill",
          instruction: "Complete the code to return x",
          codeLines: ["function show(x) {", "  ___ x;", "}"],
          tiles: ["return", "print", "prompt", "let"],
          answer: "return",
          explanation: "return gives the value back from the function.",
          consoleOutput: null,
        },
        {
          type: "multiple_choice",
          instruction: "What does return do?",
          options: ["Sends a value back from a function", "Starts a loop", "Creates a variable", "Adds a comment"],
          answer: "Sends a value back from a function",
          explanation: "return is how functions give back a result.",
        },
        {
          type: "output",
          instruction: "What does this code print?",
          codeLines: ["function add(a, b) {", "  return a + b;", "}", "console.log(add(3, 7));"],
          options: ["10", "37", "a + b", "undefined"],
          answer: "10",
          explanation: "The function returns 10, then console.log prints it.",
          consoleOutput: null,
        },
      ]
    ),
  },
  "8": {
    "1": lesson(
      {
        title: "Creating Arrays",
        explanation: "An array stores many values in one place. JavaScript arrays use square brackets and commas between items.",
        example: "const fruits = ['apple', 'banana', 'cherry'];",
        tip: "Use brackets [ ] when making an array.",
      },
      [
        {
          type: "arrange",
          instruction: "Fill in the blanks to create an array",
          codeLines: ["const fruits = [___];"],
          tiles: ["'apple', 'banana'", "'apple'", "'banana'", "{ apple: 'banana' }", "fruit1, fruit2", "true, false"],
          answer: ["'apple', 'banana'"],
          explanation: "Array items go inside square brackets, separated by commas.",
          consoleOutput: null,
        },
        {
          type: "fill",
          instruction: "Complete the code to create an array",
          codeLines: ["const nums = [1, 2, ___];"],
          tiles: ["3", "'3'", "true", "x"],
          answer: "3",
          explanation: "3 is the next value in the array.",
          consoleOutput: null,
        },
        {
          type: "multiple_choice",
          instruction: "Which of these is an array?",
          options: ["['red', 'blue']", "{'red', 'blue'}", "('red', 'blue')", "'red', 'blue'"],
          answer: "['red', 'blue']",
          explanation: "Square brackets are used for arrays.",
        },
        {
          type: "output",
          instruction: "What does this code print?",
          codeLines: ["const fruits = ['apple', 'banana'];", "console.log(fruits.length);"],
          options: ["2", "1", "banana", "undefined"],
          answer: "2",
          explanation: "The array has two items.",
          consoleOutput: null,
        },
      ]
    ),
    "2": lesson(
      {
        title: "Accessing Array Items",
        explanation: "Array items are reached by index. The first item is at index 0, the second is at index 1, and so on.",
        example: "const fruits = ['apple', 'banana'];\nconsole.log(fruits[0]);",
        tip: "Arrays start counting at 0, not 1.",
      },
      [
        {
          type: "arrange",
          instruction: "Fill in the blanks to print the first item",
          codeLines: ["const fruits = ['apple', 'banana'];", "console.log(fruits[___]);"],
          tiles: ["0", "1", "2", "'apple'", "first", "fruit"],
          answer: ["0"],
          explanation: "The first item is always at index 0.",
          consoleOutput: "apple",
        },
        {
          type: "fill",
          instruction: "Complete the code to print banana",
          codeLines: ["const fruits = ['apple', 'banana', 'cherry'];", "console.log(fruits[___]);"],
          tiles: ["1", "0", "2", "3"],
          answer: "1",
          explanation: "banana is the second item, so its index is 1.",
          consoleOutput: "banana",
        },
        {
          type: "multiple_choice",
          instruction: "What index does the first array item use?",
          options: ["0", "1", "2", "-1"],
          answer: "0",
          explanation: "JavaScript arrays start at index 0.",
        },
        {
          type: "output",
          instruction: "What does this code print?",
          codeLines: ["const colors = ['red', 'blue'];", "console.log(colors[1]);"],
          options: ["blue", "red", "1", "undefined"],
          answer: "blue",
          explanation: "Index 1 is the second item in the array.",
          consoleOutput: null,
        },
      ]
    ),
    "3": lesson(
      {
        title: "Adding and Removing Items",
        explanation: "push() adds an item to the end of an array. pop() removes the last item. These are simple ways to change an array.",
        example: "const foods = ['pizza'];\nfoods.push('tacos');\nfoods.pop();",
        tip: "push adds, pop removes.",
      },
      [
        {
          type: "arrange",
          instruction: "Fill in the blanks to add tacos to the array",
          codeLines: ["const foods = ['pizza'];", "foods.push(___);"],
          tiles: ["'tacos'", "'pizza'", "tacos", "1", "pop", "shift"],
          answer: ["'tacos'"],
          explanation: "push adds a new item to the end of the array.",
          consoleOutput: null,
        },
        {
          type: "fill",
          instruction: "Complete the code to remove the last item",
          codeLines: ["const nums = [1, 2, 3];", "nums.___();"],
          tiles: ["pop", "push", "add", "remove"],
          answer: "pop",
          explanation: "pop removes the last item.",
          consoleOutput: null,
        },
        {
          type: "multiple_choice",
          instruction: "Which method adds an item to the end of an array?",
          options: ["push()", "pop()", "shift()", "length()"],
          answer: "push()",
          explanation: "push() adds to the end of the array.",
        },
        {
          type: "output",
          instruction: "What does this code print?",
          codeLines: ["const foods = ['pizza'];", "foods.push('sushi');", "console.log(foods.length);"],
          options: ["2", "1", "sushi", "undefined"],
          answer: "2",
          explanation: "The array ends up with pizza and sushi in it.",
          consoleOutput: null,
        },
      ]
    ),
    "4": lesson(
      {
        title: "Looping Through Arrays",
        explanation: "You can loop through every array item with a for loop. This is useful when you want to do the same thing to each item.",
        example: "const foods = ['pizza', 'sushi'];\nfor (let i = 0; i < foods.length; i++) {\n  console.log(foods[i]);\n}",
        tip: "Use foods.length so the loop knows when to stop.",
      },
      [
        {
          type: "arrange",
          instruction: "Fill in the blanks to loop through an array",
          codeLines: ["const foods = ['pizza', 'sushi'];", "for (let i = 0; i < foods.length; i++) {", "  console.log(foods[___]);", "}"],
          tiles: ["i", "0", "foods", "length"],
          answer: ["i"],
          explanation: "foods[i] gives the current item in the loop.",
          consoleOutput: "pizza\nsushi",
        },
        {
          type: "fill",
          instruction: "Complete the loop condition",
          codeLines: ["for (let i = 0; i < foods.___; i++) {", "  console.log(foods[i]);", "}"],
          tiles: ["length", "size", "count", "end"],
          answer: "length",
          explanation: "length tells the loop how many items are in the array.",
          consoleOutput: null,
        },
        {
          type: "multiple_choice",
          instruction: "What does foods[i] mean in a loop?",
          options: ["The current array item", "The whole array", "The loop count only", "A new variable"],
          answer: "The current array item",
          explanation: "i points to the current position in the array.",
        },
        {
          type: "output",
          instruction: "What does this code print first?",
          codeLines: ["const foods = ['pizza', 'sushi'];", "for (let i = 0; i < foods.length; i++) {", "  console.log(foods[i]);", "}"],
          options: ["pizza", "sushi", "0", "foods"],
          answer: "pizza",
          explanation: "The loop starts with i = 0, which is the first item.",
          consoleOutput: null,
        },
      ]
    ),
  },
  "9": {
    "1": lesson(
      {
        title: "Creating Objects",
        explanation: "An object stores data with keys and values. This is helpful when different pieces of information belong together.",
        example: "const person = { name: 'Ava', age: 12 };",
        tip: "Objects use curly braces { }.",
      },
      [
        {
          type: "arrange",
          instruction: "Fill in the blanks to create an object",
          codeLines: ["const person = ___ name: 'Ava', age: 12 ___;"],
          tiles: ["{", "}", "[", "]", "(", ")"],
          answer: ["{", "}"],
          explanation: "Objects use curly braces in JavaScript.",
          consoleOutput: null,
        },
        {
          type: "fill",
          instruction: "Complete the object key-value pair",
          codeLines: ["const pet = {", "  name: ___", "};"],
          tiles: ["'Rex'", "Rex", "true", "name"],
          answer: "'Rex'",
          explanation: "'Rex' is the string value for the name key.",
          consoleOutput: null,
        },
        {
          type: "multiple_choice",
          instruction: "Which of these is an object?",
          options: ["{ name: 'Ava' }", "['Ava']", "('Ava')", "'Ava'"],
          answer: "{ name: 'Ava' }",
          explanation: "Objects use curly braces with key-value pairs.",
        },
        {
          type: "output",
          instruction: "What does this code print?",
          codeLines: ["const person = { name: 'Ava', age: 12 };", "console.log(person.age);"],
          options: ["12", "Ava", "age", "undefined"],
          answer: "12",
          explanation: "person.age looks up the age value in the object.",
          consoleOutput: null,
        },
      ]
    ),
    "2": lesson(
      {
        title: "Accessing Object Values",
        explanation: "Object values can be read with dot notation or bracket notation. Both are useful, but dot notation is often easiest for beginners.",
        example: "console.log(person.name);\nconsole.log(person['age']);",
        tip: "Dot notation reads nicely: person.name.",
      },
      [
        {
          type: "arrange",
          instruction: "Fill in the blanks to print the name from the object",
          codeLines: ["const person = { name: 'Ava' };", "console.log(person.___)___"],
          tiles: ["name", ";", "age", "['name']", ":"],
          answer: ["name", ";"],
          explanation: "person.name reads the value stored under the name key.",
          consoleOutput: "Ava",
        },
        {
          type: "fill",
          instruction: "Complete the code to print age",
          codeLines: ["const person = { age: 12 };", "console.log(person.___);"],
          tiles: ["age", "name", "12", "key"],
          answer: "age",
          explanation: "age is the key you want to read from the object.",
          consoleOutput: "12",
        },
        {
          type: "multiple_choice",
          instruction: "What does person.name do?",
          options: ["Gets the value stored in the name key", "Creates a loop", "Deletes the object", "Prints every key"],
          answer: "Gets the value stored in the name key",
          explanation: "Dot notation reads a specific value from the object.",
        },
        {
          type: "output",
          instruction: "What does this code print?",
          codeLines: ["const book = { title: 'Pico' };", "console.log(book.title);"],
          options: ["Pico", "title", "book", "undefined"],
          answer: "Pico",
          explanation: "book.title gets the value of the title key.",
          consoleOutput: null,
        },
      ]
    ),
    "3": lesson(
      {
        title: "Adding and Updating Properties",
        explanation: "You can add new object properties or change existing ones with =. This makes objects flexible and easy to update.",
        example: "const person = { name: 'Ava' };\nperson.city = 'Boston';\nperson.name = 'Mia';",
        tip: "Use object.key = value to add or update.",
      },
      [
        {
          type: "arrange",
          instruction: "Fill in the blanks to add a city property",
          codeLines: ["const person = { name: 'Ava' };", "person.city ___ 'Boston'___"],
          tiles: ["=", ";", "==", ":", ","],
          answer: ["=", ";"],
          explanation: "person.city = 'Boston'; adds the new property.",
          consoleOutput: null,
        },
        {
          type: "fill",
          instruction: "Complete the code to update age",
          codeLines: ["const person = { age: 12 };", "person.age = ___;"],
          tiles: ["13", "'13'", "age", "true"],
          answer: "13",
          explanation: "This changes age from 12 to 13.",
          consoleOutput: null,
        },
        {
          type: "multiple_choice",
          instruction: "Which line adds a language property?",
          options: ["person.language = 'JavaScript';", "language.person = 'JavaScript';", "person = language 'JavaScript';", "add person.language;"],
          answer: "person.language = 'JavaScript';",
          explanation: "That is the normal way to add a new property.",
        },
        {
          type: "output",
          instruction: "What does this code print?",
          codeLines: ["const person = { age: 12 };", "person.age = 15;", "console.log(person.age);"],
          options: ["15", "12", "age", "undefined"],
          answer: "15",
          explanation: "The age property gets updated before it is printed.",
          consoleOutput: null,
        },
      ]
    ),
    "4": lesson(
      {
        title: "Looping Through Objects",
        explanation: "You can loop through object keys with for...in. Then you can use each key to look up the matching value.",
        example: "const person = { name: 'Ava', age: 12 };\nfor (const key in person) {\n  console.log(key, person[key]);\n}",
        tip: "person[key] is helpful when the key changes during the loop.",
      },
      [
        {
          type: "arrange",
          instruction: "Fill in the blanks to start a for...in loop",
          codeLines: ["const person = { name: 'Ava' };", "for (const key ___ person) {", "  console.log(key);", "}"],
          tiles: ["in", "of", "on", "="],
          answer: ["in"],
          explanation: "for...in loops through the keys of the object.",
          consoleOutput: "name",
        },
        {
          type: "fill",
          instruction: "Complete the code to get the current value",
          codeLines: ["for (const key in person) {", "  console.log(person[___]);", "}"],
          tiles: ["key", "'key'", "person", "value"],
          answer: "key",
          explanation: "person[key] uses the current key from the loop.",
          consoleOutput: null,
        },
        {
          type: "multiple_choice",
          instruction: "What does for...in loop through on an object?",
          options: ["Its keys", "Its comments", "Its functions only", "Its semicolons"],
          answer: "Its keys",
          explanation: "for...in gives you each object key one at a time.",
        },
        {
          type: "output",
          instruction: "What prints first in this code?",
          codeLines: ["const person = { name: 'Ava', age: 12 };", "for (const key in person) {", "  console.log(key);", "}"],
          options: ["name", "Ava", "age", "12"],
          answer: "name",
          explanation: "The loop starts with the first key in the object here.",
          consoleOutput: null,
        },
      ]
    ),
  },
  "10": {
    "1": lesson(
      {
        title: "Finding Elements",
        explanation: "JavaScript can find elements on a web page. document.querySelector() is a common way to grab one element by a selector.",
        example: "const title = document.querySelector('#title');",
        tip: "Use # for ids and . for classes in selectors.",
      },
      [
        {
          type: "arrange",
          instruction: "Fill in the blanks to find an element with id title",
          codeLines: ["const title = document.___(___)___"],
          tiles: ["querySelector", "'#title'", ";", "get", "return", "prompt"],
          answer: ["querySelector", "'#title'", ";"],
          explanation: "document.querySelector('#title'); finds the element with that id.",
          consoleOutput: null,
        },
        {
          type: "fill",
          instruction: "Complete the selector for an element with id box",
          codeLines: ["const box = document.querySelector(___);"],
          tiles: ["'#box'", "'box'", ".box", "box"],
          answer: "'#box'",
          explanation: "An id selector uses # before the id name.",
          consoleOutput: null,
        },
        {
          type: "multiple_choice",
          instruction: "What does document.querySelector() do?",
          options: ["Finds an element on the page", "Creates a new page", "Deletes the DOM", "Prints the whole website"],
          answer: "Finds an element on the page",
          explanation: "querySelector returns a matching element from the page.",
        },
        {
          type: "multiple_choice",
          instruction: "Which selector targets an element with id title?",
          options: ["#title", ".title", "title()", "id.title"],
          answer: "#title",
          explanation: "#title is the correct CSS selector for an id.",
        },
      ]
    ),
    "2": lesson(
      {
        title: "Changing Text",
        explanation: "Once you have an element, you can change its text with textContent. This is a simple way to update what the user sees.",
        example: "const msg = document.querySelector('#msg');\nmsg.textContent = 'Hello';",
        tip: "textContent changes the text inside the element.",
      },
      [
        {
          type: "arrange",
          instruction: "Fill in the blanks to change an element's text",
          codeLines: ["const msg = document.querySelector('#msg');", "msg.___ = ___;"],
          tiles: ["textContent", "'Hello'", "innerStyle", "true", "length", "return"],
          answer: ["textContent", "'Hello'"],
          explanation: "textContent is the property used to change text.",
          consoleOutput: null,
        },
        {
          type: "fill",
          instruction: "Complete the property name",
          codeLines: ["title.___ = 'New title';"],
          tiles: ["textContent", "color", "innerHTML()", "querySelector"],
          answer: "textContent",
          explanation: "textContent changes the displayed text.",
          consoleOutput: null,
        },
        {
          type: "multiple_choice",
          instruction: "Which property changes the text inside an element?",
          options: ["textContent", "color", "length", "valueOf"],
          answer: "textContent",
          explanation: "textContent updates the text shown in the element.",
        },
        {
          type: "multiple_choice",
          instruction: "What does msg.textContent = 'Hi'; do?",
          options: ["Changes the element text to Hi", "Creates a loop", "Deletes the element", "Prints Hi to the console"],
          answer: "Changes the element text to Hi",
          explanation: "It updates the text inside the selected element.",
        },
      ]
    ),
    "3": lesson(
      {
        title: "Changing Styles",
        explanation: "You can change an element's style with JavaScript. This lets you update things like color, size, or background.",
        example: "const box = document.querySelector('#box');\nbox.style.color = 'blue';",
        tip: "Use element.style.property to change styles.",
      },
      [
        {
          type: "arrange",
          instruction: "Fill in the blanks to change text color to blue",
          codeLines: ["const box = document.querySelector('#box');", "box.style.___ = ___;"],
          tiles: ["color", "'blue'", "text", "42", "font", "return"],
          answer: ["color", "'blue'"],
          explanation: "style.color changes the text color.",
          consoleOutput: null,
        },
        {
          type: "fill",
          instruction: "Complete the style property",
          codeLines: ["title.style.___ = 'red';"],
          tiles: ["color", "length", "textContent", "id"],
          answer: "color",
          explanation: "color is the style property being changed.",
          consoleOutput: null,
        },
        {
          type: "multiple_choice",
          instruction: "How do you change an element's color with JavaScript?",
          options: ["element.style.color = 'blue';", "element.color('blue');", "style.element = 'blue';", "element.textContent = 'blue';"],
          answer: "element.style.color = 'blue';",
          explanation: "That is the correct style syntax.",
        },
        {
          type: "multiple_choice",
          instruction: "What does style.color control?",
          options: ["Text color", "Element id", "Loop count", "Console output"],
          answer: "Text color",
          explanation: "style.color changes how the text color looks on the page.",
        },
      ]
    ),
    "4": lesson(
      {
        title: "Button Clicks",
        explanation: "addEventListener lets JavaScript react to events like clicks. This is how buttons can run code when the user presses them.",
        example: "const btn = document.querySelector('#btn');\nbtn.addEventListener('click', function () {\n  console.log('Clicked');\n});",
        tip: "The word click goes in quotes.",
      },
      [
        {
          type: "arrange",
          instruction: "Fill in the blanks to listen for a click",
          codeLines: ["const btn = document.querySelector('#btn');", "btn.___(___, function () {", "  console.log('Clicked');", "});"],
          tiles: ["addEventListener", "'click'", "querySelector", "'hover'", "style", "textContent"],
          answer: ["addEventListener", "'click'"],
          explanation: "addEventListener('click', ...) runs code when the button is clicked.",
          consoleOutput: null,
        },
        {
          type: "fill",
          instruction: "Complete the event name",
          codeLines: ["btn.addEventListener(___, function () {", "  console.log('Clicked');", "});"],
          tiles: ["'click'", "'blue'", "'button'", "'log'"],
          answer: "'click'",
          explanation: "'click' is the event name for button presses.",
          consoleOutput: null,
        },
        {
          type: "multiple_choice",
          instruction: "What does addEventListener do here?",
          options: ["Runs code when an event happens", "Creates a variable", "Changes array length", "Ends the page"],
          answer: "Runs code when an event happens",
          explanation: "It listens for an event like a click and then runs code.",
        },
        {
          type: "multiple_choice",
          instruction: "Which event name is used for a mouse click?",
          options: ["'click'", "'press'", "'tap'", "'run'"],
          answer: "'click'",
          explanation: "click is the standard event name here.",
        },
      ]
    ),
  },
  "11": {
    "1": lesson(
      {
        title: "Defining Classes",
        explanation: "A class is a blueprint for making objects. It helps you group related data and behavior together.",
        example: "class Dog {\n}\n",
        tip: "class names usually start with a capital letter.",
      },
      [
        {
          type: "arrange",
          instruction: "Fill in the blanks to define a class",
          codeLines: ["___ Dog {", "}"],
          tiles: ["class", "function", "const", "object"],
          answer: ["class"],
          explanation: "class is the keyword used to define a class in JavaScript.",
          consoleOutput: null,
        },
        {
          type: "fill",
          instruction: "Complete the keyword",
          codeLines: ["___ Car {", "}"],
          tiles: ["class", "function", "let", "return"],
          answer: "class",
          explanation: "JavaScript classes start with the class keyword.",
          consoleOutput: null,
        },
        {
          type: "multiple_choice",
          instruction: "What is a class?",
          options: ["A blueprint for objects", "A loop", "A string method", "A comment"],
          answer: "A blueprint for objects",
          explanation: "Classes help create many similar objects.",
        },
        {
          type: "multiple_choice",
          instruction: "Which line starts a class named Cat?",
          options: ["class Cat {", "function Cat {", "const Cat {", "Cat class {"],
          answer: "class Cat {",
          explanation: "That is the correct JavaScript class syntax.",
        },
      ]
    ),
    "2": lesson(
      {
        title: "The constructor",
        explanation: "constructor runs when a new object is made from a class. It is where you set up the starting values.",
        example: "class Dog {\n  constructor(name) {\n    this.name = name;\n  }\n}",
        tip: "constructor is a special method name.",
      },
      [
        {
          type: "arrange",
          instruction: "Fill in the blanks to start a constructor",
          codeLines: ["class Dog {", "  ___(name) {", "    this.name = name;", "  }", "}"],
          tiles: ["constructor", "function", "return", "create"],
          answer: ["constructor"],
          explanation: "constructor sets up the new object when it is created.",
          consoleOutput: null,
        },
        {
          type: "fill",
          instruction: "Complete the special method name",
          codeLines: ["class Cat {", "  ___(name) {", "    this.name = name;", "  }", "}"],
          tiles: ["constructor", "function", "class", "method"],
          answer: "constructor",
          explanation: "constructor is the method that runs on creation.",
          consoleOutput: null,
        },
        {
          type: "multiple_choice",
          instruction: "What does constructor do?",
          options: ["Sets up a new object", "Deletes a class", "Prints a comment", "Starts a loop"],
          answer: "Sets up a new object",
          explanation: "constructor gives the new object its starting values.",
        },
        {
          type: "multiple_choice",
          instruction: "Where do you usually put starting values in a class?",
          options: ["Inside constructor", "Inside console.log", "Inside an array", "Inside a comment"],
          answer: "Inside constructor",
          explanation: "constructor is where setup usually happens.",
        },
      ]
    ),
    "3": lesson(
      {
        title: "Properties",
        explanation: "Properties are values stored on an object. Inside a class, this.propertyName is how you save them.",
        example: "class Dog {\n  constructor(name) {\n    this.name = name;\n  }\n}",
        tip: "this means the current object being created or used.",
      },
      [
        {
          type: "arrange",
          instruction: "Fill in the blanks to store name on the object",
          codeLines: ["class Dog {", "  constructor(name) {", "    ___.name = name;", "  }", "}"],
          tiles: ["this", "class", "Dog", "return"],
          answer: ["this"],
          explanation: "this.name stores the value on the object itself.",
          consoleOutput: null,
        },
        {
          type: "fill",
          instruction: "Complete the code to store age",
          codeLines: ["constructor(age) {", "  ___.age = age;", "}"],
          tiles: ["this", "age", "const", "class"],
          answer: "this",
          explanation: "this.age saves the value as a property of the object.",
          consoleOutput: null,
        },
        {
          type: "multiple_choice",
          instruction: "What does this.name = name do?",
          options: ["Stores the value in a property", "Prints the value", "Deletes the object", "Starts a loop"],
          answer: "Stores the value in a property",
          explanation: "It saves the incoming value onto the object.",
        },
        {
          type: "multiple_choice",
          instruction: "What does this mean in a class?",
          options: ["The current object", "A string", "The next function", "The console"],
          answer: "The current object",
          explanation: "this refers to the object being worked with.",
        },
      ]
    ),
    "4": lesson(
      {
        title: "Methods",
        explanation: "Methods are functions that belong to a class. They describe actions an object can perform.",
        example: "class Dog {\n  bark() {\n    console.log('Woof');\n  }\n}",
        tip: "Methods go inside the class body.",
      },
      [
        {
          type: "arrange",
          instruction: "Fill in the blanks to create a bark method",
          codeLines: ["class Dog {", "  bark() {", "    console.log('Woof')___", "  }", "}"],
          tiles: [";", ".", ":", ",", "()", "return"],
          answer: [";"],
          explanation: "The console.log line ends with a semicolon.",
          consoleOutput: "Woof",
        },
        {
          type: "fill",
          instruction: "Complete the method body",
          codeLines: ["class Dog {", "  bark() {", "    ___('Woof');", "  }", "}"],
          tiles: ["console.log", "prompt", "return", "class"],
          answer: "console.log",
          explanation: "console.log prints Woof from the method.",
          consoleOutput: "Woof",
        },
        {
          type: "multiple_choice",
          instruction: "What is a method?",
          options: ["A function inside a class", "A loop", "A string", "A comment"],
          answer: "A function inside a class",
          explanation: "Methods are the actions defined on a class.",
        },
        {
          type: "multiple_choice",
          instruction: "Which line is a class method?",
          options: ["bark() { }", "function bark { }", "let bark = {}", "bark => {}"],
          answer: "bark() { }",
          explanation: "That is the normal method syntax inside a class.",
        },
      ]
    ),
  },
  "12": {
    "1": lesson(
      {
        title: "Planning a Project",
        explanation: "Before you build something, it helps to plan the steps. A good plan makes the coding easier and keeps you from feeling lost.",
        example: "1. Pick the goal\n2. Break it into small tasks\n3. Build one piece at a time",
        tip: "Small steps make big projects feel simpler.",
      },
      [
        {
          type: "multiple_choice",
          instruction: "Why plan a project before coding?",
          options: ["To break the work into smaller steps", "To make the code run slower", "To avoid using variables", "To remove all bugs instantly"],
          answer: "To break the work into smaller steps",
          explanation: "Planning gives you a clear path to follow.",
        },
        {
          type: "multiple_choice",
          instruction: "What is a good first project step?",
          options: ["Decide what you want to build", "Delete your code", "Skip testing", "Use random features"],
          answer: "Decide what you want to build",
          explanation: "You need a clear goal before you start building.",
        },
        {
          type: "fill",
          instruction: "Complete the planning idea",
          codeLines: ["Break the project into small ___."],
          tiles: ["steps", "bugs", "loops", "quotes"],
          answer: "steps",
          explanation: "Small steps make projects easier to build.",
          consoleOutput: null,
        },
        {
          type: "multiple_choice",
          instruction: "What helps a beginner most on a project?",
          options: ["Building one small piece at a time", "Writing everything at once", "Ignoring mistakes", "Skipping practice"],
          answer: "Building one small piece at a time",
          explanation: "Small pieces are easier to understand and test.",
        },
      ]
    ),
    "2": lesson(
      {
        title: "Building the Structure",
        explanation: "Project structure means setting up the main pieces first. You might start with variables, functions, and the basic page elements you need.",
        example: "const contacts = {};\nfunction addContact(name, phone) {\n  contacts[name] = phone;\n}",
        tip: "Build the skeleton first, then add the details.",
      },
      [
        {
          type: "multiple_choice",
          instruction: "What does structure mean in a project?",
          options: ["The main pieces that hold the project together", "Only the final colors", "Only comments", "Only console logs"],
          answer: "The main pieces that hold the project together",
          explanation: "Structure is the base your project is built on.",
        },
        {
          type: "multiple_choice",
          instruction: "What is a good way to start a contact book app?",
          options: ["Create the data and main functions first", "Add random animations first", "Skip the data", "Delete the inputs"],
          answer: "Create the data and main functions first",
          explanation: "Start with the core pieces that make the app work.",
        },
        {
          type: "fill",
          instruction: "Complete the sentence",
          codeLines: ["Build the ___ of the project first."],
          tiles: ["structure", "bugs", "errors", "loops"],
          answer: "structure",
          explanation: "The structure is the base that everything else fits into.",
          consoleOutput: null,
        },
        {
          type: "multiple_choice",
          instruction: "Why build the skeleton first?",
          options: ["So later features have something to attach to", "So the app has more bugs", "So variables stop working", "So testing is impossible"],
          answer: "So later features have something to attach to",
          explanation: "A solid base makes the rest much easier.",
        },
      ]
    ),
    "3": lesson(
      {
        title: "Adding Features",
        explanation: "After the basic structure works, you can add features one by one. This keeps each change small and easy to test.",
        example: "Add a button.\nThen add a click handler.\nThen show the result on the page.",
        tip: "Add one feature at a time so you always know what changed.",
      },
      [
        {
          type: "multiple_choice",
          instruction: "What is a good way to add features?",
          options: ["One at a time", "All at once with no testing", "Only after deleting old code", "By guessing"],
          answer: "One at a time",
          explanation: "Small changes are easier to understand and fix.",
        },
        {
          type: "multiple_choice",
          instruction: "Why test after each feature?",
          options: ["So you catch problems early", "So bugs hide longer", "So the app stops loading", "So variables disappear"],
          answer: "So you catch problems early",
          explanation: "Testing often helps you spot issues right away.",
        },
        {
          type: "fill",
          instruction: "Complete the advice",
          codeLines: ["Add one ___ at a time."],
          tiles: ["feature", "error", "comment", "quote"],
          answer: "feature",
          explanation: "One feature at a time keeps the project manageable.",
          consoleOutput: null,
        },
        {
          type: "multiple_choice",
          instruction: "What is safer for a beginner project?",
          options: ["Small changes with testing", "Huge changes all at once", "Never checking results", "Skipping features completely"],
          answer: "Small changes with testing",
          explanation: "That makes problems easier to find and fix.",
        },
      ]
    ),
    "4": lesson(
      {
        title: "Testing and Fixing",
        explanation: "Testing helps you see if your project works the way you expect. When something breaks, fix one problem at a time and check again.",
        example: "console.log(value);\n// Check what the code is really doing",
        tip: "Simple console.log checks can help you find bugs fast.",
      },
      [
        {
          type: "multiple_choice",
          instruction: "Why test your project often?",
          options: ["To find problems early", "To remove all variables", "To stop the browser", "To avoid writing code"],
          answer: "To find problems early",
          explanation: "Frequent testing helps you catch bugs sooner.",
        },
        {
          type: "multiple_choice",
          instruction: "What is a smart way to fix bugs?",
          options: ["Fix one problem at a time", "Change everything at once", "Ignore the bug", "Delete the project"],
          answer: "Fix one problem at a time",
          explanation: "That keeps debugging simple and clear.",
        },
        {
          type: "fill",
          instruction: "Complete the debugging tool",
          codeLines: ["Use console.___() to inspect values."],
          tiles: ["log", "prompt", "style", "querySelector"],
          answer: "log",
          explanation: "console.log is a great beginner debugging tool.",
          consoleOutput: null,
        },
        {
          type: "multiple_choice",
          instruction: "What can console.log help you do?",
          options: ["See what values your code has", "Create HTML automatically", "Remove all bugs instantly", "Turn strings into arrays"],
          answer: "See what values your code has",
          explanation: "console.log helps you inspect what the program is doing.",
        },
      ]
    ),
  },
};
