import type { LessonArcQuestion } from "@/lib/lessonArc/types";

const CONCEPT = "python-for-loops";

type SeedQuestion = Omit<LessonArcQuestion, "concept">;

function question(definition: SeedQuestion): LessonArcQuestion {
  return {
    ...definition,
    concept: CONCEPT,
  };
}

export const PYTHON_FOR_LOOPS_SEED: LessonArcQuestion[] = [
  question({
    id: "pfl-mc-concept-1",
    type: "mc_concept",
    difficulty: 1,
    prompt: "What does `range(5)` mean in a Python `for` loop?",
    options: [
      "It gives the values 0, 1, 2, 3, 4",
      "It gives the values 1, 2, 3, 4, 5",
      "It repeats the loop forever",
      "It creates a list with only the number 5",
    ],
    correctIndex: 0,
    explanation: "`range(5)` starts at 0 and stops before 5, so the loop sees 0 through 4.",
  }),
  question({
    id: "pfl-mc-concept-2",
    type: "mc_concept",
    difficulty: 1,
    prompt: "Why would you use a `for` loop?",
    options: [
      "To repeat a block of code for each item or number",
      "To turn text into a number",
      "To define a function",
      "To create a comment",
    ],
    correctIndex: 0,
    explanation: "A `for` loop is for repetition. It helps you avoid writing the same code again and again.",
  }),
  question({
    id: "pfl-mc-concept-3",
    type: "mc_concept",
    difficulty: 1,
    prompt: "In `for fruit in fruits:`, what is `fruit`?",
    options: [
      "The variable that holds one item from the list on each loop",
      "The whole list every time",
      "A built-in Python keyword",
      "A comment label",
    ],
    correctIndex: 0,
    explanation: "`fruit` is the loop variable. It changes to the next item each time the loop runs.",
  }),
  question({
    id: "pfl-mc-concept-4",
    type: "mc_concept",
    difficulty: 1,
    prompt: "What must come at the end of a Python `for` loop header?",
    options: [":", ";", "=", ","],
    correctIndex: 0,
    explanation: "Python uses a colon to start the indented block that belongs to the loop.",
  }),
  question({
    id: "pfl-mc-concept-5",
    type: "mc_concept",
    difficulty: 1,
    prompt: "What is true about the code inside a `for` loop?",
    options: [
      "It must be indented under the `for` line",
      "It must be inside parentheses",
      "It runs only once",
      "It cannot use variables",
    ],
    correctIndex: 0,
    explanation: "Indentation tells Python which lines belong to the loop body.",
  }),
  question({
    id: "pfl-mc-output-1",
    type: "predict-output",
    difficulty: 2,
    prompt: "What does this print?",
    code: "for i in range(3):\n    print(i)",
    options: ["0\n1\n2", "1\n2\n3", "0\n1\n2\n3", "3"],
    correctIndex: 0,
    correctAnswer: "0\n1\n2",
    explanation: "`range(3)` gives 0, 1, and 2. The loop prints each value on its own line.",
  }),
  question({
    id: "pfl-mc-output-2",
    type: "mc_output",
    difficulty: 2,
    prompt: "What does this print?",
    code: "for i in range(1, 4):\n    print(i)",
    options: ["1\n2\n3", "0\n1\n2", "1\n2\n3\n4", "4"],
    correctIndex: 0,
    correctAnswer: "1\n2\n3",
    explanation: "`range(1, 4)` starts at 1 and stops before 4.",
  }),
  question({
    id: "pfl-mc-output-3",
    type: "mc_output",
    difficulty: 2,
    prompt: "What does this print?",
    code: "letters = ['a', 'b']\nfor letter in letters:\n    print(letter)",
    options: ["a\nb", "letters", "['a', 'b']", "b\na"],
    correctIndex: 0,
    correctAnswer: "a\nb",
    explanation: "The loop visits each item in the list in order and prints it.",
  }),
  question({
    id: "pfl-mc-output-4",
    type: "output-with-animation",
    difficulty: 2,
    prompt: "What does this print?",
    code: "for ch in 'hi':\n    print(ch)",
    options: ["h\ni", "hi", "h i", "'h'\n'i'"],
    correctIndex: 0,
    correctAnswer: "h\ni",
    explanation: "Strings can be looped over too. Each character is handled one at a time.",
  }),
  question({
    id: "pfl-mc-output-5",
    type: "mc_output",
    difficulty: 2,
    prompt: "What does this print?",
    code: "total = 0\nfor i in range(3):\n    total = total + i\nprint(total)",
    options: ["3", "6", "2", "0"],
    correctIndex: 0,
    correctAnswer: "3",
    explanation: "The loop adds 0, then 1, then 2. The total becomes 3.",
  }),
  question({
    id: "pfl-word-bank-1",
    type: "fill-only-keywords",
    difficulty: 3,
    prompt: "Build a loop header that goes through the numbers 0, 1, and 2.",
    tokens: ["for", "i", "in", "range", "(", "3", ")", ":", "print", "="],
    correctTokens: ["for", "i", "in", "range", "(", "3", ")", ":"],
    correctAnswer: "for i in range(3):",
    explanation: "A Python loop header needs `for`, a loop variable, `in`, `range(...)`, and a colon.",
  }),
  question({
    id: "pfl-word-bank-2",
    type: "word_bank",
    difficulty: 3,
    prompt: "Build a one-line loop that prints each item in `items`.",
    tokens: ["for", "item", "in", "items", ":", "print", "(", ")", "range", "="],
    correctTokens: ["for", "item", "in", "items", ":", "print", "(", "item", ")"],
    correctAnswer: "for item in items: print(item)",
    explanation: "The loop variable is `item`, and the body uses `print(item)`.",
  }),
  question({
    id: "pfl-word-bank-3",
    type: "word_bank",
    difficulty: 3,
    prompt: "Build a loop header that starts at 1 and stops before 5.",
    tokens: ["for", "n", "in", "range", "(", "1", ",", "5", ")", ":", "while", "6"],
    correctTokens: ["for", "n", "in", "range", "(", "1", ",", "5", ")", ":"],
    correctAnswer: "for n in range(1, 5):",
    explanation: "When you need a start and stop, put both numbers inside `range`.",
  }),
  question({
    id: "pfl-word-bank-4",
    type: "word_bank",
    difficulty: 3,
    prompt: "Build a one-line loop that prints each character in `word`.",
    tokens: ["for", "letter", "in", "word", ":", "print", "(", ")", "letters", "range"],
    correctTokens: ["for", "letter", "in", "word", ":", "print", "(", "letter", ")"],
    correctAnswer: "for letter in word: print(letter)",
    explanation: "The variable `letter` takes one character at a time from `word`.",
  }),
  question({
    id: "pfl-word-bank-5",
    type: "code-translation",
    difficulty: 3,
    prompt: "Build a loop that prints the numbers 2, 3, and 4.",
    tokens: ["for", "i", "in", "range", "(", "2", ",", "5", ")", ":", "print", "(", ")"],
    correctTokens: ["for", "i", "in", "range", "(", "2", ",", "5", ")", ":", "print", "(", "i", ")"],
    correctAnswer: "for i in range(2, 5): print(i)",
    explanation: "`range(2, 5)` gives 2, 3, and 4, and the loop prints each value.",
  }),
  question({
    id: "pfl-arrange-1",
    type: "timeline-execution",
    difficulty: 3,
    prompt: "Arrange the lines to print 0, 1, and 2.",
    lines: ["for i in range(3):", "    print(i)"],
    correctOrder: [0, 1],
    explanation: "The loop header must come first, then the indented line that runs inside it.",
  }),
  question({
    id: "pfl-arrange-2",
    type: "arrange",
    difficulty: 3,
    prompt: "Arrange the lines to print each fruit in the list.",
    lines: ["fruits = ['apple', 'banana']", "for fruit in fruits:", "    print(fruit)"],
    correctOrder: [0, 1, 2],
    explanation: "First create the list, then loop over it, then print each item inside the loop.",
  }),
  question({
    id: "pfl-arrange-3",
    type: "drag-to-build-function",
    difficulty: 3,
    prompt: "Arrange the lines to add 0, 1, and 2 into `total` and print the result.",
    lines: ["total = 0", "for i in range(3):", "    total = total + i", "print(total)"],
    correctOrder: [0, 1, 2, 3],
    explanation: "Start the total first, update it in the loop, and print after the loop finishes.",
  }),
  question({
    id: "pfl-arrange-4",
    type: "arrange",
    difficulty: 3,
    prompt: "Arrange the lines to print each character in `word`.",
    lines: ["word = 'cat'", "for letter in word:", "    print(letter)"],
    correctOrder: [0, 1, 2],
    explanation: "The string must exist before the loop can read each character from it.",
  }),
  question({
    id: "pfl-arrange-5",
    type: "function-call-flow",
    difficulty: 3,
    prompt: "Arrange the lines to define and call a function that prints numbers 0 and 1.",
    lines: ["def show_numbers():", "    for i in range(2):", "        print(i)", "show_numbers()"],
    correctOrder: [0, 1, 2, 3],
    explanation: "Define the function first, keep the loop inside it, then call the function at the end.",
  }),
  question({
    id: "pfl-fill-type-1",
    type: "fill-the-blank-classic",
    difficulty: 4,
    prompt: "Type the missing token.",
    code: "for i in ________(3):\n    print(i)",
    correctAnswer: "range",
    explanation: "`range` creates the sequence of numbers the loop will step through.",
    hint: "It is the built-in function most Python `for` loops use with numbers.",
  }),
  question({
    id: "pfl-fill-type-2",
    type: "fill_type",
    difficulty: 4,
    prompt: "Type the missing token.",
    code: "for item ________ items:\n    print(item)",
    correctAnswer: "in",
    explanation: "Python uses `in` to say where the loop variable gets its values from.",
    hint: "The loop variable is taken from a collection ___ items.",
  }),
  question({
    id: "pfl-fill-type-3",
    type: "fill_type",
    difficulty: 4,
    prompt: "Type the missing token.",
    code: "for n in range(1, 4)______\n    print(n)",
    correctAnswer: ":",
    explanation: "A colon starts the loop body in Python.",
    hint: "Every Python loop header ends with the same single character.",
  }),
  question({
    id: "pfl-fill-type-4",
    type: "fill-only-operators",
    difficulty: 4,
    prompt: "Type the missing token.",
    code: "word = 'go'\nfor letter in word:\n    print(________)",
    correctAnswer: "letter",
    explanation: "The loop variable `letter` already holds each character from the string.",
    hint: "Use the same variable name that appears after `for`.",
  }),
  question({
    id: "pfl-fill-type-5",
    type: "fill_type",
    difficulty: 4,
    prompt: "Type the missing token.",
    code: "total = 0\nfor n in range(4):\n    total = total + ________",
    correctAnswer: "n",
    explanation: "To add each number from the loop, use the loop variable `n`.",
    hint: "Use the value currently coming from `range(4)`.",
  }),
  question({
    id: "pfl-fill-select-1",
    type: "fill_select",
    difficulty: 1,
    prompt: "Choose the missing token.",
    code: "for i in ________(5):\n    print(i)",
    options: ["range", "print", "input", "len"],
    correctIndex: 0,
    correctAnswer: "range",
    explanation: "`range` gives the numbers the loop should use.",
  }),
  question({
    id: "pfl-fill-select-2",
    type: "fill_select",
    difficulty: 1,
    prompt: "Choose the missing token.",
    code: "for color ________ colors:\n    print(color)",
    options: ["in", "=", "to", "with"],
    correctIndex: 0,
    correctAnswer: "in",
    explanation: "The keyword `in` connects the loop variable to the collection.",
  }),
  question({
    id: "pfl-fill-select-3",
    type: "fill_select",
    difficulty: 1,
    prompt: "Choose the missing token.",
    code: "for i in range(3)________\n    print(i)",
    options: [":", ";", ",", "="],
    correctIndex: 0,
    correctAnswer: ":",
    explanation: "The colon marks the start of the loop body.",
  }),
  question({
    id: "pfl-fill-select-4",
    type: "fill_select",
    difficulty: 1,
    prompt: "Choose the missing token.",
    code: "items = ['pen', 'book']\nfor ________ in items:\n    print(item)",
    options: ["item", "range", "print", "items"],
    correctIndex: 0,
    correctAnswer: "item",
    explanation: "You need a loop variable name to represent one item at a time.",
  }),
  question({
    id: "pfl-fill-select-5",
    type: "fill_select",
    difficulty: 1,
    prompt: "Choose the missing token.",
    code: "for i in range(1, ________):\n    print(i)",
    options: ["4", "3", "1", "0"],
    correctIndex: 0,
    correctAnswer: "4",
    explanation: "To print 1, 2, and 3, the stop value must be 4 because `range` stops before it.",
  }),
  question({
    id: "pfl-spot-bug-1",
    type: "glitch-fix",
    difficulty: 4,
    prompt: "Which version has the bug?",
    code: "### Version A\nfor i in range(3):\n    print(i)\n\n### Version B\nfor i in range(3)\n    print(i)",
    options: ["Version A", "Version B"],
    correctIndex: 1,
    correctAnswer: "Version B",
    bugLine: 1,
    explanation: "Version B is missing the colon at the end of the `for` line.",
    hint: "Check the punctuation at the end of the loop header.",
    xpBonus: 2,
  }),
  question({
    id: "pfl-spot-bug-2",
    type: "spot_bug",
    difficulty: 4,
    prompt: "Which version has the bug?",
    code: "### Version A\nfruits = ['apple', 'pear']\nfor fruit in fruits:\n    print(fruit)\n\n### Version B\nfruits = ['apple', 'pear']\nfor fruit in fruits:\n    print(fruits)",
    options: ["Version A", "Version B"],
    correctIndex: 1,
    correctAnswer: "Version B",
    bugLine: 2,
    explanation: "Version B prints the whole list each time instead of the current `fruit` item.",
    hint: "Look at which variable is printed inside the loop.",
    xpBonus: 2,
  }),
  question({
    id: "pfl-spot-bug-3",
    type: "off-by-one-maze",
    difficulty: 4,
    prompt: "Which version has the bug?",
    code: "### Version A\nfor n in range(1, 4):\n    print(n)\n\n### Version B\nfor n in range(1, 3):\n    print(n)",
    options: ["Version A", "Version B"],
    correctIndex: 1,
    correctAnswer: "Version B",
    bugLine: 1,
    explanation: "Version B stops too early. `range(1, 3)` prints only 1 and 2.",
    hint: "Compare which stop value includes 3 in the output.",
    xpBonus: 2,
  }),
  question({
    id: "pfl-spot-bug-4",
    type: "invisible-bug",
    difficulty: 5,
    prompt: "Which version has the bug?",
    code: "### Version A\nword = 'go'\nfor letter in word:\n    print(letter)\n\n### Version B\nword = 'go'\nfor letter in word:\nprint(letter)",
    options: ["Version A", "Version B"],
    correctIndex: 1,
    correctAnswer: "Version B",
    bugLine: 2,
    explanation: "Version B is missing indentation for the line inside the loop.",
    hint: "The loop body should sit under the `for` line.",
    xpBonus: 2,
  }),
  question({
    id: "pfl-spot-bug-5",
    type: "spot_bug",
    difficulty: 5,
    prompt: "Which version has the bug?",
    code: "### Version A\ntotal = 0\nfor i in range(4):\n    total = total + i\nprint(total)\n\n### Version B\ntotal = 0\nfor i in range(4):\n    total = total + 1\nprint(total)",
    options: ["Version A", "Version B"],
    correctIndex: 1,
    correctAnswer: "Version B",
    bugLine: 2,
    explanation: "Version B adds 1 each time instead of adding the current loop value `i`.",
    hint: "Inside the loop, the calculation should use the loop variable.",
    xpBonus: 2,
  }),
  question({
    id: "pfl-predict-type-1",
    type: "predict_type",
    difficulty: 4,
    prompt: "What will this print? Type your answer exactly.",
    code: "for i in range(2):\n    print(i)",
    correctAnswer: "0\n1",
    explanation: "`range(2)` gives 0 and 1, and `print` writes each on a new line.",
    hint: "Start at 0 and stop before 2.",
    xpBonus: 2,
  }),
  question({
    id: "pfl-predict-type-2",
    type: "predict_type",
    difficulty: 4,
    prompt: "What will this print? Type your answer exactly.",
    code: "for i in range(3, 6):\n    print(i)",
    correctAnswer: "3\n4\n5",
    explanation: "The start is 3 and the stop value 6 is not included.",
    hint: "The final number printed is one less than the stop value.",
    xpBonus: 2,
  }),
  question({
    id: "pfl-predict-type-3",
    type: "predict_type",
    difficulty: 4,
    prompt: "What will this print? Type your answer exactly.",
    code: "word = 'up'\nfor ch in word:\n    print(ch)",
    correctAnswer: "u\np",
    explanation: "The loop visits each character in the string in order.",
    hint: "A string can be looped over character by character.",
    xpBonus: 2,
  }),
  question({
    id: "pfl-predict-type-4",
    type: "predict-final-variable",
    difficulty: 5,
    prompt: "What will this print? Type your answer exactly.",
    code: "total = 0\nfor i in range(1, 4):\n    total = total + i\nprint(total)",
    correctAnswer: "6",
    explanation: "The loop adds 1, then 2, then 3, so the total becomes 6.",
    hint: "Track how `total` changes on each loop step.",
    xpBonus: 2,
  }),
  question({
    id: "pfl-predict-type-5",
    type: "predict_type",
    difficulty: 5,
    prompt: "What will this print? Type your answer exactly.",
    code: "items = ['red', 'blue']\nfor item in items:\n    print(item.upper())",
    correctAnswer: "RED\nBLUE",
    explanation: "Each item is uppercased before being printed.",
    hint: "The loop variable is changed with `.upper()` before output.",
    xpBonus: 2,
  }),
  question({
    id: "pfl-match-pairs-1",
    type: "match_pairs",
    difficulty: 2,
    prompt: "Match each loop snippet to what it does.",
    pairs: [
      { left: "for i in range(3):", right: "Repeats with 0, 1, and 2" },
      { left: "for ch in 'go':", right: "Loops over each character in a string" },
      { left: "for item in items:", right: "Loops over each item in a collection" },
      { left: "range(1, 4)", right: "Produces 1, 2, and 3" },
    ],
    explanation: "Matching the loop shape to its meaning helps you recognize how Python repetition works.",
  }),
  question({
    id: "pfl-match-pairs-2",
    type: "match_pairs",
    difficulty: 2,
    prompt: "Match each snippet to its output.",
    pairs: [
      { left: "for i in range(2): print(i)", right: "0 1" },
      { left: "for i in range(1, 3): print(i)", right: "1 2" },
      { left: "for ch in 'ab': print(ch)", right: "a b" },
      { left: "for n in range(3, 4): print(n)", right: "3" },
    ],
    explanation: "Each loop uses `range` or a string differently, so the printed values change too.",
  }),
  question({
    id: "pfl-match-pairs-3",
    type: "match_pairs",
    difficulty: 2,
    prompt: "Match the loop part to its job.",
    pairs: [
      { left: "for", right: "Starts a loop" },
      { left: "in", right: "Connects the loop variable to the values" },
      { left: "range(5)", right: "Provides a sequence of numbers" },
      { left: ":", right: "Begins the indented loop body" },
    ],
    explanation: "A Python loop header is built from small pieces that each have one job.",
  }),
  question({
    id: "pfl-match-pairs-4",
    type: "match_pairs",
    difficulty: 2,
    prompt: "Match each code example to the best description.",
    pairs: [
      { left: "for i in range(5):", right: "Count through numbers" },
      { left: "for fruit in fruits:", right: "Visit items in a list" },
      { left: "for ch in word:", right: "Visit characters in text" },
      { left: "print(i)", right: "Use the current loop value" },
    ],
    explanation: "Different loop sources change what the variable represents on each repetition.",
  }),
  question({
    id: "pfl-match-pairs-5",
    type: "match_pairs",
    difficulty: 2,
    prompt: "Match each loop goal to the best snippet.",
    pairs: [
      { left: "Print 1, 2, 3", right: "for i in range(1, 4):" },
      { left: "Print each letter in a word", right: "for letter in word:" },
      { left: "Print each list item", right: "for item in items:" },
      { left: "Repeat twice", right: "for i in range(2):" },
    ],
    explanation: "The loop source tells Python what values it should move through.",
  }),
  question({
    id: "pfl-true-false-1",
    type: "true_false",
    difficulty: 1,
    prompt: "True or false: `range(3)` includes the number 3.",
    options: ["True", "False"],
    correctIndex: 1,
    correctAnswer: "False",
    explanation: "`range(3)` stops before 3, so it gives 0, 1, and 2.",
  }),
  question({
    id: "pfl-true-false-2",
    type: "true_false",
    difficulty: 1,
    prompt: "True or false: The code inside a `for` loop should be indented.",
    options: ["True", "False"],
    correctIndex: 0,
    correctAnswer: "True",
    explanation: "Indentation tells Python which lines belong to the loop body.",
  }),
  question({
    id: "pfl-true-false-3",
    type: "true_false",
    difficulty: 1,
    prompt: "True or false: A `for` loop helps you repeat code without rewriting it many times.",
    options: ["True", "False"],
    correctIndex: 0,
    correctAnswer: "True",
    explanation: "That is the main job of a loop: repeating work in a structured way.",
  }),
  question({
    id: "pfl-true-false-4",
    type: "true_false",
    difficulty: 2,
    prompt: "True or false: `for letter in 'cat':` loops over one character at a time.",
    options: ["True", "False"],
    correctIndex: 0,
    correctAnswer: "True",
    explanation: "Strings are iterable, so the loop variable becomes `c`, then `a`, then `t`.",
  }),
  question({
    id: "pfl-true-false-5",
    type: "true_false",
    difficulty: 2,
    prompt: "True or false: `for i in range(2):` runs the loop body three times.",
    options: ["True", "False"],
    correctIndex: 1,
    correctAnswer: "False",
    explanation: "`range(2)` gives only 0 and 1, so the loop body runs twice.",
  }),
  question({
    id: "pfl-complete-fn-1",
    type: "complete_fn",
    difficulty: 5,
    prompt: "Complete the function so it returns a list containing 0, 1, and 2.",
    code: "def first_three():\n    values = []\n    # TODO: add 0, 1, and 2 to values with a loop\n    ______",
    correctAnswer: "for i in range(3):\n        values.append(i)\n    return values",
    testCases: [
      { input: "first_three()", expected: "[0, 1, 2]" },
    ],
    explanation: "Use a loop to append each number, then return the finished list.",
    hint: "Start with `for i in range(3):` and append `i` to `values`.",
    xpBonus: 5,
  }),
  question({
    id: "pfl-complete-fn-2",
    type: "function-completion",
    difficulty: 5,
    prompt: "Complete the function so it returns the sum of 1 through `n`.",
    code: "def sum_up_to(n):\n    total = 0\n    # TODO: loop from 1 through n and add each number to total\n    ______",
    correctAnswer: "for i in range(1, n + 1):\n        total = total + i\n    return total",
    testCases: [
      { input: "sum_up_to(3)", expected: "6" },
      { input: "sum_up_to(5)", expected: "15" },
    ],
    explanation: "Use `range(1, n + 1)` so the loop includes `n`, then return the total.",
    hint: "The stop value in `range` must be one bigger than `n` to include `n`.",
    xpBonus: 5,
  }),
  question({
    id: "pfl-complete-fn-3",
    type: "complete_fn",
    difficulty: 5,
    prompt: "Complete the function so it returns a list of each character in `word`.",
    code: "def letters_in(word):\n    result = []\n    # TODO: use a loop to add each character to result\n    ______",
    correctAnswer: "for ch in word:\n        result.append(ch)\n    return result",
    testCases: [
      { input: "letters_in('go')", expected: "['g', 'o']" },
      { input: "letters_in('a')", expected: "['a']" },
    ],
    explanation: "Loop over the string and append each character to `result`.",
    hint: "A string can be looped over directly: `for ch in word:`.",
    xpBonus: 5,
  }),
  question({
    id: "pfl-complete-fn-4",
    type: "complete_fn",
    difficulty: 5,
    prompt: "Complete the function so it returns a list of even numbers below `limit`.",
    code: "def evens_below(limit):\n    nums = []\n    # TODO: use a loop and keep only even values\n    ______",
    correctAnswer: "for i in range(limit):\n        if i % 2 == 0:\n            nums.append(i)\n    return nums",
    testCases: [
      { input: "evens_below(6)", expected: "[0, 2, 4]" },
      { input: "evens_below(1)", expected: "[0]" },
    ],
    explanation: "The loop should visit each number and append it only when it is even.",
    hint: "Check whether `i % 2 == 0` before appending.",
    xpBonus: 5,
  }),
  question({
    id: "pfl-complete-fn-5",
    type: "complete_fn",
    difficulty: 5,
    prompt: "Complete the function so it returns `word` repeated `times` times.",
    code: "def repeat_word(word, times):\n    result = ''\n    # TODO: add word to result the right number of times\n    ______",
    correctAnswer: "for _ in range(times):\n        result = result + word\n    return result",
    testCases: [
      { input: "repeat_word('ha', 3)", expected: "'hahaha'" },
      { input: "repeat_word('go', 1)", expected: "'go'" },
    ],
    explanation: "Loop the correct number of times, add `word` each time, and return the built string.",
    hint: "Use `for _ in range(times):` when the loop counter itself is not needed.",
    xpBonus: 5,
  }),
  question({
    id: "pfl-debug-1",
    type: "boss-fight",
    difficulty: 5,
    prompt: "This function should return `[0, 1, 2]`, but it does not work. Fix it.",
    code: "def first_three():\n    values = []\n    for i in range(4):\n        values.append(i)\n    return values",
    correctAnswer: "def first_three():\n    values = []\n    for i in range(3):\n        values.append(i)\n    return values",
    testCases: [
      { input: "first_three()", expected: "[0, 1, 2]" },
    ],
    explanation: "The loop runs one extra time. It should stop before 3, not before 4.",
    hint: "Check the stop value in `range`.",
    xpBonus: 5,
  }),
  question({
    id: "pfl-debug-2",
    type: "debug",
    difficulty: 5,
    prompt: "This function should sum the numbers 1 through `n`, but it misses part of the range. Fix it.",
    code: "def sum_up_to(n):\n    total = 0\n    for i in range(1, n):\n        total = total + i\n    return total",
    correctAnswer: "def sum_up_to(n):\n    total = 0\n    for i in range(1, n + 1):\n        total = total + i\n    return total",
    testCases: [
      { input: "sum_up_to(3)", expected: "6" },
      { input: "sum_up_to(5)", expected: "15" },
    ],
    explanation: "The stop value in `range` is excluded, so the loop has to stop at `n + 1`.",
    hint: "The loop should include `n`, not stop just before it.",
    xpBonus: 5,
  }),
  question({
    id: "pfl-debug-3",
    type: "multi-step-debug",
    difficulty: 5,
    prompt: "This function should return each letter in `word`, but it returns too early. Fix it.",
    code: "def letters_in(word):\n    result = []\n    for ch in word:\n        result.append(ch)\n        return result",
    correctAnswer: "def letters_in(word):\n    result = []\n    for ch in word:\n        result.append(ch)\n    return result",
    testCases: [
      { input: "letters_in('go')", expected: "['g', 'o']" },
    ],
    explanation: "The `return` line is inside the loop, so the function exits after the first character.",
    hint: "The final `return` should happen after the loop finishes.",
    xpBonus: 5,
  }),
  question({
    id: "pfl-debug-4",
    type: "debug",
    difficulty: 5,
    prompt: "This function should collect even numbers below `limit`, but it keeps the wrong values. Fix it.",
    code: "def evens_below(limit):\n    nums = []\n    for i in range(limit):\n        if i % 2 == 1:\n            nums.append(i)\n    return nums",
    correctAnswer: "def evens_below(limit):\n    nums = []\n    for i in range(limit):\n        if i % 2 == 0:\n            nums.append(i)\n    return nums",
    testCases: [
      { input: "evens_below(6)", expected: "[0, 2, 4]" },
      { input: "evens_below(3)", expected: "[0, 2]" },
    ],
    explanation: "The condition is checking for odd numbers. It should keep values where the remainder is 0.",
    hint: "Even numbers leave which remainder when divided by 2?",
    xpBonus: 5,
  }),
  question({
    id: "pfl-debug-5",
    type: "glitch-world",
    difficulty: 5,
    prompt: "This function should repeat `word` `times` times, but it changes the wrong variable. Fix it.",
    code: "def repeat_word(word, times):\n    result = ''\n    for _ in range(times):\n        word = result + word\n    return result",
    correctAnswer: "def repeat_word(word, times):\n    result = ''\n    for _ in range(times):\n        result = result + word\n    return result",
    testCases: [
      { input: "repeat_word('ha', 3)", expected: "'hahaha'" },
      { input: "repeat_word('go', 2)", expected: "'gogo'" },
    ],
    explanation: "The loop should keep building `result`, not overwrite `word`.",
    hint: "Which variable is meant to hold the growing answer?",
    xpBonus: 5,
  }),
];
