alter table public.pico_progress
  add column if not exists best_streak integer not null default 0,
  add column if not exists streak_last_activity_date text,
  add column if not exists streak_timezone text,
  add column if not exists streak_activity_dates text not null default '[]',
  add column if not exists streak_protected_dates text not null default '[]',
  add column if not exists streak_freeze_reserved_for_date text,
  add column if not exists streak_freeze_last_consumed_date text,
  add column if not exists streak_protected_pending boolean not null default false,
  add column if not exists streak_protected_streak_value integer not null default 0,
  add column if not exists streak_protected_pending_date text,
  add column if not exists streak_protected_pending_count integer not null default 0,
  add column if not exists streak_pending_milestone integer,
  add column if not exists streak_pending_daily_celebration boolean not null default false,
  add column if not exists streak_pending_daily_celebration_date text,
  add column if not exists streak_pending_daily_streak_value integer not null default 0,
  add column if not exists streak_seen_milestones text not null default '[]',
  add column if not exists streak_lost_pending boolean not null default false,
  add column if not exists streak_lost_value integer not null default 0;
