import type { RobloxCodeConceptSpec, StudioConceptSpec } from "@/lib/robloxCourse/builders";

export const studioLayoutSpec: StudioConceptSpec = {
  concept: "studio-layout",
  title: "Studio layout",
  nodeType: "teaching",
  definition: "Studio layout is the overall Roblox Studio shell with the ribbon, 3D viewport, and docked panels.",
  definitionDistractors: [
    "Studio layout is the panel that only edits a selected object's values.",
    "Studio layout is the library that only browses free models.",
    "Studio layout is the script that runs when the server starts.",
  ],
  scenarios: [
    {
      action: "see the 3D world while building your place",
      distractors: ["Explorer", "Properties", "Toolbox"],
      explanation: "The Studio layout includes the main 3D viewport, which is where you orbit, pan, and inspect the world itself.",
      alternateAction: "orbit around the map and inspect parts in the world",
    },
    {
      action: "switch between Home, Model, View, and Test tabs",
      distractors: ["Explorer", "Output", "Terrain Editor"],
      explanation: "The ribbon across the Studio layout is where major tabs and grouped tool buttons live.",
      alternateAction: "open the Test tab after using the Home tab",
    },
    {
      action: "find grouped tool buttons like Move, Scale, Rotate, and Play",
      distractors: ["Properties", "Explorer", "Asset Manager"],
      explanation: "Those top-level tools are part of the ribbon inside the Studio layout, not the hierarchy or property editors.",
      alternateAction: "click the main build and test tools at the top of Studio",
    },
    {
      action: "reopen a closed panel from the View tab",
      distractors: ["Explorer", "Toolbox", "Script Editor"],
      explanation: "Panel visibility is controlled from the ribbon and View tab inside the overall Studio layout.",
      alternateAction: "bring a hidden panel back into the Studio workspace",
    },
    {
      action: "dock, resize, and rearrange the major Studio panels",
      distractors: ["Properties", "Command Bar", "Explorer"],
      explanation: "Docking and arranging panels is part of working with the Studio layout as a whole.",
      alternateAction: "customize where your panels sit on screen",
    },
    {
      action: "move from building to testing without leaving the same editor window",
      distractors: ["Toolbox", "Properties", "Explorer"],
      explanation: "Studio layout brings build tools, test controls, and the viewport together in one workspace.",
      alternateAction: "go from editing a place to pressing Play in the same workspace",
    },
    {
      action: "keep the viewport in the center and panels around the sides",
      distractors: ["Explorer", "Toolbox", "Properties"],
      explanation: "That overall arrangement is the Studio layout, which combines the viewport with docked side panels.",
      alternateAction: "use the standard Roblox Studio workspace arrangement",
    },
    {
      action: "work with tabs, the viewport, and docked panels as one interface",
      distractors: ["Properties", "Terrain Editor", "Animation Editor"],
      explanation: "Studio layout means the entire editing workspace, not a single panel like Properties or a specialized editor.",
      alternateAction: "navigate the full Studio interface rather than one panel",
    },
  ],
  truths: [
    {
      truth: "The Studio layout includes the ribbon at the top and the 3D viewport in the center.",
      lie: "The Studio layout is only the Properties panel for the selected object.",
      explanation: "Studio layout refers to the whole editing shell, not one narrow panel.",
    },
    {
      truth: "You can move, dock, and resize panels inside the Studio layout.",
      lie: "Panels in the Studio layout are fixed and cannot be rearranged.",
      explanation: "Roblox Studio lets you customize panel positions to match your workflow.",
    },
    {
      truth: "The View tab is part of the main Studio ribbon.",
      lie: "The View tab appears only inside the Explorer panel.",
      explanation: "View is a ribbon tab, not a control embedded inside Explorer.",
    },
    {
      truth: "The 3D viewport is where you look at and manipulate the place itself.",
      lie: "The 3D viewport is where you type service names like Players and TweenService.",
      explanation: "The viewport shows the world. Service access is done in code, not in the viewport.",
    },
    {
      truth: "Home, Model, Test, and View are top-level tabs in the Studio interface.",
      lie: "Home, Model, Test, and View are child objects under Workspace.",
      explanation: "They are interface tabs, not Instances in the game hierarchy.",
    },
    {
      truth: "The Studio layout is built to keep building, scripting, and testing tools close together.",
      lie: "The Studio layout is only for terrain painting and nothing else.",
      explanation: "Terrain is one tool area, but Studio layout covers the full editor workflow.",
    },
    {
      truth: "A missing panel can usually be reopened from the View tab in the Studio layout.",
      lie: "The only way to reopen a panel is to restart Roblox Studio.",
      explanation: "View controls panel visibility, so a restart is usually unnecessary.",
    },
    {
      truth: "The ribbon organizes tools into tabs instead of showing every command in one flat list.",
      lie: "The ribbon is the same thing as the Explorer hierarchy.",
      explanation: "The ribbon is for tool commands, while Explorer is for Instances in the place.",
    },
  ],
};

export const explorerPanelSpec: StudioConceptSpec = {
  concept: "explorer-panel",
  title: "Explorer",
  nodeType: "teaching",
  definition: "Explorer shows the parent-child hierarchy of Instances in your Roblox place.",
  definitionDistractors: [
    "Explorer is the panel that only edits properties like Anchored and Transparency.",
    "Explorer is the library for browsing free models and plugins.",
    "Explorer is the button that publishes your game to Roblox.",
  ],
  scenarios: [
    {
      action: "see whether a Part is inside Workspace or ReplicatedStorage",
      distractors: ["Properties", "Toolbox", "Asset Manager"],
      explanation: "Explorer is the hierarchy view, so it shows where each Instance lives in the place tree.",
      alternateAction: "check an object's parent in the place hierarchy",
    },
    {
      action: "drag a Script under ServerScriptService",
      distractors: ["Properties", "Toolbox", "Output"],
      explanation: "Reparenting objects by dragging them in the hierarchy is a standard Explorer task.",
      alternateAction: "change where an Instance lives in the hierarchy by dragging it",
    },
    {
      action: "rename a Model from Enemy to BossEnemy",
      distractors: ["Properties", "Viewport", "Terrain Editor"],
      explanation: "Explorer lets you rename and organize Instances directly in the tree.",
      alternateAction: "organize object names in the place tree",
    },
    {
      action: "expand StarterGui to inspect the GUI objects inside it",
      distractors: ["Properties", "Toolbox", "Animation Editor"],
      explanation: "Explorer uses expandable hierarchy arrows so you can inspect nested children like GUI objects.",
      alternateAction: "open a container to inspect the children under it",
    },
    {
      action: "select a LocalScript by clicking its name in the hierarchy",
      distractors: ["Properties", "Command Bar", "Material Manager"],
      explanation: "Explorer is often the fastest way to select an Instance when you know where it sits in the hierarchy.",
      alternateAction: "pick a specific Instance from the game tree",
    },
    {
      action: "confirm that a ClickDetector is a child of a Part",
      distractors: ["Properties", "Toolbox", "Output"],
      explanation: "Parent-child relationships are shown directly in Explorer's nested tree.",
      alternateAction: "inspect which object another Instance is nested under",
    },
    {
      action: "move a ScreenGui out of StarterGui into ReplicatedStorage",
      distractors: ["Properties", "Viewport", "Test panel"],
      explanation: "Explorer is used to move Instances between services and containers in the object tree.",
      alternateAction: "reorganize objects between services and folders",
    },
    {
      action: "open Workspace and select one specific Folder inside it",
      distractors: ["Properties", "Toolbox", "Script Editor"],
      explanation: "Explorer is the navigation panel for object containers like Workspace, Players, and StarterGui.",
      alternateAction: "navigate through nested services and folders",
    },
  ],
  truths: [
    {
      truth: "Explorer shows Instances as a hierarchy with parents and children.",
      lie: "Explorer shows only a selected object's numeric properties and nothing else.",
      explanation: "Hierarchy and parenting belong to Explorer. Individual property values belong to Properties.",
    },
    {
      truth: "You can drag Instances in Explorer to change their parent.",
      lie: "Instances can be reparented only by editing Lua code, never in Explorer.",
      explanation: "Lua can change Parent, but manual reparenting in Explorer is also standard Studio workflow.",
    },
    {
      truth: "Clicking an object in Explorer selects that object in Studio.",
      lie: "Clicking an object in Explorer publishes the object to Roblox immediately.",
      explanation: "Explorer is for selection and organization, not publishing.",
    },
    {
      truth: "Explorer can show services like Workspace, ReplicatedStorage, and ServerScriptService.",
      lie: "Explorer hides Roblox services and only shows Parts.",
      explanation: "Services are core top-level nodes in the Explorer tree.",
    },
    {
      truth: "Nested objects can be expanded and collapsed in Explorer.",
      lie: "Explorer cannot reveal children inside folders or models.",
      explanation: "Expanding containers is one of Explorer's main jobs.",
    },
    {
      truth: "Renaming an Instance in Explorer changes its Name property.",
      lie: "Renaming an Instance in Explorer only changes the label visually and not the real object name.",
      explanation: "Explorer edits the actual Name stored on the Instance.",
    },
    {
      truth: "Explorer is useful when you need to find hidden objects that are hard to click in the viewport.",
      lie: "Explorer can be used only for objects that are already visible in the 3D viewport.",
      explanation: "Many Instances are easier to find in the hierarchy than by clicking in the world.",
    },
    {
      truth: "A Part can appear in Explorer even if you are not looking at it in the camera view.",
      lie: "If a Part is off-camera, it disappears from Explorer too.",
      explanation: "Explorer shows the object hierarchy independently from the camera position.",
    },
  ],
};

export const propertiesPanelSpec: StudioConceptSpec = {
  concept: "properties-panel",
  title: "Properties",
  nodeType: "practice",
  definition: "Properties shows the editable values for the currently selected Instance.",
  definitionDistractors: [
    "Properties shows the child hierarchy for every Instance in the place.",
    "Properties is the asset browser for free models, images, and plugins.",
    "Properties is the window that starts multiplayer playtests.",
  ],
  scenarios: [
    {
      action: "change a Part's Anchored checkbox after selecting it",
      distractors: ["Explorer", "Toolbox", "Animation Editor"],
      explanation: "Anchored is a property value, so you edit it in Properties after selecting the Part.",
      alternateAction: "toggle Anchored on the selected object",
    },
    {
      action: "set a Part's Transparency to 0.5",
      distractors: ["Explorer", "Toolbox", "Terrain Editor"],
      explanation: "Transparency is a property field on the selected Part, which makes Properties the right panel.",
      alternateAction: "edit a selected object's numeric property value",
    },
    {
      action: "change a TextLabel's Text property after selecting it",
      distractors: ["Explorer", "Viewport", "Toolbox"],
      explanation: "Text, Color, Size, and many other value fields are edited in Properties.",
      alternateAction: "edit a selected GUI object's value fields",
    },
    {
      action: "search within the selected Instance's available property fields",
      distractors: ["Explorer", "Output", "Script Editor"],
      explanation: "Properties includes a property search box so you can jump to a field quickly.",
      alternateAction: "filter the value list for a selected object",
    },
    {
      action: "set a Part's Material to Neon after selecting it",
      distractors: ["Explorer", "Toolbox", "View tab"],
      explanation: "Material is edited from the selected object's property list in Properties.",
      alternateAction: "change a selected object's material field",
    },
    {
      action: "edit the WalkSpeed of a selected Humanoid",
      distractors: ["Explorer", "Toolbox", "Asset Manager"],
      explanation: "Humanoid values like WalkSpeed are object properties, so you edit them in Properties.",
      alternateAction: "change a selected Humanoid field without writing code",
    },
    {
      action: "inspect whether CanCollide is on or off for the selected Part",
      distractors: ["Explorer", "Viewport", "Toolbox"],
      explanation: "CanCollide is a property value, so Properties is where you inspect or edit it.",
      alternateAction: "read or change the selected object's collision value",
    },
    {
      action: "change the selected object's Name without dragging it in the hierarchy",
      distractors: ["Explorer", "Toolbox", "Output"],
      explanation: "Name is also a property, so Properties can edit it after the object is selected.",
      alternateAction: "edit the Name field of the selected Instance",
    },
  ],
  truths: [
    {
      truth: "Properties changes based on whichever Instance is currently selected.",
      lie: "Properties always shows the same fields no matter what object is selected.",
      explanation: "The panel is selection-dependent because different Instance classes expose different properties.",
    },
    {
      truth: "You usually select an object first, then edit its values in Properties.",
      lie: "You edit an object's values in Properties first and then Roblox Studio selects the object for you.",
      explanation: "Selection comes first so Properties knows which Instance to display.",
    },
    {
      truth: "Anchored, Transparency, Material, and Name are examples of property values.",
      lie: "Anchored, Transparency, Material, and Name are ribbon tabs in the Studio layout.",
      explanation: "Those are editable fields on Instances, not major interface tabs.",
    },
    {
      truth: "Properties is not the same thing as Explorer.",
      lie: "Properties and Explorer are two names for the same hierarchy panel.",
      explanation: "Explorer manages hierarchy. Properties edits values for the selected Instance.",
    },
    {
      truth: "The Properties panel can show booleans, numbers, colors, strings, and enums depending on the object.",
      lie: "The Properties panel can show only text values and nothing else.",
      explanation: "Roblox properties use many data types, and the panel adapts to them.",
    },
    {
      truth: "Changing a value in Properties affects the actual selected Instance.",
      lie: "Changes made in Properties are preview-only and never change the real object.",
      explanation: "Properties edits the real object in the place, not a fake preview.",
    },
    {
      truth: "Properties is useful for quick edits when you do not want to write code.",
      lie: "Properties can be used only by scripts and not by a builder in Studio.",
      explanation: "It is one of the main manual editing panels in the Studio UI.",
    },
    {
      truth: "If nothing is selected, Properties may show little or no object-specific data.",
      lie: "Properties fully edits every object in the place even when nothing is selected.",
      explanation: "The panel depends on the current selection.",
    },
  ],
};

export const toolboxPanelSpec: StudioConceptSpec = {
  concept: "toolbox-panel",
  title: "Toolbox",
  nodeType: "practice",
  definition: "Toolbox is the Roblox Studio panel for browsing and inserting assets like models, images, audio, and plugins.",
  definitionDistractors: [
    "Toolbox is the panel that edits the selected Instance's value fields.",
    "Toolbox is the panel that shows the Instance parent-child hierarchy.",
    "Toolbox is the button row that starts server and player playtests.",
  ],
  scenarios: [
    {
      action: "search for a model or mesh to insert into the place",
      distractors: ["Explorer", "Properties", "Output"],
      explanation: "Toolbox is the asset browser used for finding and inserting models and other library assets.",
      alternateAction: "browse creator assets from inside Studio",
    },
    {
      action: "insert a sound asset from the Roblox library",
      distractors: ["Explorer", "Properties", "Command Bar"],
      explanation: "Toolbox can browse more than models. It also exposes assets like audio and images.",
      alternateAction: "find a reusable asset in the Roblox catalog",
    },
    {
      action: "look for a plugin to install into Roblox Studio",
      distractors: ["Explorer", "Properties", "Viewport"],
      explanation: "Plugins are discovered through Toolbox, not through the hierarchy or property editor.",
      alternateAction: "browse Studio plugins instead of place objects",
    },
    {
      action: "search by keyword for a free model",
      distractors: ["Explorer", "Properties", "Animation Editor"],
      explanation: "Toolbox has search for assets, so keyword lookups belong there.",
      alternateAction: "type a search term to find insertable assets",
    },
    {
      action: "insert a decal or image asset without creating it from scratch",
      distractors: ["Explorer", "Properties", "Terrain Editor"],
      explanation: "Toolbox is where you browse existing assets from Roblox or your inventory.",
      alternateAction: "bring in an already-made Roblox asset",
    },
    {
      action: "open the built-in asset browser instead of writing code",
      distractors: ["Explorer", "Output", "Test tab"],
      explanation: "Toolbox is the visual asset browser inside Studio.",
      alternateAction: "use Studio's asset library interface",
    },
    {
      action: "review an asset before inserting it into the place",
      distractors: ["Properties", "Explorer", "Script Editor"],
      explanation: "Toolbox is the panel that exposes library content and insertion controls.",
      alternateAction: "inspect Roblox library content before adding it",
    },
    {
      action: "find a starter model instead of manually building every part yourself",
      distractors: ["Properties", "Explorer", "Output"],
      explanation: "Searching for existing models is a classic Toolbox workflow.",
      alternateAction: "insert premade content from the asset library",
    },
  ],
  truths: [
    {
      truth: "Toolbox can browse assets like models, plugins, audio, decals, and meshes.",
      lie: "Toolbox can browse only Parts that already exist in your current Workspace.",
      explanation: "Toolbox works with insertable assets and library content, not just current Workspace objects.",
    },
    {
      truth: "You should review assets from Toolbox carefully before trusting them in a real project.",
      lie: "Everything from Toolbox is automatically safe and production-ready with no review.",
      explanation: "Free models and plugins can include unwanted content, so inspection is important.",
    },
    {
      truth: "Toolbox is an asset browser, not the place hierarchy.",
      lie: "Toolbox replaces Explorer and is used to reparent Instances in the game tree.",
      explanation: "Hierarchy editing belongs to Explorer, not Toolbox.",
    },
    {
      truth: "Toolbox search is useful when you know a keyword for the asset you want.",
      lie: "Toolbox does not support searching and requires scrolling through every asset manually.",
      explanation: "Search is one of Toolbox's main features.",
    },
    {
      truth: "Toolbox can be used for plugins as well as in-game assets.",
      lie: "Toolbox cannot browse plugins at all.",
      explanation: "Plugins are one of the asset categories available through Toolbox.",
    },
    {
      truth: "Inserting a model from Toolbox places a new asset into your experience.",
      lie: "Inserting a model from Toolbox only renames your current Workspace objects.",
      explanation: "Toolbox inserts new content instead of editing unrelated existing objects.",
    },
    {
      truth: "Toolbox helps when you need starter content quickly, but it does not replace understanding how your project works.",
      lie: "Using Toolbox means you never need to inspect inserted objects or scripts.",
      explanation: "Inserted content still needs review, cleanup, and integration.",
    },
    {
      truth: "Toolbox is separate from Properties even though both can be open at the same time.",
      lie: "Toolbox and Properties are the same panel with two different names.",
      explanation: "Toolbox browses assets. Properties edits values on the selected Instance.",
    },
  ],
};

export const partManipulationSpec: StudioConceptSpec = {
  concept: "part-manipulation",
  title: "Part tools",
  nodeType: "teaching",
  definition: "Part tools are the Roblox Studio controls used to create, move, rotate, scale, anchor, and configure 3D parts.",
  definitionDistractors: [
    "Part tools are the service objects returned by game:GetService in code.",
    "Part tools are the asset browser entries inside Toolbox only.",
    "Part tools are the scripts that replicate UI from server to client.",
  ],
  scenarios: [
    {
      action: "drag a selected Part upward in the world",
      distractors: ["Explorer", "Properties", "Toolbox"],
      explanation: "Moving a Part in 3D space is done with the transform tools in the main build workflow.",
      alternateAction: "translate a selected block to a new position",
    },
    {
      action: "turn a Part 90 degrees around an axis",
      distractors: ["Explorer", "Properties", "Animation Editor"],
      explanation: "Rotating objects is part of the transform tool set for building in Studio.",
      alternateAction: "rotate a selected object in the world",
    },
    {
      action: "stretch a Part so it becomes wider",
      distractors: ["Explorer", "Toolbox", "Output"],
      explanation: "Scaling changes the size of the selected Part, which is one of the main part editing tools.",
      alternateAction: "resize a selected block in the viewport",
    },
    {
      action: "keep a platform from falling when the game starts",
      distractors: ["Explorer", "Toolbox", "Script Editor"],
      explanation: "Anchoring is part of core part setup. Builders usually set it from the part workflow or Properties.",
      alternateAction: "set a platform so physics will not drop it",
    },
    {
      action: "toggle whether a wall can collide with players",
      distractors: ["Explorer", "Toolbox", "Command Bar"],
      explanation: "Collision behavior is part of configuring Parts and their physical properties.",
      alternateAction: "change whether a selected block stops characters",
    },
    {
      action: "snap a moved part cleanly onto the grid",
      distractors: ["Explorer", "Toolbox", "Properties"],
      explanation: "Move, rotate, and scale tools work together with snapping settings for cleaner building.",
      alternateAction: "use Studio build controls for cleaner alignment",
    },
    {
      action: "duplicate a block and keep editing the copy",
      distractors: ["Explorer", "Toolbox", "Output"],
      explanation: "Part building workflows include selecting, duplicating, and transforming physical objects in the viewport.",
      alternateAction: "copy a selected part and continue building",
    },
    {
      action: "insert a basic block and then shape it in the viewport",
      distractors: ["Explorer", "Properties", "Output"],
      explanation: "Creating and transforming primitive parts is a core building workflow in Studio.",
      alternateAction: "start with a primitive part and edit it into the shape you need",
    },
  ],
  truths: [
    {
      truth: "Move, Rotate, and Scale are core tools for editing Parts in the viewport.",
      lie: "Move, Rotate, and Scale are Roblox services accessed with game:GetService.",
      explanation: "They are Studio build tools, not runtime services.",
    },
    {
      truth: "Anchored prevents a part from being moved by physics when the game runs.",
      lie: "Anchored makes a part invisible instead of stopping physics movement.",
      explanation: "Anchored controls whether physics simulation can move the part.",
    },
    {
      truth: "CanCollide controls whether players and other objects physically bump into a part.",
      lie: "CanCollide controls whether a part appears in Explorer.",
      explanation: "Collision is a physics property, not a hierarchy setting.",
    },
    {
      truth: "Scaling changes size, while rotating changes orientation.",
      lie: "Scaling changes orientation, while rotating changes color.",
      explanation: "The transform tools each affect different aspects of the selected object.",
    },
    {
      truth: "Grid snapping helps parts line up more cleanly while building.",
      lie: "Grid snapping is used only for Datastore saving and not for building.",
      explanation: "Snapping is a Studio build aid, not a persistence feature.",
    },
    {
      truth: "A part can be edited visually in Studio without writing any Lua code.",
      lie: "Every move, resize, and rotation requires a Lua script first.",
      explanation: "Studio provides direct building tools for manual world editing.",
    },
    {
      truth: "A duplicated part starts as a copy of the original part's setup.",
      lie: "Duplicating a part deletes the original and keeps only the copy.",
      explanation: "Duplication makes another object instead of replacing the existing one.",
    },
    {
      truth: "Part manipulation often combines viewport tools with property edits like Anchored or Material.",
      lie: "Part manipulation never uses the Properties panel at all.",
      explanation: "Builders often move a part in the viewport and then refine settings in Properties.",
    },
  ],
};

export const playtestPublishingSpec: StudioConceptSpec = {
  concept: "playtest-publishing",
  title: "Test and publish tools",
  nodeType: "teaching",
  definition: "Test and publish tools let you run the game in Studio, simulate players, save work, and publish updates to Roblox.",
  definitionDistractors: [
    "Test and publish tools are only the property fields on a selected Part.",
    "Test and publish tools are the hierarchy tree of Instances in the place.",
    "Test and publish tools are only the asset search results inside Toolbox.",
  ],
  scenarios: [
    {
      action: "press Play to spawn into the game and control a character",
      distractors: ["Explorer", "Properties", "Toolbox"],
      explanation: "Playtesting is part of the Test workflow in Studio, not the hierarchy or asset browser.",
      alternateAction: "run the experience and control it inside Studio",
    },
    {
      action: "stop a running playtest and return to edit mode",
      distractors: ["Explorer", "Toolbox", "Properties"],
      explanation: "Testing controls manage entering and leaving simulation mode.",
      alternateAction: "leave simulation and go back to building",
    },
    {
      action: "publish the current place update to Roblox",
      distractors: ["Explorer", "Properties", "Toolbox"],
      explanation: "Publishing is part of the save-and-share workflow, not the hierarchy or property workflow.",
      alternateAction: "send the latest place version to Roblox",
    },
    {
      action: "run the game to check whether a script behaves correctly",
      distractors: ["Explorer", "Toolbox", "Properties"],
      explanation: "Testing is how you validate gameplay, physics, UI, and scripts before release.",
      alternateAction: "simulate the experience before shipping it",
    },
    {
      action: "save a local copy of the place before making a risky change",
      distractors: ["Explorer", "Properties", "Toolbox"],
      explanation: "Saving and publishing are part of the place management workflow around testing and releases.",
      alternateAction: "store a safer copy of the place before experimenting",
    },
    {
      action: "start a multiplayer test with server and player sessions",
      distractors: ["Properties", "Toolbox", "Explorer"],
      explanation: "Multiplayer playtests belong to the testing toolset, not the object and asset panels.",
      alternateAction: "simulate server-client behavior in Studio",
    },
    {
      action: "check game behavior before players see the new update",
      distractors: ["Explorer", "Properties", "Toolbox"],
      explanation: "A playtest is meant to catch issues before you publish the experience to Roblox.",
      alternateAction: "verify a feature in Studio before releasing it",
    },
    {
      action: "publish after confirming the new version works",
      distractors: ["Properties", "Explorer", "Toolbox"],
      explanation: "Testing and publishing work together: test first, then publish once the change is ready.",
      alternateAction: "ship a tested build instead of an unverified one",
    },
  ],
  truths: [
    {
      truth: "Playtesting lets you run the game inside Studio to check gameplay and scripts.",
      lie: "Playtesting is only for renaming objects in the Explorer tree.",
      explanation: "Testing runs the experience. Explorer manages hierarchy.",
    },
    {
      truth: "Publishing sends your place updates to Roblox.",
      lie: "Publishing only closes Studio and does not save or upload anything.",
      explanation: "Publishing is how your place changes reach Roblox.",
    },
    {
      truth: "You usually want to test a change before publishing it.",
      lie: "There is no reason to test before publishing because Studio and Roblox always behave identically without bugs.",
      explanation: "Testing catches logic, UI, and physics issues before release.",
    },
    {
      truth: "Stopping a playtest returns you to edit mode.",
      lie: "Stopping a playtest permanently deletes your place from Studio.",
      explanation: "Stop ends the simulation and restores the editing environment.",
    },
    {
      truth: "A multiplayer Studio test can help you verify client-server behavior.",
      lie: "Studio tests can never simulate more than one player.",
      explanation: "Roblox Studio supports server and player test sessions for networking checks.",
    },
    {
      truth: "Saving locally and publishing to Roblox are related but not identical actions.",
      lie: "Saving a local file and publishing online are always the exact same thing.",
      explanation: "A local save keeps a file copy, while publishing updates the Roblox-hosted experience.",
    },
    {
      truth: "Play mode usually gives you player controls so you can move around the game.",
      lie: "Play mode is only a static screenshot of the map with no simulation.",
      explanation: "Play mode runs the experience so you can interact with it.",
    },
    {
      truth: "Testing is useful for verifying scripts, UI, physics, and spawn behavior.",
      lie: "Testing is useful only for terrain painting and nothing else.",
      explanation: "Playtests cover many systems, not just one editing workflow.",
    },
  ],
};

export const workspaceServiceSpec: RobloxCodeConceptSpec = {
  concept: "workspace-service",
  title: "workspace",
  nodeType: "practice",
  definitions: [
    {
      prompt: "What does `workspace` usually represent in Roblox Lua?",
      options: [
        "The service that contains the live 3D world and most visible parts",
        "The text box that searches the Toolbox",
        "The script type used only on the client",
        "The panel that edits selected object properties",
      ],
      correctIndex: 0,
      explanation: "`workspace` is the main container for the live 3D world. Parts parented there exist in the place and can appear during play.",
    },
    {
      prompt: "Where does a normal visible Part usually need to be parented so it exists in the world?",
      options: ["workspace", "Toolbox", "Output", "Properties"],
      correctIndex: 0,
      explanation: "Parenting a Part to `workspace` puts it into the live world tree. Panels like Toolbox and Properties are Studio UI, not runtime containers.",
    },
    {
      prompt: "Which Roblox expression refers to the same world container as the lowercase global `workspace`?",
      options: ["game.Workspace", "game.Players", "game.ServerScriptService", "script.Parent.Parent"],
      correctIndex: 0,
      explanation: "`workspace` and `game.Workspace` refer to the same service object. Roblox provides the lowercase shortcut globally.",
    },
    {
      prompt: "Why would a builder use `workspace` in code?",
      options: [
        "To access or parent world objects like Parts, Models, and folders in the live place",
        "To browse free models from Roblox's library",
        "To edit a selected object's Transparency field in the UI",
        "To publish the place to Roblox without testing",
      ],
      correctIndex: 0,
      explanation: "`workspace` is for live world objects. It is not the asset browser, property editor, or publish flow.",
    },
  ],
  truths: [
    {
      prompt: "In Roblox Lua, `workspace` and `game.Workspace` refer to the same service object.",
      correct: true,
      explanation: "Roblox exposes the Workspace service through both the lowercase global and the property on `game`.",
      code: "print(workspace == game.Workspace)",
    },
    {
      prompt: "Parenting a Part to `workspace` can make it part of the live world.",
      correct: true,
      explanation: "Once a Part's Parent is set to `workspace`, it becomes part of the world tree and can appear in the game.",
      code: "local part = Instance.new(\"Part\")\npart.Parent = workspace",
    },
    {
      prompt: "`workspace` is a Studio panel like Explorer, not a runtime service.",
      correct: false,
      explanation: "`workspace` is a runtime service-like object in the DataModel. Explorer is only a Studio interface panel.",
    },
    {
      prompt: "A script can never read properties like `workspace.Name` or `workspace.ClassName`.",
      correct: false,
      explanation: "Scripts can read standard properties from `workspace` just like other Instances and services.",
      code: "print(workspace.Name)\nprint(workspace.ClassName)",
    },
  ],
  examples: [
    {
      mcOutputPrompt: "What does this print after the part is parented?",
      mcOutputCode: "local part = Instance.new(\"Part\")\npart.Parent = workspace\nprint(part.Parent == workspace)",
      mcOutputOptions: ["true", "false", "nil", "Part"],
      mcOutputCorrectIndex: 0,
      mcOutputExplanation: "The part's Parent is set to `workspace`, so the comparison prints `true`.",
      fillTypePrompt: "Type the missing target so the part is placed into the live world.",
      fillTypeCode: "local part = Instance.new(\"Part\")\npart.Parent = ___",
      fillTypeAnswer: "workspace",
      fillTypeExplanation: "Setting `Parent` to `workspace` places the part into the world tree.",
      fillTypeHint: "Use the global name of the world service.",
      fillSelectPrompt: "Fill both blanks so the part is parented into the world.",
      fillSelectCode: "local part = Instance.new(\"Part\")\npart.___ = ___",
      fillSelectTokens: ["Parent", "workspace", "Name", "game"],
      fillSelectAnswer: ["Parent", "workspace"],
      fillSelectExplanation: "`Parent` chooses the container, and `workspace` is the world container.",
      wordBankPrompt: "Build the line that places the new part into the world.",
      wordBankTokens: ["part.Parent", "=", "workspace", "part.Name", "\"Block\"", "game.Players"],
      wordBankAnswer: ["part.Parent", "=", "workspace"],
      wordBankExplanation: "A new part enters the world when its Parent is set to `workspace`.",
      predictPrompt: "What does this print?",
      predictCode: "local folder = Instance.new(\"Folder\")\nfolder.Parent = workspace\nprint(folder.Parent.Name)",
      predictAnswer: "Workspace",
      predictExplanation: "The folder's parent is `workspace`, and that service's Name property is `Workspace`.",
    },
    {
      mcOutputPrompt: "What is printed here?",
      mcOutputCode: "print(workspace.ClassName)",
      mcOutputOptions: ["Workspace", "Folder", "Service", "DataModel"],
      mcOutputCorrectIndex: 0,
      mcOutputExplanation: "The Workspace service reports its class name as `Workspace`.",
      fillTypePrompt: "Type the property that prints `Workspace` for the world service.",
      fillTypeCode: "print(workspace.___)",
      fillTypeAnswer: "ClassName",
      fillTypeExplanation: "`ClassName` returns the Roblox class, which is `Workspace` here.",
      fillSelectPrompt: "Fill the blanks so the code prints the world service name.",
      fillSelectCode: "local worldName = workspace.___\nprint(___)",
      fillSelectTokens: ["Name", "worldName", "Parent", "workspace"],
      fillSelectAnswer: ["Name", "worldName"],
      fillSelectExplanation: "`workspace.Name` is stored in `worldName`, then printed.",
      wordBankPrompt: "Build the line that prints the Workspace service name.",
      wordBankTokens: ["print", "(", "workspace.Name", ")", "workspace.Parent", "game"],
      wordBankAnswer: ["print", "(", "workspace.Name", ")"],
      wordBankExplanation: "Printing `workspace.Name` shows the service's display name.",
      predictPrompt: "What does this print?",
      predictCode: "print(workspace == game.Workspace)",
      predictAnswer: "true",
      predictExplanation: "Both expressions reference the same Workspace object, so the comparison is true.",
    },
    {
      mcOutputPrompt: "What does this comparison print?",
      mcOutputCode: "local model = Instance.new(\"Model\")\nmodel.Parent = workspace\nprint(model.Parent == game.Workspace)",
      mcOutputOptions: ["true", "false", "Model", "Workspace"],
      mcOutputCorrectIndex: 0,
      mcOutputExplanation: "The model's parent is set to Workspace, and `workspace` matches `game.Workspace`.",
      fillTypePrompt: "Type the container name so the folder is placed in the world.",
      fillTypeCode: "local folder = Instance.new(\"Folder\")\nfolder.Parent = game.___",
      fillTypeAnswer: "Workspace",
      fillTypeExplanation: "You can also reach the world through `game.Workspace`.",
      fillSelectPrompt: "Fill both blanks so the code stores the world service and prints its class name.",
      fillSelectCode: "local world = ___\nprint(world.___)",
      fillSelectTokens: ["workspace", "ClassName", "Players", "Parent"],
      fillSelectAnswer: ["workspace", "ClassName"],
      fillSelectExplanation: "`workspace` stores the world service, and `ClassName` prints its class.",
      wordBankPrompt: "Build the line that stores a folder under Workspace.",
      wordBankTokens: ["folder.Parent", "=", "game.Workspace", "folder.Value", "\"Coins\"", "script"],
      wordBankAnswer: ["folder.Parent", "=", "game.Workspace"],
      wordBankExplanation: "Parenting to `game.Workspace` is another correct way to place it in the world.",
      predictPrompt: "What does this print?",
      predictCode: "local part = Instance.new(\"Part\")\npart.Parent = game.Workspace\nprint(part.Parent.ClassName)",
      predictAnswer: "Workspace",
      predictExplanation: "The part's parent is the Workspace service, so its class name prints as `Workspace`.",
    },
    {
      mcOutputPrompt: "What is printed after the value is assigned?",
      mcOutputCode: "workspace.StreamingEnabled = false\nprint(workspace.StreamingEnabled)",
      mcOutputOptions: ["false", "true", "nil", "Workspace"],
      mcOutputCorrectIndex: 0,
      mcOutputExplanation: "The property is explicitly set to `false`, so printing it returns `false`.",
      fillTypePrompt: "Type the property name so this reads the world service's display name.",
      fillTypeCode: "print(workspace.___)",
      fillTypeAnswer: "Name",
      fillTypeExplanation: "`Name` is the standard property that prints `Workspace`.",
      fillSelectPrompt: "Fill the blanks so the code compares the two Workspace references.",
      fillSelectCode: "print(___ == ___)",
      fillSelectTokens: ["workspace", "game.Workspace", "game.Players", "script"],
      fillSelectAnswer: ["workspace", "game.Workspace"],
      fillSelectExplanation: "Both expressions refer to the same Workspace service.",
      wordBankPrompt: "Build the expression that compares the two Workspace references.",
      wordBankTokens: ["workspace", "==", "game.Workspace", "game.Players", "=", "script"],
      wordBankAnswer: ["workspace", "==", "game.Workspace"],
      wordBankExplanation: "This equality check is true because both sides point to the same service object.",
      predictPrompt: "What does this print?",
      predictCode: "print(workspace.Name)\nprint(workspace.ClassName)",
      predictAnswer: "Workspace\nWorkspace",
      predictExplanation: "Both `Name` and `ClassName` evaluate to `Workspace` for the world service.",
    },
  ],
  arrange: [
    {
      prompt: "Arrange the code so a part is created, parented into the world, and renamed.",
      lines: [
        "local part = Instance.new(\"Part\")",
        "part.Parent = workspace",
        "part.Name = \"SpawnBlock\"",
      ],
      correctOrder: [0, 1, 2],
      explanation: "Create the part first, parent it into Workspace, then rename it.",
    },
    {
      prompt: "Arrange the code so the script stores Workspace in a variable and prints its name.",
      lines: [
        "local world = workspace",
        "local worldName = world.Name",
        "print(worldName)",
      ],
      correctOrder: [0, 1, 2],
      explanation: "First store the service, then read its Name, then print the result.",
    },
    {
      prompt: "Arrange the code so a folder is added to Workspace and its parent name is printed.",
      lines: [
        "local folder = Instance.new(\"Folder\")",
        "folder.Parent = game.Workspace",
        "print(folder.Parent.Name)",
      ],
      correctOrder: [0, 1, 2],
      explanation: "The folder must exist before you parent it, and the print comes after the parent is assigned.",
    },
  ],
  bugs: [
    {
      prompt: "Which version has the bug if the goal is to parent a part into the world service?",
      versionA: "local part = Instance.new(\"Part\")\npart.Parent = Workspace",
      versionB: "local part = Instance.new(\"Part\")\npart.Parent = workspace",
      buggyVersion: "A",
      explanation: "Roblox provides the lowercase global `workspace`. `Workspace` is not the standard global variable to use here.",
    },
    {
      prompt: "Which version has the bug if the goal is to print the Workspace service name?",
      versionA: "print(workspace.Name)",
      versionB: "print(workspace.Parent)",
      buggyVersion: "B",
      explanation: "Printing `workspace.Parent` gives the DataModel, not the workspace name. `workspace.Name` is the correct property.",
    },
    {
      prompt: "Which version has the bug if the goal is to place a folder into Workspace?",
      versionA: "local folder = Instance.new(\"Folder\")\nfolder.Parent = game.Workspace",
      versionB: "local folder = Instance.new(\"Folder\")\nfolder = game.Workspace",
      buggyVersion: "B",
      explanation: "Version B overwrites the variable instead of parenting the folder into Workspace.",
    },
  ],
};

export const instanceNewSpec: RobloxCodeConceptSpec = {
  concept: "instance-new",
  title: "Instance.new",
  nodeType: "practice",
  definitions: [
    {
      prompt: "What does `Instance.new()` do in Roblox Lua?",
      options: [
        "It creates a new Roblox object from a class name string",
        "It publishes the place to Roblox",
        "It opens the Toolbox asset browser",
        "It restarts the current server",
      ],
      correctIndex: 0,
      explanation: "`Instance.new()` constructs a new object like a Part, Folder, or ScreenGui by class name.",
    },
    {
      prompt: "Which argument does `Instance.new()` usually need first?",
      options: ["A class name string like \"Part\"", "A panel name like Explorer", "A boolean like true", "A player object"],
      correctIndex: 0,
      explanation: "You pass the class name as text, such as `\"Part\"` or `\"Folder\"`.",
    },
    {
      prompt: "Which expression creates a new Part object in Roblox Lua?",
      options: [
        "Instance.new(\"Part\")",
        "Part.new()",
        "game:GetService(\"Part\")",
        "workspace.new(\"Part\")",
      ],
      correctIndex: 0,
      explanation: "Roblox objects are created with `Instance.new(\"ClassName\")`, not with `.new()` on the class name itself.",
    },
    {
      prompt: "After creating an object with `Instance.new()`, what do you usually do next?",
      options: [
        "Store it, configure it, and set properties like Parent or Name",
        "Publish the whole place immediately",
        "Open the Toolbox to convert it into a plugin",
        "Restart Studio so the object can load",
      ],
      correctIndex: 0,
      explanation: "Creating the object is only the first step. You normally configure fields like Name, Value, or Parent next.",
    },
  ],
  truths: [
    {
      prompt: "A new object from `Instance.new()` exists before you parent it anywhere.",
      correct: true,
      explanation: "The object is created immediately. Parenting decides where it lives in the DataModel.",
      code: "local folder = Instance.new(\"Folder\")\nprint(folder.ClassName)",
    },
    {
      prompt: "You can create different Roblox classes like Part, Folder, and ClickDetector with `Instance.new()`.",
      correct: true,
      explanation: "The class name string tells Roblox which kind of object to create.",
    },
    {
      prompt: "The class name in `Instance.new()` should be written as a string like `Part` without quotes.",
      correct: false,
      explanation: "Roblox expects a string, so you write `Instance.new(\"Part\")` with quotes around the class name.",
    },
    {
      prompt: "`Instance.new()` can only create Part objects and nothing else.",
      correct: false,
      explanation: "It creates many classes, including Folder, Value objects, GUIs, detectors, sounds, and more.",
    },
  ],
  examples: [
    {
      mcOutputPrompt: "What does this print?",
      mcOutputCode: "local part = Instance.new(\"Part\")\nprint(part.ClassName)",
      mcOutputOptions: ["Part", "Instance", "Workspace", "Model"],
      mcOutputCorrectIndex: 0,
      mcOutputExplanation: "The created object's class is `Part`, so `ClassName` prints `Part`.",
      fillTypePrompt: "Type the class name so the code creates a Part.",
      fillTypeCode: "local part = Instance.new(\"___\")",
      fillTypeAnswer: "Part",
      fillTypeExplanation: "Passing `\"Part\"` tells Roblox to create a Part object.",
      fillTypeHint: "Use the standard block class name.",
      fillSelectPrompt: "Fill the blanks so the code creates a folder and prints its class.",
      fillSelectCode: "local folder = Instance.new(\"___\")\nprint(folder.___)",
      fillSelectTokens: ["Folder", "ClassName", "Name", "Parent"],
      fillSelectAnswer: ["Folder", "ClassName"],
      fillSelectExplanation: "The class is `Folder`, and `ClassName` prints the object's class type.",
      wordBankPrompt: "Build the line that creates a new Part.",
      wordBankTokens: ["local", "part", "=", "Instance.new(\"Part\")", "workspace", "print(part)"],
      wordBankAnswer: ["local", "part", "=", "Instance.new(\"Part\")"],
      wordBankExplanation: "That line stores a new Part object in a variable named `part`.",
      predictPrompt: "What does this print?",
      predictCode: "local detector = Instance.new(\"ClickDetector\")\nprint(detector.ClassName)",
      predictAnswer: "ClickDetector",
      predictExplanation: "The created object is a ClickDetector, so its class name prints as `ClickDetector`.",
    },
    {
      mcOutputPrompt: "What does this print after the new folder is named?",
      mcOutputCode: "local folder = Instance.new(\"Folder\")\nfolder.Name = \"Coins\"\nprint(folder.Name)",
      mcOutputOptions: ["Coins", "Folder", "Workspace", "nil"],
      mcOutputCorrectIndex: 0,
      mcOutputExplanation: "The folder's Name property is set to `Coins`, so that exact text is printed.",
      fillTypePrompt: "Type the property name so the object is renamed to `Coins`.",
      fillTypeCode: "local folder = Instance.new(\"Folder\")\nfolder.___ = \"Coins\"",
      fillTypeAnswer: "Name",
      fillTypeExplanation: "`Name` is the property used to rename an Instance.",
      fillSelectPrompt: "Fill the blanks so the script creates a StringValue and stores text inside it.",
      fillSelectCode: "local value = Instance.new(\"___\")\nvalue.___ = \"Ready\"",
      fillSelectTokens: ["StringValue", "Value", "Name", "Parent"],
      fillSelectAnswer: ["StringValue", "Value"],
      fillSelectExplanation: "`StringValue` is the class, and `Value` stores the string data.",
      wordBankPrompt: "Build the line that renames the created folder to `Coins`.",
      wordBankTokens: ["folder.Name", "=", "\"Coins\"", "folder.Parent", "workspace", "print(folder)"],
      wordBankAnswer: ["folder.Name", "=", "\"Coins\""],
      wordBankExplanation: "The `Name` property controls what the Instance is called.",
      predictPrompt: "What does this print?",
      predictCode: "local value = Instance.new(\"StringValue\")\nvalue.Value = \"Ready\"\nprint(value.Value)",
      predictAnswer: "Ready",
      predictExplanation: "A StringValue stores text in its `Value` property, so it prints `Ready`.",
    },
    {
      mcOutputPrompt: "What does this print?",
      mcOutputCode: "local click = Instance.new(\"ClickDetector\")\nclick.Name = \"TapTarget\"\nprint(click.Name)",
      mcOutputOptions: ["TapTarget", "ClickDetector", "Detector", "true"],
      mcOutputCorrectIndex: 0,
      mcOutputExplanation: "The object's name is explicitly set to `TapTarget` before printing.",
      fillTypePrompt: "Type the class name so the code creates a ClickDetector.",
      fillTypeCode: "local click = Instance.new(\"___\")",
      fillTypeAnswer: "ClickDetector",
      fillTypeExplanation: "`ClickDetector` is the class name string used for click interaction objects.",
      fillSelectPrompt: "Fill the blanks so the code creates a Part and renames it.",
      fillSelectCode: "local part = Instance.new(\"___\")\npart.___ = \"SpawnBlock\"",
      fillSelectTokens: ["Part", "Name", "Value", "ClassName"],
      fillSelectAnswer: ["Part", "Name"],
      fillSelectExplanation: "A new Part uses the `Part` class and the `Name` property for renaming.",
      wordBankPrompt: "Build the line that creates a ClickDetector object.",
      wordBankTokens: ["local", "click", "=", "Instance.new(\"ClickDetector\")", "workspace", "click.Parent"],
      wordBankAnswer: ["local", "click", "=", "Instance.new(\"ClickDetector\")"],
      wordBankExplanation: "That full line creates a ClickDetector and stores it in `click`.",
      predictPrompt: "What does this print?",
      predictCode: "local part = Instance.new(\"Part\")\npart.Name = \"SpawnBlock\"\nprint(part.Name)",
      predictAnswer: "SpawnBlock",
      predictExplanation: "The new part is renamed before printing, so the output is `SpawnBlock`.",
    },
    {
      mcOutputPrompt: "What does this print?",
      mcOutputCode: "local value = Instance.new(\"IntValue\")\nvalue.Value = 25\nprint(value.Value)",
      mcOutputOptions: ["25", "IntValue", "Value", "nil"],
      mcOutputCorrectIndex: 0,
      mcOutputExplanation: "The IntValue stores the number 25 in its `Value` property, so that is printed.",
      fillTypePrompt: "Type the class name so the object can store an integer in `Value`.",
      fillTypeCode: "local value = Instance.new(\"___\")\nvalue.Value = 25",
      fillTypeAnswer: "IntValue",
      fillTypeExplanation: "`IntValue` is a built-in Roblox class for storing integer data in the DataModel.",
      fillSelectPrompt: "Fill the blanks so the code creates an IntValue and prints its number.",
      fillSelectCode: "local score = Instance.new(\"___\")\nprint(score.___)",
      fillSelectTokens: ["IntValue", "Value", "Name", "ClassName"],
      fillSelectAnswer: ["IntValue", "Value"],
      fillSelectExplanation: "The object class is `IntValue`, and its data is read through `Value`.",
      wordBankPrompt: "Build the line that stores the number 25 in the IntValue.",
      wordBankTokens: ["value.Value", "=", "25", "value.Name", "\"Coins\"", "workspace"],
      wordBankAnswer: ["value.Value", "=", "25"],
      wordBankExplanation: "The `Value` field stores the integer payload on the IntValue.",
      predictPrompt: "What does this print?",
      predictCode: "local value = Instance.new(\"Folder\")\nprint(value.ClassName)",
      predictAnswer: "Folder",
      predictExplanation: "The created object is a Folder, so its class name prints as `Folder`.",
    },
  ],
  arrange: [
    {
      prompt: "Arrange the code so a folder is created, renamed, and parented to Workspace.",
      lines: [
        "local folder = Instance.new(\"Folder\")",
        "folder.Name = \"Coins\"",
        "folder.Parent = workspace",
      ],
      correctOrder: [0, 1, 2],
      explanation: "Create the object first, then rename it, then parent it where it should live.",
    },
    {
      prompt: "Arrange the code so a StringValue is created and loaded with text.",
      lines: [
        "local status = Instance.new(\"StringValue\")",
        "status.Name = \"RoundState\"",
        "status.Value = \"Waiting\"",
      ],
      correctOrder: [0, 1, 2],
      explanation: "The value object must exist before you set its Name and Value properties.",
    },
    {
      prompt: "Arrange the code so a ClickDetector is created and named correctly.",
      lines: [
        "local click = Instance.new(\"ClickDetector\")",
        "click.Name = \"DoorClick\"",
        "print(click.ClassName)",
      ],
      correctOrder: [0, 1, 2],
      explanation: "First create the detector, then rename it, then print its class if needed.",
    },
  ],
  bugs: [
    {
      prompt: "Which version has the bug if the goal is to create a Part?",
      versionA: "local part = Instance.new(\"Part\")",
      versionB: "local part = Instance.new(Part)",
      buggyVersion: "B",
      explanation: "The class name must be passed as a string. `Part` without quotes is not the correct argument here.",
    },
    {
      prompt: "Which version has the bug if the goal is to store `Coins` in the folder's Name property?",
      versionA: "local folder = Instance.new(\"Folder\")\nfolder.Name = \"Coins\"",
      versionB: "local folder = Instance.new(\"Folder\")\nfolder.Value = \"Coins\"",
      buggyVersion: "B",
      explanation: "Folders do not use `Value` for naming. The correct property for an Instance's display name is `Name`.",
    },
    {
      prompt: "Which version has the bug if the goal is to create a ClickDetector object?",
      versionA: "local click = Instance.new(\"ClickDetector\")",
      versionB: "local click = ClickDetector.new()",
      buggyVersion: "B",
      explanation: "Roblox Instances are created with `Instance.new(\"ClassName\")`, not with `.new()` on the class name.",
    },
  ],
};

export const scriptTypesSpec: RobloxCodeConceptSpec = {
  concept: "script-types",
  title: "Script, LocalScript, and ModuleScript",
  nodeType: "teaching",
  definitions: [
    {
      prompt: "Which Roblox class represents normal server-side scripts in the DataModel?",
      options: ["Script", "LocalScript", "ModuleScript", "Workspace"],
      correctIndex: 0,
      explanation: "`Script` is the standard server-side script class. LocalScript is for client-side code, and ModuleScript is for reusable modules.",
    },
    {
      prompt: "Which script type is meant for client-side behavior such as player UI and local input?",
      options: ["LocalScript", "Script", "Workspace", "Folder"],
      correctIndex: 0,
      explanation: "`LocalScript` is the client-side script type in Roblox. It is used for player-local systems like GUI and input.",
    },
    {
      prompt: "What is a ModuleScript mainly used for?",
      options: [
        "Storing reusable code that can be required from other scripts",
        "Opening the Toolbox asset browser",
        "Publishing the place to Roblox",
        "Replacing Workspace as the world container",
      ],
      correctIndex: 0,
      explanation: "ModuleScripts package reusable code and return values or tables through `require`.",
    },
    {
      prompt: "Which choice correctly lists the three main Roblox script object classes?",
      options: [
        "Script, LocalScript, and ModuleScript",
        "Part, Script, and Explorer",
        "Players, Folder, and Plugin",
        "TweenService, Script, and Viewport",
      ],
      correctIndex: 0,
      explanation: "Those three classes cover server scripts, client scripts, and reusable module code in Roblox.",
    },
  ],
  truths: [
    {
      prompt: "A `LocalScript` is a different class from a normal `Script`.",
      correct: true,
      explanation: "Roblox separates client-local scripts and server scripts into different classes with different execution contexts.",
      code: "local clientScript = Instance.new(\"LocalScript\")\nprint(clientScript.ClassName)",
    },
    {
      prompt: "A `ModuleScript` is used for reusable code instead of direct one-off world behavior by itself.",
      correct: true,
      explanation: "ModuleScripts are designed to return reusable logic or data to other scripts through `require`.",
    },
    {
      prompt: "A `Script` and a `LocalScript` are just two different names for the exact same Roblox class.",
      correct: false,
      explanation: "They are separate classes with different intended execution contexts.",
    },
    {
      prompt: "A `ModuleScript` is a Studio panel you open from the View tab.",
      correct: false,
      explanation: "ModuleScript is an Instance class for reusable Lua code, not a Studio interface panel.",
    },
  ],
  examples: [
    {
      mcOutputPrompt: "What does this print?",
      mcOutputCode: "local serverScript = Instance.new(\"Script\")\nprint(serverScript.ClassName)",
      mcOutputOptions: ["Script", "LocalScript", "ModuleScript", "Instance"],
      mcOutputCorrectIndex: 0,
      mcOutputExplanation: "The created object is a `Script`, so `ClassName` prints `Script`.",
      fillTypePrompt: "Type the class name so the code creates a normal server script object.",
      fillTypeCode: "local serverScript = Instance.new(\"___\")",
      fillTypeAnswer: "Script",
      fillTypeExplanation: "`Script` is the server-side script class name.",
      fillSelectPrompt: "Fill the blanks so the code creates a LocalScript and prints its class.",
      fillSelectCode: "local clientScript = Instance.new(\"___\")\nprint(clientScript.___)",
      fillSelectTokens: ["LocalScript", "ClassName", "Name", "Parent"],
      fillSelectAnswer: ["LocalScript", "ClassName"],
      fillSelectExplanation: "The client-side script class is `LocalScript`, and `ClassName` prints its type.",
      wordBankPrompt: "Build the line that creates a ModuleScript.",
      wordBankTokens: ["local", "moduleScript", "=", "Instance.new(\"ModuleScript\")", "workspace", "print(moduleScript)"],
      wordBankAnswer: ["local", "moduleScript", "=", "Instance.new(\"ModuleScript\")"],
      wordBankExplanation: "That line creates a reusable module object and stores it in a variable.",
      predictPrompt: "What does this print?",
      predictCode: "local clientScript = Instance.new(\"LocalScript\")\nprint(clientScript.ClassName)",
      predictAnswer: "LocalScript",
      predictExplanation: "The object's class is LocalScript, so that text is printed.",
    },
    {
      mcOutputPrompt: "What does this print?",
      mcOutputCode: "local moduleScript = Instance.new(\"ModuleScript\")\nmoduleScript.Name = \"RoundUtils\"\nprint(moduleScript.Name)",
      mcOutputOptions: ["RoundUtils", "ModuleScript", "Script", "nil"],
      mcOutputCorrectIndex: 0,
      mcOutputExplanation: "The module is renamed to `RoundUtils`, so its Name property prints that exact value.",
      fillTypePrompt: "Type the property name so the ModuleScript is renamed to `RoundUtils`.",
      fillTypeCode: "local moduleScript = Instance.new(\"ModuleScript\")\nmoduleScript.___ = \"RoundUtils\"",
      fillTypeAnswer: "Name",
      fillTypeExplanation: "Like other Instances, script objects use the `Name` property for renaming.",
      fillSelectPrompt: "Fill the blanks so the script creates a Script and stores its class name in a variable.",
      fillSelectCode: "local serverScript = Instance.new(\"___\")\nlocal kind = serverScript.___",
      fillSelectTokens: ["Script", "ClassName", "Name", "LocalScript"],
      fillSelectAnswer: ["Script", "ClassName"],
      fillSelectExplanation: "A server script uses the `Script` class and reports its type through `ClassName`.",
      wordBankPrompt: "Build the line that renames the LocalScript to `ClientHud`.",
      wordBankTokens: ["clientScript.Name", "=", "\"ClientHud\"", "clientScript.Value", "workspace", "print(clientScript)"],
      wordBankAnswer: ["clientScript.Name", "=", "\"ClientHud\""],
      wordBankExplanation: "Script objects are renamed through `Name` just like other Instances.",
      predictPrompt: "What does this print?",
      predictCode: "local moduleScript = Instance.new(\"ModuleScript\")\nprint(moduleScript.ClassName)",
      predictAnswer: "ModuleScript",
      predictExplanation: "The object was created as a ModuleScript, so that is its class name.",
    },
    {
      mcOutputPrompt: "What does this print after the LocalScript is renamed?",
      mcOutputCode: "local clientScript = Instance.new(\"LocalScript\")\nclientScript.Name = \"ClientHud\"\nprint(clientScript.Name)",
      mcOutputOptions: ["ClientHud", "LocalScript", "Script", "false"],
      mcOutputCorrectIndex: 0,
      mcOutputExplanation: "The LocalScript's Name property is set to `ClientHud` before printing.",
      fillTypePrompt: "Type the class name so the code creates a client-side script object.",
      fillTypeCode: "local clientScript = Instance.new(\"___\")",
      fillTypeAnswer: "LocalScript",
      fillTypeExplanation: "`LocalScript` is the class name used for client-local code objects.",
      fillSelectPrompt: "Fill the blanks so the code creates a ModuleScript and renames it to `RoundUtils`.",
      fillSelectCode: "local moduleScript = Instance.new(\"___\")\nmoduleScript.___ = \"RoundUtils\"",
      fillSelectTokens: ["ModuleScript", "Name", "ClassName", "Script"],
      fillSelectAnswer: ["ModuleScript", "Name"],
      fillSelectExplanation: "A ModuleScript is created from its class name and renamed through `Name`.",
      wordBankPrompt: "Build the line that creates a LocalScript.",
      wordBankTokens: ["local", "clientScript", "=", "Instance.new(\"LocalScript\")", "workspace", "clientScript.Name"],
      wordBankAnswer: ["local", "clientScript", "=", "Instance.new(\"LocalScript\")"],
      wordBankExplanation: "That line creates a client script object and stores it in `clientScript`.",
      predictPrompt: "What does this print?",
      predictCode: "local serverScript = Instance.new(\"Script\")\nserverScript.Name = \"ServerLogic\"\nprint(serverScript.Name)",
      predictAnswer: "ServerLogic",
      predictExplanation: "The Name property was set to `ServerLogic`, so that text is printed.",
    },
    {
      mcOutputPrompt: "What does this print?",
      mcOutputCode: "local serverScript = Instance.new(\"Script\")\nlocal clientScript = Instance.new(\"LocalScript\")\nprint(serverScript.ClassName == clientScript.ClassName)",
      mcOutputOptions: ["false", "true", "Script", "LocalScript"],
      mcOutputCorrectIndex: 0,
      mcOutputExplanation: "The two objects have different classes, so the comparison prints `false`.",
      fillTypePrompt: "Type the class name so the code creates a reusable module object.",
      fillTypeCode: "local moduleScript = Instance.new(\"___\")",
      fillTypeAnswer: "ModuleScript",
      fillTypeExplanation: "`ModuleScript` is the reusable module code class in Roblox.",
      fillSelectPrompt: "Fill the blanks so the code creates both script types and compares their classes.",
      fillSelectCode: "local serverScript = Instance.new(\"___\")\nlocal clientScript = Instance.new(\"___\")",
      fillSelectTokens: ["Script", "LocalScript", "ModuleScript", "Folder"],
      fillSelectAnswer: ["Script", "LocalScript"],
      fillSelectExplanation: "A normal server script uses `Script`, while the client version uses `LocalScript`.",
      wordBankPrompt: "Build the expression that compares the class names of the two script objects.",
      wordBankTokens: ["serverScript.ClassName", "==", "clientScript.ClassName", "=", "workspace", "script.Parent"],
      wordBankAnswer: ["serverScript.ClassName", "==", "clientScript.ClassName"],
      wordBankExplanation: "Comparing their class names shows whether they are the same script type.",
      predictPrompt: "What does this print?",
      predictCode: "local a = Instance.new(\"Script\")\nlocal b = Instance.new(\"LocalScript\")\nprint(a.ClassName == b.ClassName)",
      predictAnswer: "false",
      predictExplanation: "A Script and a LocalScript are different classes, so the equality check is false.",
    },
  ],
  arrange: [
    {
      prompt: "Arrange the code so a Script is created and renamed.",
      lines: [
        "local serverScript = Instance.new(\"Script\")",
        "serverScript.Name = \"ServerLogic\"",
        "print(serverScript.ClassName)",
      ],
      correctOrder: [0, 1, 2],
      explanation: "Create the script first, then rename it, then print its class if needed.",
    },
    {
      prompt: "Arrange the code so a LocalScript is created and stored in a variable called `clientScript`.",
      lines: [
        "local clientScript = Instance.new(\"LocalScript\")",
        "clientScript.Name = \"ClientHud\"",
        "print(clientScript.Name)",
      ],
      correctOrder: [0, 1, 2],
      explanation: "The object must be created before you can rename it or print its name.",
    },
    {
      prompt: "Arrange the code so a ModuleScript is created and named `RoundUtils`.",
      lines: [
        "local moduleScript = Instance.new(\"ModuleScript\")",
        "moduleScript.Name = \"RoundUtils\"",
        "print(moduleScript.ClassName)",
      ],
      correctOrder: [0, 1, 2],
      explanation: "Create the module first, rename it next, then inspect its class.",
    },
  ],
  bugs: [
    {
      prompt: "Which version has the bug if the goal is to create a LocalScript?",
      versionA: "local clientScript = Instance.new(\"LocalScript\")",
      versionB: "local clientScript = Instance.new(\"Local Script\")",
      buggyVersion: "B",
      explanation: "The class name must match exactly. `Local Script` with a space is not the correct Roblox class name.",
    },
    {
      prompt: "Which version has the bug if the goal is to rename a Script to `ServerLogic`?",
      versionA: "local serverScript = Instance.new(\"Script\")\nserverScript.Name = \"ServerLogic\"",
      versionB: "local serverScript = Instance.new(\"Script\")\nserverScript.Value = \"ServerLogic\"",
      buggyVersion: "B",
      explanation: "Scripts use `Name` for renaming. They do not expose a generic `Value` field like Value objects do.",
    },
    {
      prompt: "Which version has the bug if the goal is to create a ModuleScript?",
      versionA: "local moduleScript = Instance.new(\"ModuleScript\")",
      versionB: "local moduleScript = ModuleScript.new()",
      buggyVersion: "B",
      explanation: "Roblox script objects are created with `Instance.new(\"ClassName\")`, not with `.new()` on the class name.",
    },
  ],
};

export const getServiceSpec: RobloxCodeConceptSpec = {
  concept: "getservice",
  title: "game:GetService",
  nodeType: "teaching",
  definitions: [
    {
      prompt: "What does `game:GetService(\"Players\")` return?",
      options: [
        "The Players service object",
        "A new player character model",
        "The Explorer panel",
        "A folder named Players in Workspace",
      ],
      correctIndex: 0,
      explanation: "`GetService` returns a Roblox service object by name, such as Players, TweenService, or ReplicatedStorage.",
    },
    {
      prompt: "Why do Roblox scripts often use `game:GetService()` instead of guessing where an object might be?",
      options: [
        "Because it gives direct access to services by their official name",
        "Because it creates Studio panels like Explorer and Properties",
        "Because it publishes the place to Roblox automatically",
        "Because it is the only way to rename parts in Workspace",
      ],
      correctIndex: 0,
      explanation: "`GetService` is the standard way to access services reliably by name inside the DataModel.",
    },
    {
      prompt: "Which line correctly gets TweenService in Roblox Lua?",
      options: [
        "local tweenService = game:GetService(\"TweenService\")",
        "local tweenService = TweenService.new()",
        "local tweenService = workspace.TweenService",
        "local tweenService = game.TweenService()",
      ],
      correctIndex: 0,
      explanation: "Services are accessed through `game:GetService(\"ServiceName\")` with a string and a colon call.",
    },
    {
      prompt: "What is the main purpose of `GetService` in Roblox scripts?",
      options: [
        "Accessing Roblox services like Players, ReplicatedStorage, and RunService",
        "Creating new Parts and Folders from class names",
        "Reopening panels from the View tab",
        "Transforming Parts with Move, Rotate, and Scale handles",
      ],
      correctIndex: 0,
      explanation: "`GetService` is for services, while `Instance.new` creates objects and Studio UI actions happen elsewhere.",
    },
  ],
  truths: [
    {
      prompt: "The call `game:GetService(\"Players\")` uses a colon because it is a method on `game`.",
      correct: true,
      explanation: "In Roblox Lua, `GetService` is called with `:` on `game` so the method receives the correct self object.",
      code: "local players = game:GetService(\"Players\")\nprint(players.Name)",
    },
    {
      prompt: "`GetService` can be used for common services like Players, RunService, TweenService, and ReplicatedStorage.",
      correct: true,
      explanation: "Those are all standard Roblox services that scripts commonly access through `game:GetService()`.",
    },
    {
      prompt: "`game:GetService(\"Players\")` returns the Explorer panel in Studio.",
      correct: false,
      explanation: "It returns the runtime Players service object, not a Studio panel.",
    },
    {
      prompt: "You should write `game.GetService(\"Players\")` without a colon in normal Roblox Lua.",
      correct: false,
      explanation: "The standard method call uses a colon: `game:GetService(\"Players\")`.",
      code: "local players = game:GetService(\"Players\")",
    },
  ],
  examples: [
    {
      mcOutputPrompt: "What does this print?",
      mcOutputCode: "local players = game:GetService(\"Players\")\nprint(players.ClassName)",
      mcOutputOptions: ["Players", "Player", "Folder", "Workspace"],
      mcOutputCorrectIndex: 0,
      mcOutputExplanation: "The Players service reports its class name as `Players`.",
      fillTypePrompt: "Type the service name so the code gets the Players service.",
      fillTypeCode: "local players = game:GetService(\"___\")",
      fillTypeAnswer: "Players",
      fillTypeExplanation: "The service name string must match the Roblox service you want to access.",
      fillTypeHint: "Use the service that manages connected player objects.",
      fillSelectPrompt: "Fill the blanks so the code gets TweenService and prints its name.",
      fillSelectCode: "local tweenService = game:GetService(\"___\")\nprint(tweenService.___)",
      fillSelectTokens: ["TweenService", "Name", "Parent", "Players"],
      fillSelectAnswer: ["TweenService", "Name"],
      fillSelectExplanation: "The service name is `TweenService`, and `Name` prints its service name text.",
      wordBankPrompt: "Build the line that gets ReplicatedStorage.",
      wordBankTokens: ["local", "replicatedStorage", "=", "game:GetService(\"ReplicatedStorage\")", "workspace", "print(replicatedStorage)"],
      wordBankAnswer: ["local", "replicatedStorage", "=", "game:GetService(\"ReplicatedStorage\")"],
      wordBankExplanation: "That line stores the ReplicatedStorage service in a local variable.",
      predictPrompt: "What does this print?",
      predictCode: "local tweenService = game:GetService(\"TweenService\")\nprint(tweenService.Name)",
      predictAnswer: "TweenService",
      predictExplanation: "The service returned is TweenService, so its `Name` property prints `TweenService`.",
    },
    {
      mcOutputPrompt: "What does this print?",
      mcOutputCode: "local replicatedStorage = game:GetService(\"ReplicatedStorage\")\nprint(replicatedStorage.ClassName)",
      mcOutputOptions: ["ReplicatedStorage", "Folder", "Storage", "Instance"],
      mcOutputCorrectIndex: 0,
      mcOutputExplanation: "The ReplicatedStorage service reports its class name as `ReplicatedStorage`.",
      fillTypePrompt: "Type the property name so this prints the service's class.",
      fillTypeCode: "local players = game:GetService(\"Players\")\nprint(players.___)",
      fillTypeAnswer: "ClassName",
      fillTypeExplanation: "`ClassName` is the property used to inspect the Roblox class of the returned service object.",
      fillSelectPrompt: "Fill the blanks so the code gets RunService and stores its name.",
      fillSelectCode: "local runService = game:GetService(\"___\")\nlocal serviceName = runService.___",
      fillSelectTokens: ["RunService", "Name", "Parent", "Players"],
      fillSelectAnswer: ["RunService", "Name"],
      fillSelectExplanation: "`RunService` is the service name string, and `Name` stores its display name.",
      wordBankPrompt: "Build the line that gets Players with `GetService`.",
      wordBankTokens: ["local", "players", "=", "game:GetService(\"Players\")", "workspace", "game.Players()"],
      wordBankAnswer: ["local", "players", "=", "game:GetService(\"Players\")"],
      wordBankExplanation: "That is the normal pattern for storing a service in a variable.",
      predictPrompt: "What does this print?",
      predictCode: "local runService = game:GetService(\"RunService\")\nprint(runService.Name)",
      predictAnswer: "RunService",
      predictExplanation: "The returned object is the RunService service, so its name prints accordingly.",
    },
    {
      mcOutputPrompt: "What does this print?",
      mcOutputCode: "local world = game:GetService(\"Workspace\")\nprint(world == workspace)",
      mcOutputOptions: ["true", "false", "Workspace", "nil"],
      mcOutputCorrectIndex: 0,
      mcOutputExplanation: "`game:GetService(\"Workspace\")` returns the same Workspace object as the global `workspace`.",
      fillTypePrompt: "Type the missing method name so the script reads Players correctly.",
      fillTypeCode: "local players = game:___(\"Players\")",
      fillTypeAnswer: "GetService",
      fillTypeExplanation: "`GetService` is the method used on `game` to access Roblox services by name.",
      fillSelectPrompt: "Fill the blanks so the code gets the Players service and prints its class.",
      fillSelectCode: "local players = game:___(\"___\")\nprint(players.ClassName)",
      fillSelectTokens: ["GetService", "Players", "Workspace", "Instance.new"],
      fillSelectAnswer: ["GetService", "Players"],
      fillSelectExplanation: "You call the `GetService` method and pass the service name string `Players`.",
      wordBankPrompt: "Build the expression that checks whether GetService for Workspace matches the global world reference.",
      wordBankTokens: ["game:GetService(\"Workspace\")", "==", "workspace", "=", "game.Players", "script"],
      wordBankAnswer: ["game:GetService(\"Workspace\")", "==", "workspace"],
      wordBankExplanation: "The expression is true because both sides refer to the same Workspace object.",
      predictPrompt: "What does this print?",
      predictCode: "local world = game:GetService(\"Workspace\")\nprint(world.Name)",
      predictAnswer: "Workspace",
      predictExplanation: "The service returned is Workspace, so its `Name` property prints `Workspace`.",
    },
    {
      mcOutputPrompt: "What does this print?",
      mcOutputCode: "local players = game:GetService(\"Players\")\nlocal replicatedStorage = game:GetService(\"ReplicatedStorage\")\nprint(players.Name ~= replicatedStorage.Name)",
      mcOutputOptions: ["true", "false", "Players", "ReplicatedStorage"],
      mcOutputCorrectIndex: 0,
      mcOutputExplanation: "The two services have different names, so the not-equal comparison prints `true`.",
      fillTypePrompt: "Type the service name so the code gets ReplicatedStorage.",
      fillTypeCode: "local replicatedStorage = game:GetService(\"___\")",
      fillTypeAnswer: "ReplicatedStorage",
      fillTypeExplanation: "You access ReplicatedStorage by passing its service name string into `GetService`.",
      fillSelectPrompt: "Fill the blanks so the code gets Players and prints its name.",
      fillSelectCode: "local players = game:GetService(\"___\")\nprint(players.___)",
      fillSelectTokens: ["Players", "Name", "ClassName", "Workspace"],
      fillSelectAnswer: ["Players", "Name"],
      fillSelectExplanation: "`Players` selects the service, and `Name` prints the service name text.",
      wordBankPrompt: "Build the line that gets TweenService with `GetService`.",
      wordBankTokens: ["local", "tweenService", "=", "game:GetService(\"TweenService\")", "workspace", "TweenService.new()"],
      wordBankAnswer: ["local", "tweenService", "=", "game:GetService(\"TweenService\")"],
      wordBankExplanation: "That line is the standard service lookup pattern for TweenService.",
      predictPrompt: "What does this print?",
      predictCode: "local players = game:GetService(\"Players\")\nprint(players.Name)",
      predictAnswer: "Players",
      predictExplanation: "The Players service object's `Name` property prints `Players`.",
    },
  ],
  arrange: [
    {
      prompt: "Arrange the code so the Players service is fetched and its class name is printed.",
      lines: [
        "local players = game:GetService(\"Players\")",
        "local kind = players.ClassName",
        "print(kind)",
      ],
      correctOrder: [0, 1, 2],
      explanation: "First fetch the service, then read its class, then print the result.",
    },
    {
      prompt: "Arrange the code so TweenService is fetched and its name is printed.",
      lines: [
        "local tweenService = game:GetService(\"TweenService\")",
        "local serviceName = tweenService.Name",
        "print(serviceName)",
      ],
      correctOrder: [0, 1, 2],
      explanation: "Get the service first, then read its Name property, then print it.",
    },
    {
      prompt: "Arrange the code so ReplicatedStorage is fetched and compared with Players.",
      lines: [
        "local players = game:GetService(\"Players\")",
        "local replicatedStorage = game:GetService(\"ReplicatedStorage\")",
        "print(players.Name ~= replicatedStorage.Name)",
      ],
      correctOrder: [0, 1, 2],
      explanation: "Fetch both services before comparing their names.",
    },
  ],
  bugs: [
    {
      prompt: "Which version has the bug if the goal is to get the Players service?",
      versionA: "local players = game:GetService(\"Players\")",
      versionB: "local players = game.GetService(\"Players\")",
      buggyVersion: "B",
      explanation: "The standard method call uses a colon: `game:GetService(...)`. Version B drops the colon.",
    },
    {
      prompt: "Which version has the bug if the goal is to get TweenService?",
      versionA: "local tweenService = game:GetService(\"TweenService\")",
      versionB: "local tweenService = game:GetService(\"Tween Service\")",
      buggyVersion: "B",
      explanation: "The service name must match exactly. `TweenService` has no space in the service string.",
    },
    {
      prompt: "Which version has the bug if the goal is to print the Players service name?",
      versionA: "local players = game:GetService(\"Players\")\nprint(players.Name)",
      versionB: "local players = game:GetService(\"Players\")\nprint(players.Parent)",
      buggyVersion: "B",
      explanation: "Version B prints the service parent instead of the service name. `players.Name` is the correct property for this goal.",
    },
  ],
};
