"use client";

import { defineCommonTheme } from "@/lib/themes/shared";

export const COMMON_THEME_IDS = [
  "midnight",
  "crimson",
  "forest",
  "slate",
  "dusk",
  "ember",
  "arctic",
  "sand",
  "rose",
  "obsidian",
  "verdant",
  "cobalt",
  "copper",
  "lilac",
  "gold",
  "onyx",
  "coral",
  "teal",
  "burgundy",
  "chrome",
] as const;

export type CommonThemeId = typeof COMMON_THEME_IDS[number];

export const COMMON_THEMES = {
  midnight: defineCommonTheme({
    id: "midnight",
    name: "Midnight",
    description: "Deep navy calm with crisp white lesson markers.",
    shopDescription: "A clean midnight route with moonlit nodes and a silver thread connecting each step.",
    previewColor: "#0F172A",
    previewUnitTitle: "Moonrise Walk",
    accent: "#E2E8F0",
    surface: "#0F172A",
    text: "#F8FAFC",
    node: "#F8FAFC",
    nodeDark: "#CBD5E1",
    trail: "#94A3B8",
    background: "linear-gradient(180deg,#0B1120 0%,#111C32 100%)",
    chestSkin: "default_chest",
    trailEffect: "steady_glow",
    particleEffect: "default_nodes",
  }),
  crimson: defineCommonTheme({
    id: "crimson",
    name: "Crimson",
    description: "Dark red depth with cream nodes and a rose-gold thread.",
    shopDescription: "Velvet reds, warm lesson markers, and a polished rose-gold connector.",
    previewColor: "#7F1D1D",
    previewUnitTitle: "Red Velvet Route",
    accent: "#F5D0C5",
    surface: "#7F1D1D",
    text: "#FFF7ED",
    node: "#FDE68A",
    nodeDark: "#B45309",
    trail: "#FB7185",
    background: "linear-gradient(180deg,#6B0F1A 0%,#8A1E2F 100%)",
    chestSkin: "default_chest",
    trailEffect: "steady_glow",
    particleEffect: "sparkles",
  }),
  forest: defineCommonTheme({
    id: "forest",
    name: "Forest",
    description: "Deep green shade with pale nodes and earthy trail light.",
    shopDescription: "A grounded forest path with soft greens and a natural earthy connector.",
    previewColor: "#14532D",
    previewUnitTitle: "Canopy Run",
    accent: "#DCFCE7",
    surface: "#14532D",
    text: "#F0FDF4",
    node: "#A7F3D0",
    nodeDark: "#166534",
    trail: "#65A30D",
    background: "linear-gradient(180deg,#123524 0%,#1B5A3C 100%)",
    chestSkin: "classic_treasure",
    trailEffect: "vine",
    particleEffect: "default_nodes",
  }),
  slate: defineCommonTheme({
    id: "slate",
    name: "Slate",
    description: "Cool gray pathing with blue-gray energy under each lesson.",
    shopDescription: "Smooth stone-gray surfaces with quiet white nodes and a steel-blue trail.",
    previewColor: "#334155",
    previewUnitTitle: "Stone Stack",
    accent: "#E2E8F0",
    surface: "#334155",
    text: "#F8FAFC",
    node: "#E2E8F0",
    nodeDark: "#94A3B8",
    trail: "#64748B",
    background: "linear-gradient(180deg,#253244 0%,#3A4A61 100%)",
    chestSkin: "default_chest",
    trailEffect: "steady_glow",
    particleEffect: "default_nodes",
  }),
  dusk: defineCommonTheme({
    id: "dusk",
    name: "Dusk",
    description: "Muted purple haze with lavender lesson lights.",
    shopDescription: "Soft violet dusk tones and a gentle lavender lesson route.",
    previewColor: "#5B427C",
    previewUnitTitle: "Evening Drift",
    accent: "#E9D5FF",
    surface: "#5B427C",
    text: "#FAF5FF",
    node: "#D8B4FE",
    nodeDark: "#7E22CE",
    trail: "#C084FC",
    background: "linear-gradient(180deg,#4B356A 0%,#73518E 100%)",
    chestSkin: "magic_lantern",
    trailEffect: "aurora",
    particleEffect: "sparkles",
  }),
  ember: defineCommonTheme({
    id: "ember",
    name: "Ember",
    description: "Dark charcoal with warm orange lesson heat.",
    shopDescription: "A charcoal route with amber nodes and a molten ember glow.",
    previewColor: "#2F1B10",
    previewUnitTitle: "Ashfall Line",
    accent: "#FED7AA",
    surface: "#2F1B10",
    text: "#FFF7ED",
    node: "#FB923C",
    nodeDark: "#C2410C",
    trail: "#F59E0B",
    background: "linear-gradient(180deg,#1C1917 0%,#3A2417 100%)",
    chestSkin: "default_chest",
    trailEffect: "steady_glow",
    particleEffect: "embers",
  }),
  arctic: defineCommonTheme({
    id: "arctic",
    name: "Arctic",
    description: "Ice-white air with pale blue nodes and a frost-bright trail.",
    shopDescription: "An airy arctic palette with frosted nodes and clean polar light.",
    previewColor: "#E0F2FE",
    previewUnitTitle: "Glacier Walk",
    accent: "#60A5FA",
    surface: "#E0F2FE",
    text: "#0F172A",
    node: "#BAE6FD",
    nodeDark: "#60A5FA",
    trail: "#93C5FD",
    background: "linear-gradient(180deg,#F8FCFF 0%,#DFF3FF 100%)",
    chestSkin: "ice_block_chest",
    trailEffect: "ice_growth",
    particleEffect: "snowflakes",
  }),
  sand: defineCommonTheme({
    id: "sand",
    name: "Sand",
    description: "Warm beige dunes with terracotta path energy.",
    shopDescription: "Sun-baked beige surfaces, clay-toned nodes, and a terracotta route line.",
    previewColor: "#D6B88C",
    previewUnitTitle: "Dune Route",
    accent: "#F59E0B",
    surface: "#D6B88C",
    text: "#422006",
    node: "#FCD34D",
    nodeDark: "#B45309",
    trail: "#C2410C",
    background: "linear-gradient(180deg,#F4E3C3 0%,#DFC08D 100%)",
    chestSkin: "classic_treasure",
    trailEffect: "expedition_dots",
    particleEffect: "gold_dust",
  }),
  rose: defineCommonTheme({
    id: "rose",
    name: "Rose",
    description: "Blush pink softness with bright white lesson markers.",
    shopDescription: "A romantic blush route with pearly nodes and a warm rose connector.",
    previewColor: "#F9A8D4",
    previewUnitTitle: "Petal Path",
    accent: "#EC4899",
    surface: "#FBCFE8",
    text: "#831843",
    node: "#FFFFFF",
    nodeDark: "#EC4899",
    trail: "#FB7185",
    background: "linear-gradient(180deg,#FDE7F2 0%,#FBCFE8 100%)",
    chestSkin: "magic_lantern",
    trailEffect: "steady_glow",
    particleEffect: "sparkles",
  }),
  obsidian: defineCommonTheme({
    id: "obsidian",
    name: "Obsidian",
    description: "Pure black minimalism with barely-there charcoal progress lines.",
    shopDescription: "A stripped-back obsidian route where the path glows only when it matters.",
    previewColor: "#09090B",
    previewUnitTitle: "Blackline Route",
    accent: "#A1A1AA",
    surface: "#09090B",
    text: "#F4F4F5",
    node: "#27272A",
    nodeDark: "#18181B",
    trail: "#3F3F46",
    background: "linear-gradient(180deg,#020202 0%,#111114 100%)",
    chestSkin: "default_chest",
    trailEffect: "default_trail",
    particleEffect: "default_nodes",
  }),
  verdant: defineCommonTheme({
    id: "verdant",
    name: "Verdant",
    description: "Bright spring greens with crisp white lesson buttons.",
    shopDescription: "Fresh meadow greens and a bright lime connector that feels full of life.",
    previewColor: "#22C55E",
    previewUnitTitle: "Bloom Lane",
    accent: "#FFFFFF",
    surface: "#22C55E",
    text: "#F0FDF4",
    node: "#86EFAC",
    nodeDark: "#16A34A",
    trail: "#A3E635",
    background: "linear-gradient(180deg,#1EB855 0%,#34D399 100%)",
    chestSkin: "classic_treasure",
    trailEffect: "vine",
    particleEffect: "default_nodes",
  }),
  cobalt: defineCommonTheme({
    id: "cobalt",
    name: "Cobalt",
    description: "Rich blue depth with electric sky-blue progress.",
    shopDescription: "A bold cobalt route charged with bright blue lesson energy.",
    previewColor: "#1D4ED8",
    previewUnitTitle: "Blue Current",
    accent: "#BFDBFE",
    surface: "#1D4ED8",
    text: "#EFF6FF",
    node: "#60A5FA",
    nodeDark: "#1E40AF",
    trail: "#38BDF8",
    background: "linear-gradient(180deg,#133FBC 0%,#2563EB 100%)",
    chestSkin: "default_chest",
    trailEffect: "steady_glow",
    particleEffect: "sparkles",
  }),
  copper: defineCommonTheme({
    id: "copper",
    name: "Copper",
    description: "Warm brown metal with bronze lesson lights and rusted trail glow.",
    shopDescription: "A forged copper route with polished bronze nodes and a rust-red connector.",
    previewColor: "#92400E",
    previewUnitTitle: "Forge Mile",
    accent: "#FED7AA",
    surface: "#92400E",
    text: "#FFF7ED",
    node: "#D97706",
    nodeDark: "#7C2D12",
    trail: "#C2410C",
    background: "linear-gradient(180deg,#6B3410 0%,#A16207 100%)",
    chestSkin: "classic_treasure",
    trailEffect: "steady_glow",
    particleEffect: "embers",
  }),
  lilac: defineCommonTheme({
    id: "lilac",
    name: "Lilac",
    description: "Soft purple haze with bright white lesson markers.",
    shopDescription: "A light lilac route with pastel lesson nodes and a smooth violet connector.",
    previewColor: "#C084FC",
    previewUnitTitle: "Lilac Lane",
    accent: "#8B5CF6",
    surface: "#E9D5FF",
    text: "#581C87",
    node: "#FFFFFF",
    nodeDark: "#A855F7",
    trail: "#C084FC",
    background: "linear-gradient(180deg,#F5E8FF 0%,#E9D5FF 100%)",
    chestSkin: "magic_lantern",
    trailEffect: "aurora",
    particleEffect: "sparkles",
  }),
  gold: defineCommonTheme({
    id: "gold",
    name: "Gold",
    description: "Warm yellow daylight with amber connectors and bright white nodes.",
    shopDescription: "A sunny golden path with rich amber progress lines and polished lesson markers.",
    previewColor: "#FBBF24",
    previewUnitTitle: "Sunlit Road",
    accent: "#FFFFFF",
    surface: "#FBBF24",
    text: "#78350F",
    node: "#FDE68A",
    nodeDark: "#D97706",
    trail: "#F59E0B",
    background: "linear-gradient(180deg,#FDE68A 0%,#FBBF24 100%)",
    chestSkin: "default_chest",
    trailEffect: "steady_glow",
    particleEffect: "sparkles",
  }),
  onyx: defineCommonTheme({
    id: "onyx",
    name: "Onyx",
    description: "Very dark gray with a matte, low-light node treatment.",
    shopDescription: "A matte onyx route with restrained dark nodes and a quiet graphite line.",
    previewColor: "#18181B",
    previewUnitTitle: "Shadow Route",
    accent: "#A1A1AA",
    surface: "#18181B",
    text: "#FAFAFA",
    node: "#27272A",
    nodeDark: "#3F3F46",
    trail: "#52525B",
    background: "linear-gradient(180deg,#121214 0%,#1E1E22 100%)",
    chestSkin: "default_chest",
    trailEffect: "default_trail",
    particleEffect: "default_nodes",
  }),
  coral: defineCommonTheme({
    id: "coral",
    name: "Coral",
    description: "Bright coral warmth with pink route light and white nodes.",
    shopDescription: "A playful coral path with bright nodes and a sunlit pink connector.",
    previewColor: "#FB7185",
    previewUnitTitle: "Coral Bloom",
    accent: "#FFFFFF",
    surface: "#FB7185",
    text: "#FFF7ED",
    node: "#FDA4AF",
    nodeDark: "#E11D48",
    trail: "#F472B6",
    background: "linear-gradient(180deg,#FB7185 0%,#F97393 100%)",
    chestSkin: "clam_chest",
    trailEffect: "bubble_stream",
    particleEffect: "bubbles",
  }),
  teal: defineCommonTheme({
    id: "teal",
    name: "Teal",
    description: "Deep teal waters with mint lesson nodes and seafoam progress.",
    shopDescription: "Oceanic teal surfaces, bright mint lesson lights, and a seafoam connector.",
    previewColor: "#0F766E",
    previewUnitTitle: "Sea Glass Run",
    accent: "#A7F3D0",
    surface: "#0F766E",
    text: "#ECFEFF",
    node: "#5EEAD4",
    nodeDark: "#115E59",
    trail: "#2DD4BF",
    background: "linear-gradient(180deg,#0F766E 0%,#155E75 100%)",
    chestSkin: "clam_chest",
    trailEffect: "bubble_stream",
    particleEffect: "bubbles",
  }),
  burgundy: defineCommonTheme({
    id: "burgundy",
    name: "Burgundy",
    description: "Wine-dark atmosphere with dusty rose nodes and a maroon route.",
    shopDescription: "A polished burgundy path with dusty rose highlights and a rich maroon connector.",
    previewColor: "#6B1529",
    previewUnitTitle: "Velvet Turn",
    accent: "#FBCFE8",
    surface: "#6B1529",
    text: "#FFF1F2",
    node: "#FDA4AF",
    nodeDark: "#9F1239",
    trail: "#BE123C",
    background: "linear-gradient(180deg,#5E1022 0%,#7A1830 100%)",
    chestSkin: "default_chest",
    trailEffect: "steady_glow",
    particleEffect: "sparkles",
  }),
  chrome: defineCommonTheme({
    id: "chrome",
    name: "Chrome",
    description: "Silver-metal sheen with mirror-bright lesson nodes.",
    shopDescription: "A reflective chrome route with polished silver gradients and a mirrored connector.",
    previewColor: "#CBD5E1",
    previewUnitTitle: "Mirror Lane",
    accent: "#FFFFFF",
    surface: "#CBD5E1",
    text: "#0F172A",
    node: "#FFFFFF",
    nodeDark: "#94A3B8",
    trail: "#E2E8F0",
    background: "linear-gradient(180deg,#E5E7EB 0%,#CBD5E1 100%)",
    chestSkin: "default_chest",
    trailEffect: "steady_glow",
    particleEffect: "sparkles",
  }),
} satisfies Record<CommonThemeId, ReturnType<typeof defineCommonTheme<CommonThemeId>>>;
