"use client";

import { defineEpicTheme } from "@/lib/themes/shared";

export const EPIC_THEME_IDS = [
  "cyberpunk_city",
  "haunted_mansion",
  "deep_ocean",
  "samurai_dojo",
  "ancient_egypt",
  "arctic_tundra",
  "jungle_temple",
  "lava_world",
  "retro_arcade",
  "space_station",
] as const;

export type EpicThemeId = typeof EPIC_THEME_IDS[number];

export const EPIC_THEMES = {
  cyberpunk_city: defineEpicTheme({
    id: "cyberpunk_city",
    name: "Cyberpunk City",
    description: "A living neon district where current races through every connector.",
    shopDescription: "Electric hex nodes, neon signage, and current-driven trails turn the path into a city circuit.",
    previewColor: "#22D3EE",
    previewUnitTitle: "Voltage Ward",
    accent: "#22D3EE",
    surface: "#09090F",
    text: "#ECFEFF",
    node: "#0EA5E9",
    nodeDark: "#164E63",
    trail: "#8B5CF6",
    background: "linear-gradient(180deg,#050816 0%,#0F172A 100%)",
    overlay: "radial-gradient(circle at 80% 16%, rgba(236,72,153,0.18), transparent 24%)",
    bannerPattern: "linear-gradient(90deg,transparent 0%,rgba(34,211,238,0.14) 48%,transparent 100%)",
    chestSkin: "vault_door",
    trailEffect: "electric_current",
    particleEffect: "sparkles",
    nodeShape: "hex",
    ambientEffects: [
      { kind: "scanlines", opacity: 0.12 },
      { kind: "glints", color: "#22D3EE", count: 10, durationMs: 4200 },
      { kind: "light-rays", color: "#EC4899", opacity: 0.12 },
    ],
  }),
  haunted_mansion: defineEpicTheme({
    id: "haunted_mansion",
    name: "Haunted Mansion",
    description: "Drifting fog, cracked stone nodes, and spectral movement in the dark.",
    shopDescription: "A fog-choked mansion route with eerie wisps, gothic banners, and occasional bats crossing the scene.",
    previewColor: "#A78BFA",
    previewUnitTitle: "Wraith Wing",
    accent: "#A78BFA",
    surface: "#111827",
    text: "#F5F3FF",
    node: "#4C1D95",
    nodeDark: "#14532D",
    trail: "#94A3B8",
    background: "linear-gradient(180deg,#0B1020 0%,#171923 100%)",
    chestSkin: "coffin_chest",
    trailEffect: "default_trail",
    particleEffect: "wisps",
    nodeShape: "arch",
    ambientEffects: [
      { kind: "fog", color: "#CBD5E1", opacity: 0.18, durationMs: 10000 },
      { kind: "wisps", color: "#A78BFA", count: 8, opacity: 0.16 },
      { kind: "bats", color: "#94A3B8", durationMs: 14000 },
    ],
  }),
  deep_ocean: defineEpicTheme({
    id: "deep_ocean",
    name: "Deep Ocean",
    description: "Porthole nodes, caustic light, and bubbles drifting through a dark sea.",
    shopDescription: "Slow underwater caustics, porthole nodes, and a bubble-stream trail make the route feel submerged.",
    previewColor: "#0EA5E9",
    previewUnitTitle: "Submarine Reach",
    accent: "#67E8F9",
    surface: "#082F49",
    text: "#ECFEFF",
    node: "#0EA5E9",
    nodeDark: "#155E75",
    trail: "#22D3EE",
    background: "linear-gradient(180deg,#082F49 0%,#0B4B6E 100%)",
    chestSkin: "clam_chest",
    trailEffect: "bubble_stream",
    particleEffect: "bubbles",
    nodeShape: "circle",
    ambientEffects: [
      { kind: "caustics", color: "#E0F2FE", opacity: 0.16 },
      { kind: "bubbles", color: "#E0F2FE", count: 14, opacity: 0.2 },
      { kind: "fish", color: "#93C5FD", durationMs: 18000 },
    ],
  }),
  samurai_dojo: defineEpicTheme({
    id: "samurai_dojo",
    name: "Samurai Dojo",
    description: "Brushstroke nodes, hanging-scroll banners, and petals across warm timber.",
    shopDescription: "An ink-wash dojo path with brushstroke borders, drawn trails, and drifting cherry blossoms.",
    previewColor: "#DC2626",
    previewUnitTitle: "Lantern Court",
    accent: "#DC2626",
    surface: "#F5EAD9",
    text: "#450A0A",
    node: "#F97316",
    nodeDark: "#991B1B",
    trail: "#B91C1C",
    background: "linear-gradient(180deg,#F9F0E4 0%,#E9D7BD 100%)",
    chestSkin: "lacquered_box",
    trailEffect: "ink_stroke",
    particleEffect: "ink_splash",
    nodeShape: "circle",
    ambientEffects: [
      { kind: "petals", color: "#F9A8D4", count: 12, opacity: 0.2 },
      { kind: "mist", color: "#94A3B8", opacity: 0.1 },
    ],
  }),
  ancient_egypt: defineEpicTheme({
    id: "ancient_egypt",
    name: "Ancient Egypt",
    description: "Sun-warmed stone, hieroglyph rings, and gold dust rising from each lesson.",
    shopDescription: "Heat-haze air, carved banners, and scarab-lined routes turn the path into an ancient procession.",
    previewColor: "#D97706",
    previewUnitTitle: "Sun Court",
    accent: "#F59E0B",
    surface: "#F5D9A6",
    text: "#78350F",
    node: "#FBBF24",
    nodeDark: "#B45309",
    trail: "#EAB308",
    background: "linear-gradient(180deg,#F8E1AD 0%,#E7BE6B 100%)",
    chestSkin: "sarcophagus_chest",
    trailEffect: "scarab_track",
    particleEffect: "gold_dust",
    nodeShape: "circle",
    ambientEffects: [
      { kind: "heat-haze", color: "#FDE68A", opacity: 0.18 },
      { kind: "dust", color: "#F59E0B", count: 12, opacity: 0.14 },
    ],
  }),
  arctic_tundra: defineEpicTheme({
    id: "arctic_tundra",
    name: "Arctic Tundra",
    description: "Frosted nodes, drifting snow, and a glowing ice route across the cold.",
    shopDescription: "Snowfall, glassy nodes, and an aurora-kissed ice line make the route feel frozen alive.",
    previewColor: "#93C5FD",
    previewUnitTitle: "Frost Divide",
    accent: "#BFDBFE",
    surface: "#E0F2FE",
    text: "#0F172A",
    node: "#BAE6FD",
    nodeDark: "#60A5FA",
    trail: "#38BDF8",
    background: "linear-gradient(180deg,#F8FCFF 0%,#DCEFFD 100%)",
    chestSkin: "ice_block_chest",
    trailEffect: "ice_growth",
    particleEffect: "snowflakes",
    nodeShape: "crystal",
    ambientEffects: [
      { kind: "snow", color: "#FFFFFF", count: 20, opacity: 0.22 },
      { kind: "aurora", color: "#34D399", colorSecondary: "#60A5FA", opacity: 0.14 },
    ],
  }),
  jungle_temple: defineEpicTheme({
    id: "jungle_temple",
    name: "Jungle Temple",
    description: "Mossy stone, roots, and fireflies woven into a hidden ruin.",
    shopDescription: "Layered jungle shadows, rooted connectors, and firefly-lit stone nodes create a living ruin.",
    previewColor: "#166534",
    previewUnitTitle: "Temple Canopy",
    accent: "#86EFAC",
    surface: "#0F3D2E",
    text: "#F0FDF4",
    node: "#4ADE80",
    nodeDark: "#166534",
    trail: "#65A30D",
    background: "linear-gradient(180deg,#0F3D2E 0%,#1F5A3E 100%)",
    chestSkin: "stone_idol_chest",
    trailEffect: "root_vine",
    particleEffect: "fireflies",
    nodeShape: "circle",
    ambientEffects: [
      { kind: "fireflies", color: "#FDE68A", count: 12, opacity: 0.2 },
      { kind: "mist", color: "#022C22", opacity: 0.1 },
      { kind: "leaves", color: "#4ADE80", count: 8, opacity: 0.14 },
    ],
  }),
  lava_world: defineEpicTheme({
    id: "lava_world",
    name: "Lava World",
    description: "Dark stone and molten fractures with ember smoke on every finish.",
    shopDescription: "Cracked basalt, lava-glow edges, and ember bursts turn the path into a molten gauntlet.",
    previewColor: "#F97316",
    previewUnitTitle: "Molten Rift",
    accent: "#F97316",
    surface: "#1C1917",
    text: "#FFF7ED",
    node: "#FB923C",
    nodeDark: "#B91C1C",
    trail: "#F59E0B",
    background: "linear-gradient(180deg,#171717 0%,#2D140B 100%)",
    overlay: "radial-gradient(circle at 50% 100%, rgba(249,115,22,0.2), transparent 36%)",
    chestSkin: "volcanic_obsidian",
    trailEffect: "lava_flow",
    particleEffect: "embers",
    nodeShape: "circle",
    ambientEffects: [
      { kind: "embers", color: "#F97316", count: 12, opacity: 0.2 },
      { kind: "heat-haze", color: "#FB923C", opacity: 0.12 },
    ],
  }),
  retro_arcade: defineEpicTheme({
    id: "retro_arcade",
    name: "Retro Arcade",
    description: "CRT glow, pixel explosions, and dotted prize-line progress.",
    shopDescription: "Scanlines, pixel nodes, and sprite-like bursts make the path feel like an arcade cabinet.",
    previewColor: "#F97316",
    previewUnitTitle: "Bonus Floor",
    accent: "#FACC15",
    surface: "#111827",
    text: "#FFF7ED",
    node: "#F97316",
    nodeDark: "#C2410C",
    trail: "#FACC15",
    background: "linear-gradient(180deg,#0F172A 0%,#1E293B 100%)",
    bannerPattern: "repeating-linear-gradient(180deg,rgba(255,255,255,0.05) 0px,rgba(255,255,255,0.05) 2px,transparent 2px,transparent 6px)",
    chestSkin: "arcade_prize_chest",
    trailEffect: "pixel",
    particleEffect: "pixel_burst",
    nodeShape: "pixel",
    ambientEffects: [
      { kind: "scanlines", opacity: 0.16 },
      { kind: "pixel-walker", color: "#FACC15", durationMs: 12000 },
    ],
  }),
  space_station: defineEpicTheme({
    id: "space_station",
    name: "Space Station",
    description: "Parallax stars, orbital nodes, and a constellation route through deep space.",
    shopDescription: "Slow-moving star layers, orbiting node rings, and mission-panel banners turn the path into a station briefing.",
    previewColor: "#8B5CF6",
    previewUnitTitle: "Mission Ring",
    accent: "#C4B5FD",
    surface: "#050816",
    text: "#F5F3FF",
    node: "#6366F1",
    nodeDark: "#312E81",
    trail: "#38BDF8",
    background: "linear-gradient(180deg,#020617 0%,#0F172A 100%)",
    chestSkin: "alien_pod",
    trailEffect: "constellation",
    particleEffect: "supernova",
    nodeShape: "orbital",
    ambientEffects: [
      { kind: "stars", color: "#F8FAFC", count: 60, opacity: 0.18 },
      { kind: "comet", color: "#93C5FD", durationMs: 14000 },
      { kind: "orbit-rings", color: "#C4B5FD", opacity: 0.12 },
    ],
  }),
} satisfies Record<EpicThemeId, ReturnType<typeof defineEpicTheme<EpicThemeId>>>;
