"use client";

import { defineLegendaryTheme } from "@/lib/themes/shared";

export const LEGENDARY_THEME_IDS = [
  "enchanted_forest",
  "clockwork_empire",
  "storm_chaser",
  "crystal_cavern",
  "living_ocean_surface",
  "the_dreamscape",
] as const;

export type LegendaryThemeId = typeof LEGENDARY_THEME_IDS[number];

export const LEGENDARY_THEMES = {
  enchanted_forest: defineLegendaryTheme({
    id: "enchanted_forest",
    name: "Enchanted Forest",
    description: "A living forest path with drifting mist, fireflies, and glowing roots.",
    shopDescription: "Parallax leaves, bioluminescent completed nodes, and a mossy forest trail make the route feel alive.",
    previewColor: "#166534",
    previewUnitTitle: "Moonroot Trail",
    accent: "#86EFAC",
    surface: "#0C2F1C",
    text: "#F0FDF4",
    node: "#4ADE80",
    nodeDark: "#14532D",
    trail: "#65A30D",
    background: "linear-gradient(180deg,#082414 0%,#124C2B 100%)",
    chestSkin: "vine_overgrown_chest",
    trailEffect: "forest_path",
    particleEffect: "fireflies",
    nodeShape: "circle",
    ambientEffects: [
      { kind: "fireflies", color: "#FDE68A", count: 12, opacity: 0.22 },
      { kind: "leaves", color: "#86EFAC", count: 12, opacity: 0.14 },
      { kind: "mist", color: "#DCFCE7", opacity: 0.12, durationMs: 12000 },
      { kind: "glints", color: "#86EFAC", count: 6, opacity: 0.12 },
    ],
  }),
  clockwork_empire: defineLegendaryTheme({
    id: "clockwork_empire",
    name: "Clockwork Empire",
    description: "Brass gears turn behind every node as the path hums like a machine.",
    shopDescription: "Rotating gears, ticker motion, and brass-plated nodes make the whole route feel engineered.",
    previewColor: "#B45309",
    previewUnitTitle: "Empire Works",
    accent: "#F59E0B",
    surface: "#422006",
    text: "#FFF7ED",
    node: "#FBBF24",
    nodeDark: "#B45309",
    trail: "#F97316",
    background: "linear-gradient(180deg,#2E1606 0%,#593214 100%)",
    chestSkin: "clockwork_mechanism",
    trailEffect: "gear_track",
    particleEffect: "sparkles",
    nodeShape: "hex",
    ambientEffects: [
      { kind: "gears", color: "#FBBF24", count: 5, opacity: 0.18 },
      { kind: "embers", color: "#FDBA74", count: 8, opacity: 0.14 },
      { kind: "light-rays", color: "#FDE68A", opacity: 0.1 },
    ],
  }),
  storm_chaser: defineLegendaryTheme({
    id: "storm_chaser",
    name: "Storm Chaser",
    description: "Wind, rain, and lightning animate a stormfront across the path.",
    shopDescription: "Rolling storm clouds, crackling node rings, and lightning-strike connectors keep the route charged.",
    previewColor: "#94A3B8",
    previewUnitTitle: "Thunder Lane",
    accent: "#93C5FD",
    surface: "#111827",
    text: "#F8FAFC",
    node: "#60A5FA",
    nodeDark: "#334155",
    trail: "#38BDF8",
    background: "linear-gradient(180deg,#0F172A 0%,#1F2937 100%)",
    chestSkin: "storm_glass_chest",
    trailEffect: "lightning_zigzag",
    particleEffect: "storm_shock",
    nodeShape: "circle",
    ambientEffects: [
      { kind: "rain", color: "#E0F2FE", count: 24, opacity: 0.16 },
      { kind: "mist", color: "#94A3B8", opacity: 0.12, durationMs: 9000 },
      { kind: "light-rays", color: "#E2E8F0", opacity: 0.08 },
    ],
  }),
  crystal_cavern: defineLegendaryTheme({
    id: "crystal_cavern",
    name: "Crystal Cavern",
    description: "Bioluminescent crystals pulse at the edges while light refracts through the route.",
    shopDescription: "Glowing crystal clusters, refracted bridges, and slow cave sparkle make the path feel enchanted underground.",
    previewColor: "#8B5CF6",
    previewUnitTitle: "Crystal Span",
    accent: "#C4B5FD",
    surface: "#1E1B4B",
    text: "#F5F3FF",
    node: "#A78BFA",
    nodeDark: "#6D28D9",
    trail: "#60A5FA",
    background: "linear-gradient(180deg,#0F0D2C 0%,#231A58 100%)",
    chestSkin: "geode",
    trailEffect: "crystal_bridge",
    particleEffect: "crystal_shards",
    nodeShape: "crystal",
    ambientEffects: [
      { kind: "glints", color: "#C4B5FD", count: 12, opacity: 0.18 },
      { kind: "mist", color: "#60A5FA", opacity: 0.08 },
      { kind: "light-rays", color: "#93C5FD", opacity: 0.12 },
    ],
  }),
  living_ocean_surface: defineLegendaryTheme({
    id: "living_ocean_surface",
    name: "Living Ocean Surface",
    description: "The whole path sways like water, with wakes, foam, and drifting sunlight.",
    shopDescription: "Wave motion, buoy-like nodes, wake trails, and subtle sea life make the route feel like open water.",
    previewColor: "#0EA5E9",
    previewUnitTitle: "Sunwake Reach",
    accent: "#67E8F9",
    surface: "#083344",
    text: "#ECFEFF",
    node: "#38BDF8",
    nodeDark: "#0F766E",
    trail: "#22D3EE",
    background: "linear-gradient(180deg,#082F49 0%,#0C607D 100%)",
    chestSkin: "sunken_treasure_chest",
    trailEffect: "wake",
    particleEffect: "foam_burst",
    nodeShape: "circle",
    ambientEffects: [
      { kind: "waves", color: "#E0F2FE", opacity: 0.16 },
      { kind: "fish", color: "#93C5FD", durationMs: 16000 },
      { kind: "glints", color: "#FFFFFF", count: 6, opacity: 0.16 },
      { kind: "bubbles", color: "#E0F2FE", count: 10, opacity: 0.14 },
    ],
  }),
  the_dreamscape: defineLegendaryTheme({
    id: "the_dreamscape",
    name: "The Dreamscape",
    description: "Pastel clouds, levitating nodes, and gentle starlight create a floating world.",
    shopDescription: "Shifting pastel skies, levitating crystal nodes, and a rainbow bridge turn the route into a dream.",
    previewColor: "#C084FC",
    previewUnitTitle: "Cloudstep Field",
    accent: "#F9A8D4",
    surface: "#2B1640",
    text: "#FFF7FF",
    node: "#D8B4FE",
    nodeDark: "#8B5CF6",
    trail: "#93C5FD",
    background: "linear-gradient(180deg,#261438 0%,#4A2A68 100%)",
    chestSkin: "dream_box",
    trailEffect: "dream_ribbon",
    particleEffect: "dream_stars",
    nodeShape: "orbital",
    ambientEffects: [
      { kind: "aurora", color: "#F9A8D4", colorSecondary: "#93C5FD", opacity: 0.18 },
      { kind: "stars", color: "#FFFFFF", count: 44, opacity: 0.14 },
      { kind: "shooting-stars", color: "#FDE68A", durationMs: 15000 },
      { kind: "mist", color: "#E9D5FF", opacity: 0.12 },
    ],
  }),
} satisfies Record<LegendaryThemeId, ReturnType<typeof defineLegendaryTheme<LegendaryThemeId>>>;
