"use client";

import { defineRareTheme } from "@/lib/themes/shared";

export const RARE_THEME_IDS = [
  "neon_city",
  "blueprint",
  "comic_book",
  "paper_craft",
  "chalkboard",
  "vintage_map",
  "synthwave",
  "botanical",
  "pixel_art",
  "noir",
  "origami",
  "aurora_lite",
] as const;

export type RareThemeId = typeof RARE_THEME_IDS[number];

export const RARE_THEMES = {
  neon_city: defineRareTheme({
    id: "neon_city",
    name: "Neon City",
    description: "A neon-lit district with pulsing outlines and scanline banners.",
    shopDescription: "Glowing borders, cyan-pink pulses, and a scanline city mood that never sits still.",
    previewColor: "#22D3EE",
    previewUnitTitle: "Afterglow Block",
    accent: "#22D3EE",
    surface: "#0B1120",
    text: "#ECFEFF",
    node: "#0EA5E9",
    nodeDark: "#164E63",
    trail: "#EC4899",
    background: "linear-gradient(180deg,#050816 0%,#111827 100%)",
    overlay: "radial-gradient(circle at 80% 16%, rgba(236,72,153,0.14), transparent 22%)",
    bannerPattern: "repeating-linear-gradient(180deg,rgba(255,255,255,0.05) 0px,rgba(255,255,255,0.05) 2px,transparent 2px,transparent 6px)",
    chestSkin: "vault_door",
    trailEffect: "neon_pulse",
    particleEffect: "glow_drift",
    nodeShape: "circle",
    ambientEffects: [
      { kind: "scanlines", opacity: 0.18 },
      { kind: "glints", color: "#22D3EE", count: 8, durationMs: 4800 },
    ],
  }),
  blueprint: defineRareTheme({
    id: "blueprint",
    name: "Blueprint",
    description: "Technical blue schematics with measured nodes and dashed planning lines.",
    shopDescription: "A drafting-table route with grid overlays, blueprint nodes, and measured progress.",
    previewColor: "#1D4ED8",
    previewUnitTitle: "Drafting Hall",
    accent: "#93C5FD",
    surface: "#1E3A8A",
    text: "#EFF6FF",
    node: "#60A5FA",
    nodeDark: "#1D4ED8",
    trail: "#BFDBFE",
    background: "linear-gradient(180deg,#15306F 0%,#1E3A8A 100%)",
    bannerPattern: "linear-gradient(90deg,rgba(255,255,255,0.08) 0%,rgba(255,255,255,0.08) 1px,transparent 1px,transparent 18px)",
    chestSkin: "vault_door",
    trailEffect: "dashed_technical",
    particleEffect: "sparkles",
    nodeShape: "circle",
    ambientEffects: [
      { kind: "grid", color: "#BFDBFE", opacity: 0.16 },
      { kind: "dots", color: "#E0F2FE", count: 10, durationMs: 5200 },
    ],
  }),
  comic_book: defineRareTheme({
    id: "comic_book",
    name: "Comic Book",
    description: "Bold ink outlines, halftone dots, and action-panel energy.",
    shopDescription: "Flat pop colors, punchy outlines, and comic-book motion in every banner and node.",
    previewColor: "#F97316",
    previewUnitTitle: "Action Alley",
    accent: "#F97316",
    surface: "#FFF7ED",
    text: "#111827",
    node: "#FACC15",
    nodeDark: "#111827",
    trail: "#FB7185",
    background: "linear-gradient(180deg,#FFF7ED 0%,#FDE68A 100%)",
    bannerPattern: "radial-gradient(circle, rgba(17,24,39,0.1) 12%, transparent 13%)",
    chestSkin: "default_chest",
    trailEffect: "steady_glow",
    particleEffect: "sparkles",
    nodeShape: "rounded",
    ambientEffects: [{ kind: "halftone", color: "#111827", opacity: 0.12 }],
  }),
  paper_craft: defineRareTheme({
    id: "paper_craft",
    name: "Paper Craft",
    description: "Folded-paper nodes, sketch lines, and off-white studio calm.",
    shopDescription: "A hand-built paper world with pencil routes and folded lesson markers.",
    previewColor: "#E7DCC8",
    previewUnitTitle: "Fold Workshop",
    accent: "#B45309",
    surface: "#F8F3EA",
    text: "#5B3713",
    node: "#FDE68A",
    nodeDark: "#C2410C",
    trail: "#A16207",
    background: "linear-gradient(180deg,#FBF7EE 0%,#F1E6D4 100%)",
    chestSkin: "classic_treasure",
    trailEffect: "sketch",
    particleEffect: "chalk_dust",
    nodeShape: "fold",
    ambientEffects: [{ kind: "paper-grain", color: "#B45309", opacity: 0.12 }],
  }),
  chalkboard: defineRareTheme({
    id: "chalkboard",
    name: "Chalkboard",
    description: "Smudged chalk textures with hand-drawn routes and circles.",
    shopDescription: "A classroom-blackboard theme with chalk dust, chalk nodes, and sketched progress lines.",
    previewColor: "#14532D",
    previewUnitTitle: "Lesson Board",
    accent: "#E2E8F0",
    surface: "#14532D",
    text: "#F8FAFC",
    node: "#E2E8F0",
    nodeDark: "#86EFAC",
    trail: "#E2E8F0",
    background: "linear-gradient(180deg,#0F3B27 0%,#185B3E 100%)",
    chestSkin: "classic_treasure",
    trailEffect: "chalk",
    particleEffect: "chalk_dust",
    nodeShape: "circle",
    ambientEffects: [{ kind: "chalk-dust", color: "#F8FAFC", count: 12, opacity: 0.18 }],
  }),
  vintage_map: defineRareTheme({
    id: "vintage_map",
    name: "Vintage Map",
    description: "Aged parchment with dotted expedition routes and explorer pins.",
    shopDescription: "Parchment paper, legend-card banners, and an expedition route you can almost trace by hand.",
    previewColor: "#D6B88C",
    previewUnitTitle: "Old Atlas",
    accent: "#92400E",
    surface: "#F5E6C8",
    text: "#5B3713",
    node: "#D97706",
    nodeDark: "#92400E",
    trail: "#B45309",
    background: "linear-gradient(180deg,#F8EED9 0%,#EAD2A6 100%)",
    chestSkin: "classic_treasure",
    trailEffect: "expedition_dots",
    particleEffect: "gold_dust",
    nodeShape: "marker",
    ambientEffects: [{ kind: "map-lines", color: "#92400E", opacity: 0.16 }],
  }),
  synthwave: defineRareTheme({
    id: "synthwave",
    name: "Synthwave",
    description: "Retrowave gradients, glowing nodes, and a slow pink-cyan pulse.",
    shopDescription: "Hot pink and cyan collide over a dark synth horizon with pulsing neon energy.",
    previewColor: "#EC4899",
    previewUnitTitle: "Sunset Strip",
    accent: "#22D3EE",
    surface: "#1F1235",
    text: "#FAF5FF",
    node: "#F472B6",
    nodeDark: "#7C3AED",
    trail: "#22D3EE",
    background: "linear-gradient(180deg,#120A23 0%,#2A174B 100%)",
    overlay: "linear-gradient(180deg,rgba(236,72,153,0.12) 0%,transparent 36%)",
    chestSkin: "portal",
    trailEffect: "neon_pulse",
    particleEffect: "glow_drift",
    nodeShape: "circle",
    ambientEffects: [
      { kind: "grid", color: "#EC4899", opacity: 0.12 },
      { kind: "scanlines", opacity: 0.08 },
    ],
  }),
  botanical: defineRareTheme({
    id: "botanical",
    name: "Botanical",
    description: "Elegant watercolor leaves, vine lines, and refined bright nodes.",
    shopDescription: "A graceful botanical study with airy paper, vinework, and delicate leaf-edged nodes.",
    previewColor: "#16A34A",
    previewUnitTitle: "Greenhouse Walk",
    accent: "#166534",
    surface: "#F8FFF7",
    text: "#14532D",
    node: "#86EFAC",
    nodeDark: "#166534",
    trail: "#22C55E",
    background: "linear-gradient(180deg,#F8FFF7 0%,#EBFCEB 100%)",
    chestSkin: "magic_lantern",
    trailEffect: "vine",
    particleEffect: "fireflies",
    nodeShape: "circle",
    ambientEffects: [{ kind: "leaves", color: "#22C55E", count: 8, opacity: 0.18 }],
  }),
  pixel_art: defineRareTheme({
    id: "pixel_art",
    name: "Pixel Art",
    description: "Chunky 8-bit blocks, sharp UI boxes, and sprite-like motion.",
    shopDescription: "A fully pixelated route with chunky nodes, CRT grid hints, and old-game charm.",
    previewColor: "#F97316",
    previewUnitTitle: "Coin Route",
    accent: "#FACC15",
    surface: "#111827",
    text: "#FFF7ED",
    node: "#F97316",
    nodeDark: "#EA580C",
    trail: "#FACC15",
    background: "linear-gradient(180deg,#0F172A 0%,#1E293B 100%)",
    chestSkin: "pixel_chest",
    trailEffect: "pixel",
    particleEffect: "pixel_burst",
    nodeShape: "pixel",
    ambientEffects: [
      { kind: "grid", color: "#FFFFFF", opacity: 0.06 },
      { kind: "pixel-walker", color: "#FACC15", durationMs: 12000 },
    ],
  }),
  noir: defineRareTheme({
    id: "noir",
    name: "Noir",
    description: "Monochrome contrast, hard shadows, and rain drifting through the scene.",
    shopDescription: "Black and white only, with stark light, hard edges, and subtle rain behind the path.",
    previewColor: "#111827",
    previewUnitTitle: "Midnight Case",
    accent: "#F8FAFC",
    surface: "#111827",
    text: "#F8FAFC",
    node: "#F8FAFC",
    nodeDark: "#374151",
    trail: "#E5E7EB",
    background: "linear-gradient(180deg,#050505 0%,#1F2937 100%)",
    chestSkin: "default_chest",
    trailEffect: "rain",
    particleEffect: "wisps",
    nodeShape: "circle",
    ambientEffects: [{ kind: "rain", color: "#F8FAFC", count: 20, opacity: 0.12 }],
  }),
  origami: defineRareTheme({
    id: "origami",
    name: "Origami",
    description: "Angular folded geometry with architectural white space.",
    shopDescription: "Clean folded shapes, crisp planes, and angular route segments like paper architecture.",
    previewColor: "#E5E7EB",
    previewUnitTitle: "Folded Court",
    accent: "#64748B",
    surface: "#FFFFFF",
    text: "#334155",
    node: "#CBD5E1",
    nodeDark: "#64748B",
    trail: "#94A3B8",
    background: "linear-gradient(180deg,#FFFFFF 0%,#F8FAFC 100%)",
    chestSkin: "default_chest",
    trailEffect: "origami",
    particleEffect: "sparkles",
    nodeShape: "fold",
    ambientEffects: [{ kind: "glints", color: "#94A3B8", count: 6, opacity: 0.12 }],
  }),
  aurora_lite: defineRareTheme({
    id: "aurora_lite",
    name: "Aurora Lite",
    description: "Dark night with a gentle aurora wash across the top edge.",
    shopDescription: "A restrained aurora shimmer that softens the whole route without overpowering it.",
    previewColor: "#22D3EE",
    previewUnitTitle: "Polar Edge",
    accent: "#A7F3D0",
    surface: "#0F172A",
    text: "#ECFEFF",
    node: "#93C5FD",
    nodeDark: "#0EA5E9",
    trail: "#22D3EE",
    background: "linear-gradient(180deg,#081120 0%,#152A45 100%)",
    chestSkin: "default_chest",
    trailEffect: "aurora",
    particleEffect: "glow_drift",
    nodeShape: "circle",
    ambientEffects: [{ kind: "aurora", color: "#22D3EE", colorSecondary: "#34D399", opacity: 0.2 }],
  }),
} satisfies Record<RareThemeId, ReturnType<typeof defineRareTheme<RareThemeId>>>;
